---
title: "Predicting urinary tract infection (UTI)"
output: html_document
date: "2022-11-26"
---

# Programming environment

```{r Determine settings, include=FALSE}
seed=2022-11-26
bioc_version='3.16'
```

```{r Determine computing requirements, include=FALSE}
# 1 == file size >=25MB
# 2 == considerably-long computation
# 3 == RAM >=8 GB
# 4 == require GPU
comp_req=c()#c(1,2,3,4)
```


```{r Load packages, include=FALSE}
library(tidyverse)
library(pbapply)
library(haven)
library(parallel)
library(doParallel)
library(lubridate)
library(ggpubr)
```

```{r Set theme, include=FALSE}
dslabs::ds_theme_set()
```

# Load raw data

```{r Obtain raw data file information, include=FALSE}
raw_data_info=
  list.files('raw_data',full.names=T) %>%
  data.frame(filename=.) %>%
  mutate(
    filesize=file.size(filename)
    ,code=
      filename %>%
      str_sub(
        start=
          sapply(.,\(x){
            str_locate_all(x,'/v_')[[1]][1,1]+3}
          )
        ,end=
          sapply(.,\(x){
            str_locate_all(x,'\\.sas7bdat')[[1]][1,1]-1
          })
      )
    ,type=str_sub(code,str_length(code),str_length(code))
    ,type=ifelse(type%in%c('s','t','w'),type,'')
    ,code=str_remove_all(code,'_s$|_t$|_w$')
  ) %>%
  group_by(code) %>%
  mutate(
    n=n()
    ,codesize=sum(filesize)
  ) %>%
  ungroup() %>%
  arrange(desc(n),codesize,code,type)
```

```{r Scrape raw data description from SAS-report PDF, include=FALSE}
raw_data_desc_sas=
  suppressWarnings(suppressMessages(
    read_csv('data/++«+ñjñp_A202206008.csv')
  )) %>%
  slice(7:nrow(.)) %>%
  filter(str_detect(pdf,'[:alpha:]')) %>%
  filter(
    !pdf%in%c(
      'A202206008: 2008-01-01 ~ 2020-12-31 ??????????'
      ,'? 59.09 GB'
      ,'???? (GB)'
      ,'TOTAL'
    )
  ) %>%
  mutate(pdf=str_to_lower(pdf)) %>%
  rename(code=pdf) %>%
  mutate(code=factor(code,unique(code)))
```

```{r Read raw data in SAS, include=FALSE}
if(all(c(1,2,3)%in%comp_req)){ # 50m 21s
  cl=detectCores()-2
  start=T; source('R/parallel_computing-codes.R')
  
  raw_data=
    raw_data_info %>%
    pull(filename) %>%
    pblapply(
      cl=cl
      ,read_sas=read_sas
      ,\(x,read_sas){
        if(str_detect(x,'v_mtrl_basic_s')){
          x %>%
            read_sas(encoding='UTF-8')
        }else{
          x %>%
            read_sas()
        }
    }) %>%
    `names<-`(
      raw_data_info %>%
        pull(filename) %>%
        str_remove_all('raw_data/|\\.sas7bdat')
    )
  
  saveRDS(raw_data,'data/raw_data.rds')
  start=F; source('R/parallel_computing-codes.R')
}else{
  raw_data=readRDS('data/raw_data.rds')
}
```

```{r Sanity check of data file completeness, eval=FALSE, include=FALSE}
# The numbers of rows are the same,
# while the numbers of fields are different.
# But, manual check by SAS EG shows the same numbers of fields.
raw_data %>%
  lapply(dim) %>%
  lapply(t) %>%
  lapply(data.frame) %>%
  lapply(`colnames<-`,c('nrow','ncol')) %>%
  lapply(X=names(.),Y=.,\(X,Y)mutate(Y[[X]],code=X)) %>%
  do.call(rbind,.) %>%
  mutate(
    type=str_sub(code,str_length(code),str_length(code))
    ,type=ifelse(type%in%c('s','t','w'),type,'z')
    ,code=str_remove_all(code,'^v_|_s$|_t$|_w$')
  ) %>%
  left_join(
    raw_data_info %>%
      select(code,type,filesize)
    ,by=c('code','type')
  ) %>%
  mutate(filesize=round(filesize/10^9,2)) %>%
  rbind(
    group_by(.,ncol,code) %>%
      summarize(
        type='all'
        ,nrow=sum(nrow)
        ,filesize=sum(filesize)
        ,.groups='drop'
      )
  ) %>%
  pivot_wider(
    names_from='type'
    ,values_from=c('nrow','filesize')
    ,values_fill=0
  ) %>%
  mutate(code=factor(code,levels(raw_data_desc_sas$code))) %>%
  right_join(
    raw_data_desc_sas
    ,by='code'
  ) %>%
  mutate_all(\(x){
    if(is.factor(x)){
      x
    }else{
      ifelse(is.na(x),0,x)
    }
  }) %>%
  arrange(code)
```

```{r Determine FEE_CODE for urine cath, include=FALSE}
uri_cath=
  raw_data %>%
  .[str_detect(names(.),'^v_fee_basic')] %>%
  lapply(select,FEE_CODE,FEE_DESC) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  filter(
    str_detect(
      str_to_lower(FEE_CODE)
      ,filter(.,str_detect(str_to_lower(FEE_DESC),'cath|導|foley')) %>%
        filter(str_detect(str_to_lower(FEE_DESC),'uri|尿|icp')) %>%
        filter(str_detect(str_to_lower(FEE_DESC),'dwel|留置|icp')) %>%
        pull(FEE_CODE) %>%
        str_sub(1,str_count(.)-1) %>%
        str_to_lower() %>%
        unique() %>%
        paste0(collapse='|')
    )
  ) %>%
  mutate(exist='yes') %>%
  spread(HOSP,exist,fill='no') %>%
  arrange(FEE_CODE,w,t,s) %>%
  filter(str_detect(str_to_lower(FEE_CODE),'f470130|f47013c|f470140|f47014c'))

uri_cath %>%
  knitr::kable()
```

```{r Re-check FEE_CODE for urine cath, eval=FALSE, include=FALSE}
raw_data %>%
  .[str_detect(names(.),'^v_fee_ins')] %>%
  lapply(select,FEE_CODE) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  filter(FEE_CODE%in%uri_cath$FEE_CODE) %>%
  filter(!duplicated(.)) %>%
  left_join(
    raw_data %>%
      .[str_detect(names(.),'^v_fee_basic')] %>%
      lapply(select,FEE_CODE,FEE_DESC) %>%
      lapply(
        X=names(.)
        ,Y=.
        ,\(X,Y)
        Y[[X]] %>%
          mutate(
            HOSP=
              str_sub(X,str_count(X),str_count(X))
          )
      ) %>%
      do.call(rbind,.)
    ,by=c('FEE_CODE','HOSP')
  ) %>%
  arrange(FEE_CODE,HOSP)
```

```{r FEE_CODE distribution per hospital and type, eval=FALSE, include=FALSE}
raw_data %>%
  .[str_detect(names(.),'^v_opd_fee|^v_ipd_fee')] %>%
  lapply(filter,FEE_CODE%in%uri_cath$FEE_CODE) %>%
  lapply(select_at,c(
    'FEE_NO'
    ,'FEE_CODE'
    ,colnames(.) %>%
      .[str_detect(str_to_lower(.),'date|time')]
  )) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
        ,TYPE=
          str_sub(X,3,5)
      )
  ) %>%
  do.call(rbind,.) %>%
  group_by(HOSP,TYPE,FEE_CODE) %>%
  summarize(n=n()) %>%
  pivot_wider(names_from=c('HOSP','TYPE'),values_from='n',values_fill=0)
```

```{r Urine cath offsets, eval=FALSE, fig.height=15, fig.width=5, include=FALSE}
raw_data %>%
  .[str_detect(names(.),'^v_opd_fee|^v_ipd_fee')] %>%
  lapply(filter,FEE_CODE%in%uri_cath$FEE_CODE) %>%
  lapply(
    \(x)
    select_at(
        x
        ,c(
          'FEE_NO'
          ,'FEE_CODE'
          ,colnames(x) %>%
            .[str_detect(str_to_lower(.),'date|time')]
        )
      ) %>%
      mutate_all(as.character) %>%
      mutate_all(\(x)ifelse(x=='',NA,x)) %>%
      mutate(seq=seq(nrow(.))) %>%
      gather(key,value,-seq,-FEE_NO,-FEE_CODE) %>%
      filter(!is.na(value)) %>%
      mutate(
        key2=
          case_when(
            str_detect(str_to_lower(key),'date$')~'DATE'
            ,str_detect(str_to_lower(key),'time$')~'TIME'
            ,TRUE~''
          )
        ,key=
          str_remove_all(key,paste0('_',key2))
      ) %>%
      spread(key2,value) %>%
      mutate(
        TIME=
          ifelse(
            !is.na(DATE) & is.na(TIME)
            ,'0000'
            ,TIME
          )
      ) %>%
      mutate(
        DATE=
          as.numeric(DATE)
        ,DATE=
          DATE+(2023-112)*10000
        ,DATE=
          paste0(
            str_sub(DATE,1,4)
            ,'-'
            ,str_sub(DATE,5,6)
            ,'-'
            ,str_sub(DATE,7,8)
          )
        ,TIME=
          paste0(
            str_sub(TIME,1,2)
            ,':'
            ,str_sub(TIME,3,4)
          )
      ) %>%
      unite(DATETIME,DATE,TIME,sep=' ') %>%
      mutate(DATETIME=ymd_hm(DATETIME))
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
        ,TYPE=
          str_sub(X,3,5)
      )
  ) %>%
  do.call(rbind,.) %>%
  left_join(
    filter(.,key%in%c('OPD','IPD')) %>%
      mutate(key='APD_DATETIME') %>%
      spread(key,DATETIME)
    ,by=c('seq','HOSP','TYPE','FEE_CODE','FEE_NO')
  ) %>%
  filter(!key%in%c('OPD','IPD')) %>%
  group_by(seq,HOSP,TYPE,FEE_CODE,FEE_NO) %>%
  mutate(DATETIME=as.duration(DATETIME-APD_DATETIME)/ddays(1)) %>%
  ungroup() %>%
  group_by(HOSP,TYPE,FEE_CODE,key) %>%
  summarize(
    avg=mean(DATETIME)
    ,std=sd(DATETIME)
    ,q1=quantile(DATETIME,0.25)
    ,q2=quantile(DATETIME,0.5)
    ,q3=quantile(DATETIME,0.75)
    ,.groups='drop'
  ) %>%
  arrange(HOSP,TYPE,FEE_CODE,q2) %>%
  left_join(
    raw_data %>%
      .[str_detect(names(.),'^v_fee_basic')] %>%
      lapply(select,FEE_CODE,FEE_DESC) %>%
      lapply(
        X=names(.)
        ,Y=.
        ,\(X,Y)
        Y[[X]] %>%
          mutate(
            HOSP=
              str_sub(X,str_count(X),str_count(X))
          )
      ) %>%
      do.call(rbind,.)
    ,by=c('FEE_CODE','HOSP')
  ) %>%
  unite(FEE_CODE,FEE_CODE,FEE_DESC,sep=':') %>%
  lapply(
    X=unique(.$FEE_CODE)
    ,Y=.
    ,\(X,Y)
    Y %>%
      filter(FEE_CODE==X) %>%
      mutate(key=reorder(key,desc(q2))) %>%
      ggplot(aes(key,q2)) +
      geom_errorbar(aes(ymin=q1,ymax=q3),width=0.1,size=1) +
      geom_point(size=3) +
      facet_wrap(HOSP~TYPE,scales='free') +
      coord_flip() +
      ggtitle(label='',subtitle=X)
  ) %>%
  lapply(X=1,Y=.,\(X,Y)
    ggarrange(
      Y[[1]]
      ,Y[[2]]
      ,Y[[3]]
      ,Y[[4]]
      ,ggarrange(
        Y[[5]],Y[[6]]
        ,ncol=2
      )
      ,Y[[7]]
      ,Y[[8]]
      ,nrow=7
    )
  ) %>%
  .[[1]]
```

```{r Identify the most optimal offsets, eval=FALSE, include=FALSE}
raw_data %>%
  .[str_detect(names(.),'^v_opd_fee|^v_ipd_fee')] %>%
  lapply(filter,FEE_CODE%in%uri_cath$FEE_CODE) %>%
  lapply(
    \(x)
    select_at(
        x
        ,c(
          'FEE_NO'
          ,'FEE_CODE'
          ,colnames(x) %>%
            .[str_detect(str_to_lower(.),'date|time')]
        )
      ) %>%
      mutate_all(as.character) %>%
      mutate_all(\(x)ifelse(x=='',NA,x)) %>%
      mutate(seq=seq(nrow(.))) %>%
      gather(key,value,-seq,-FEE_NO,-FEE_CODE) %>%
      filter(!is.na(value)) %>%
      mutate(
        key2=
          case_when(
            str_detect(str_to_lower(key),'date$')~'DATE'
            ,str_detect(str_to_lower(key),'time$')~'TIME'
            ,TRUE~''
          )
        ,key=
          str_remove_all(key,paste0('_',key2))
      ) %>%
      spread(key2,value) %>%
      mutate(
        TIME=
          ifelse(
            !is.na(DATE) & is.na(TIME)
            ,'0000'
            ,TIME
          )
      ) %>%
      mutate(
        DATE=
          as.numeric(DATE)
        ,DATE=
          DATE+(2023-112)*10000
        ,DATE=
          paste0(
            str_sub(DATE,1,4)
            ,'-'
            ,str_sub(DATE,5,6)
            ,'-'
            ,str_sub(DATE,7,8)
          )
        ,TIME=
          paste0(
            str_sub(TIME,1,2)
            ,':'
            ,str_sub(TIME,3,4)
          )
      ) %>%
      unite(DATETIME,DATE,TIME,sep=' ') %>%
      mutate(DATETIME=ymd_hm(DATETIME))
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
        ,TYPE=
          str_sub(X,3,5)
      )
  ) %>%
  do.call(rbind,.) %>%
  left_join(
    spread(.,key,DATETIME)
    ,by=c('FEE_NO','FEE_CODE','seq','HOSP','TYPE')
  ) %>%
  gather(key2,DATETIME2,-FEE_NO,-FEE_CODE,-seq,-key,-DATETIME,-HOSP,-TYPE) %>%
  filter(!is.na(DATETIME2)) %>%
  filter(key2!=key) %>%
  unite(keys,key2,key,sep='-') %>%
  mutate(duration=as.duration(DATETIME2-DATETIME)/ddays(1)) %>%
  group_by(HOSP,TYPE,FEE_CODE,keys) %>%
  summarize(
    neg_d=sum(duration<0,na.rm=T)
    ,pos_d012=sum(duration>=0 & duration<3,na.rm=T)
    ,pos_d3=sum(duration>=3,na.rm=T)
    ,n=n()
    ,m=sum(is.na(duration),na.rm=T)
    ,min=min(duration,na.rm=T)
    ,q1=quantile(duration,0.25,na.rm=T)
    ,q2=quantile(duration,0.5,na.rm=T)
    ,q3=quantile(duration,0.75,na.rm=T)
    ,max=max(duration,na.rm=T)
    ,o=sum(
      duration<(
        quantile(duration,0.25,na.rm=T)
        -1.5*(quantile(duration,0.75,na.rm=T)-quantile(duration,0.25,na.rm=T))
      )
      | duration>(
        quantile(duration,0.75,na.rm=T)
        +1.5*(quantile(duration,0.75,na.rm=T)-quantile(duration,0.25,na.rm=T))
      )
      ,na.rm=T
    )
    ,avg=mean(ifelse(
      duration<(
        quantile(duration,0.25,na.rm=T)
        -1.5*(quantile(duration,0.75,na.rm=T)-quantile(duration,0.25,na.rm=T))
      )
      | duration>(
        quantile(duration,0.75,na.rm=T)
        +1.5*(quantile(duration,0.75,na.rm=T)-quantile(duration,0.25,na.rm=T))
      )
      ,NA
      ,duration
    ),na.rm=T)
    ,std=sd(ifelse(
      duration<(
        quantile(duration,0.25,na.rm=T)
        -1.5*(quantile(duration,0.75,na.rm=T)-quantile(duration,0.25,na.rm=T))
      )
      | duration>(
        quantile(duration,0.75,na.rm=T)
        +1.5*(quantile(duration,0.75,na.rm=T)-quantile(duration,0.25,na.rm=T))
      )
      ,NA
      ,duration
    ),na.rm=T)
    ,.groups='drop'
  ) %>%
  arrange(FEE_CODE,keys)
```

```{r Create selector of urine cath at order level, include=FALSE}
if(all(c(2)%in%comp_req)){ # 01m 00s
  uri_cath_d_order_selector0=
    raw_data %>%
    .[str_detect(names(.),'^v_ipd_fee')] %>%
    lapply(filter,FEE_CODE%in%uri_cath$FEE_CODE) %>%
    lapply(\(x)
      x %>%
        select_at(
          colnames(.) %>%
            .[str_detect(
              .
              ,paste0(
                c(
                  '^CHR_NO'
                  ,'^FEE_NO'
                  ,'^FEE_DATE'
                  ,'^FEE_TIME'
                  ,'^FEE_CODE'
                  ,'^SEQ_NO'
                  ,'^START'
                  ,'^DC'
                )
                ,collapse='|'
              )
            )]
        )
    ) %>%
    lapply(
      X=names(.)
      ,Y=.
      ,\(X,Y)
      Y[[X]] %>%
        mutate(
          HOSP=
            str_sub(X,str_count(X),str_count(X))
          ,TYPE=
            str_sub(X,3,5)
        )
    ) %>%
    do.call(rbind,.) %>%
    mutate(
      START_TIME=
        ifelse(
          !is.na(START_DATE) & is.na(START_TIME)
          ,'0000'
          ,START_TIME
        )
      ,DC_TIME=
        ifelse(
          !is.na(DC_DATE) & is.na(DC_TIME)
          ,'0000'
          ,DC_TIME
        )
    ) %>%
    mutate_at(
      c('START_DATE','DC_DATE')
      ,\(x)
      as.numeric(x)+(2023-112)*10000
    ) %>%
    mutate_at(
      c('START_DATE','DC_DATE')
      ,\(x)
      paste0(
        str_sub(x,1,4)
        ,'-'
        ,str_sub(x,5,6)
        ,'-'
        ,str_sub(x,7,8)
      )
    ) %>%
    mutate_at(
      c('START_TIME','DC_TIME')
      ,\(x)
      paste0(
        str_sub(x,1,2)
        ,':'
        ,str_sub(x,3,4)
      )
    ) %>%
    unite(START,START_DATE,START_TIME,sep=' ') %>%
    unite(DC,DC_DATE,DC_TIME,sep=' ') %>%
    mutate_at(
      c('START','DC')
      ,\(x)
      ifelse(
        str_count(x)==16
        & str_count(x,'-')==2
        & str_count(x,' ')==1
        & str_count(x,'\\:')==1
        ,x
        ,NA
      )
    ) %>%
    mutate_at(c('START','DC'),ymd_hm) %>%
    arrange(HOSP,CHR_NO,TYPE,FEE_NO,START,DC) %>%
    mutate(merged=1)
  
  uri_cath_d_order_selector=
    uri_cath_d_order_selector0
  
  # %>%
  #   filter(FEE_CODE=='F47014C')
  
  uri_cath_d_order_selector_nrow=
    uri_cath_d_order_selector %>%
    nrow()
  
  iter=0
  
  while(iter<1){
    cat('iter',iter,'nrow',uri_cath_d_order_selector_nrow,'\n')
  
    uri_cath_d_order_selector=
      uri_cath_d_order_selector %>%
      group_by(HOSP,CHR_NO,TYPE,FEE_NO) %>%
      mutate(seq=seq(n())) %>%
      ungroup() %>%
      left_join(
        select(.,HOSP,CHR_NO,TYPE,FEE_NO,seq,DC) %>%
          mutate(seq=seq+1) %>%
          rename(prev_DC=DC)
        ,by=c('HOSP','CHR_NO','TYPE','FEE_NO','seq')
      ) %>%
      mutate(dist=as.duration(START-prev_DC)/ddays(1)) %>%
      mutate(dist=ifelse(is.na(dist),0,dist)) %>%
      group_by(HOSP,CHR_NO,TYPE,FEE_NO) %>%
      mutate(unmerged=dist>1) %>%
      mutate(seq2=cumsum(unmerged)+1) %>%
      ungroup() %>%
      select(-seq,-prev_DC,-dist,-unmerged) %>%
      rename(seq=seq2) %>%
      group_by(HOSP,CHR_NO,TYPE,FEE_NO,seq) %>%
      mutate(
        FEE_CODE=paste0(sort(unique(FEE_CODE)),collapse=' & ')
        ,START=min(START)
        ,DC=max(DC)
        ,merged=sum(merged)
      ) %>%
      slice(1) %>%
      ungroup() %>%
      select(-seq)
  
    if(uri_cath_d_order_selector_nrow>nrow(uri_cath_d_order_selector)){
      iter=0
    }else{
      iter=iter+1
    }
  
    uri_cath_d_order_selector_nrow=
      uri_cath_d_order_selector %>%
      nrow()
  }
  
  rm(iter,uri_cath_d_order_selector_nrow)
  
  uri_cath_d_order_selector=
    uri_cath_d_order_selector %>%
    mutate(duration=as.duration(DC-START)/ddays(1)) %>%
    # filter(duration>2) %>%
    select(
      HOSP,CHR_NO
      ,TYPE,FEE_NO
      ,FEE_DATE,FEE_TIME,FEE_CODE,SEQ_NO,SEQ_NO2
      ,START,DC,duration
      ,merged
    )
  
  uri_cath_d_order_selector0=
    uri_cath_d_order_selector0 %>%
    mutate(duration=as.duration(DC-START)/ddays(1)) %>%
    select(
      HOSP,CHR_NO
      ,TYPE,FEE_NO
      ,FEE_DATE,FEE_TIME,FEE_CODE,SEQ_NO,SEQ_NO2
      ,START,DC,duration
    )
  
  uri_cath_d_order_selector0 %>%
    saveRDS('data/uri_cath_d_order_selector0.rds')
  
  uri_cath_d_order_selector %>%
    saveRDS('data/uri_cath_d_order_selector.rds')
}else{
  uri_cath_d_order_selector0=
    readRDS('data/uri_cath_d_order_selector0.rds')
  
  uri_cath_d_order_selector=
    readRDS('data/uri_cath_d_order_selector.rds')
}
```

```{r Create selector of urine cath at prediction level, include=FALSE}
if(all(c(2)%in%comp_req)){ # 06m 03s
  uri_cath_d_pred_selector=
    uri_cath_d_order_selector %>%
    pblapply(X=seq(nrow(.)),Y=.,\(X,Y){
      Y %>%
        slice(X) %>%
        lapply(
          X=seq(0,ceiling(ifelse(is.na(.$duration),0,.$duration))+2)
          ,Y=.
          ,\(X,Y)Y
        ) %>%
        do.call(rbind,.) %>%
        mutate(pred_day=seq(0,n()-1))
    }) %>%
    do.call(rbind,.) %>%
    mutate(pred_day=START+ddays(pred_day))
  
  saveRDS(uri_cath_d_pred_selector,'data/uri_cath_d_pred_selector.rds')
}else{
  uri_cath_d_pred_selector=readRDS('data/uri_cath_d_pred_selector.rds')
}
```

```{r Create selector of urine cath at visit level, include=FALSE}
if(all(c(2)%in%comp_req)){ # 01m 00s
  uri_cath_d_visit_selector=
    raw_data %>%
    .[str_detect(names(.),'^v_ipd_basic')] %>%
    lapply(\(x)
      x %>%
        select_at(
          colnames(.) %>%
            .[str_detect(.,'^CHR_NO|^FEE_NO')]
        )
    ) %>%
    lapply(
      X=names(.)
      ,Y=.
      ,\(X,Y)
      Y[[X]] %>%
        mutate(
          HOSP=
            str_sub(X,str_count(X),str_count(X))
          ,TYPE=
            str_sub(X,3,5)
        )
    ) %>%
    do.call(rbind,.) %>%
    filter(
      paste0(HOSP,'_',CHR_NO,'_',TYPE,'_',FEE_NO)
      %in%paste0(
        uri_cath_d_order_selector$HOSP
        ,'_'
        ,uri_cath_d_order_selector$CHR_NO
        ,'_'
        ,uri_cath_d_order_selector$TYPE
        ,'_'
        ,uri_cath_d_order_selector$FEE_NO
      )
    ) %>%
    select(
      HOSP,CHR_NO
      ,TYPE,FEE_NO
    )
  
  saveRDS(uri_cath_d_visit_selector,'data/uri_cath_d_visit_selector.rds')
}else{
  uri_cath_d_visit_selector=readRDS('data/uri_cath_d_visit_selector.rds')
}
```

```{r Create selector of urine cath at patient level, include=FALSE}
if(all(c(2)%in%comp_req)){ # 01m 00s
  uri_cath_d_patient_selector=
    raw_data %>%
    .[str_detect(names(.),'^v_chr_basic')] %>%
    lapply(\(x)
      x %>%
        select_at(
          colnames(.) %>%
            .[str_detect(.,'^CHR_NO')]
        )
    ) %>%
    lapply(
      X=names(.)
      ,Y=.
      ,\(X,Y)
      Y[[X]] %>%
        mutate(
          HOSP=
            str_sub(X,str_count(X),str_count(X))
        )
    ) %>%
    do.call(rbind,.) %>%
    filter(
      paste0(HOSP,'_',CHR_NO)
      %in%paste0(
        uri_cath_d_visit_selector$HOSP
        ,'_'
        ,uri_cath_d_visit_selector$CHR_NO
      )
    ) %>%
    select(HOSP,CHR_NO)
  
  uri_cath_d_patient_selector %>%
    saveRDS('data/uri_cath_d_patient_selector.rds')
}else{
  uri_cath_d_patient_selector=
    readRDS('data/uri_cath_d_patient_selector.rds')
}
```

```{r Find an example in merging of Foley duration, include=FALSE}
seq_example=
  uri_cath_d_order_selector %>%
  group_by(HOSP,CHR_NO,TYPE,FEE_NO,FEE_CODE) %>%
  mutate(earliest=min(START,na.rm=T)) %>%
  ungroup() %>%
  arrange(earliest) %>%
  left_join(
    select(.,HOSP,CHR_NO,TYPE,FEE_NO) %>%
      filter(!duplicated(.)) %>%
      mutate(ID=seq(nrow(.)))
    ,by=c('HOSP','CHR_NO','TYPE','FEE_NO')
  ) %>%
  filter(
    ID
    %in%pull(
      group_by(.,ID) %>%
        summarize(n=n(),.groups='drop') %>%
        filter(n==4)
      ,ID
    )
  ) %>%
  arrange(ID,START) %>%
  group_by(HOSP,CHR_NO,TYPE,FEE_NO) %>%
  summarize(type=length(unique(FEE_CODE)),.groups='drop') %>%
  filter(type>1) %>%
  select(CHR_NO,FEE_NO) %>%
  slice(1:4)
```

```{r Merging examples, eval=FALSE, fig.height=5, fig.width=7, include=FALSE}
uri_cath_d_order_selector0 %>%
  group_by(HOSP,CHR_NO,TYPE,FEE_NO) %>%
  mutate(earliest=min(START,na.rm=T)) %>%
  ungroup() %>%
  arrange(earliest) %>%
  filter(
    paste0(CHR_NO,FEE_NO)%in%paste0(seq_example$CHR_NO,seq_example$FEE_NO)
  ) %>%
  mutate(status='Before merging') %>%
  rbind(
    uri_cath_d_order_selector %>%
      select(-merged) %>%
      group_by(HOSP,CHR_NO,TYPE,FEE_NO) %>%
      mutate(earliest=min(START,na.rm=T)) %>%
      ungroup() %>%
      arrange(earliest) %>%
      filter(
        paste0(CHR_NO,FEE_NO)%in%paste0(seq_example$CHR_NO,seq_example$FEE_NO)
      ) %>%
      mutate(status='After merging')
  ) %>%
  left_join(
    uri_cath_d_order_selector0 %>%
      select(HOSP,CHR_NO,TYPE,FEE_NO) %>%
      rbind(
        uri_cath_d_order_selector %>%
          select(HOSP,CHR_NO,TYPE,FEE_NO)
      ) %>%
      filter(!duplicated(.)) %>%
      mutate(ID=seq(nrow(.)))
    ,by=c('HOSP','CHR_NO','TYPE','FEE_NO')
  ) %>%
  ggplot(aes(status,START+duration/2,color=FEE_CODE)) +
  geom_linerange(aes(ymin=START,ymax=DC),size=0.5,alpha=0.75) +
  geom_point(size=1.5,alpha=0.75) +
  facet_wrap(ID~.,scales='free',ncol=1) +
  coord_flip() +
  scale_x_discrete('') +
  scale_y_datetime(
    ''
    ,date_breaks='1 month'
    ,date_labels='%Y-%m'
    ,date_minor_breaks='1 day'
  )
```

```{r List variable to save results of selection, eval=FALSE, include=FALSE}
# selection=list()
# selection %>% saveRDS('data/selection.rds')
selection=readRDS('data/selection.rds')
```

```{r Save results of every selection scenario, eval=FALSE, include=FALSE}
# selection$start_upd_gt2_idw=
#   rbind(
#     uri_cath_d_pred_selector %>%
#       mutate(level='prediction') %>%
#       group_by(HOSP,TYPE,level) %>%
#       summarize(n=n(),.groups='drop') %>%
#       spread(HOSP,n)
#     ,uri_cath_d_order_selector %>%
#       mutate(level='order') %>%
#       group_by(HOSP,TYPE,level) %>%
#       summarize(n=n(),.groups='drop') %>%
#       spread(HOSP,n)
#     ,uri_cath_d_visit_selector %>%
#       mutate(level='visit') %>%
#       group_by(HOSP,TYPE,level) %>%
#       summarize(n=n(),.groups='drop') %>%
#       spread(HOSP,n)
#     ,uri_cath_d_patient_selector %>%
#       mutate(TYPE=NA,level='patient') %>%
#       group_by(HOSP,TYPE,level) %>%
#       summarize(n=n(),.groups='drop') %>%
#       spread(HOSP,n)
#   ) %>%
#   mutate(dataset='start_upd_gt2_idw')
```

```{r Results of several selection scenarios, eval=FALSE, include=FALSE}
selection %>%
  lapply(
    X=seq(length(.))
    ,Y=.
    ,\(X,Y)mutate(Y[[X]],seq=X,seq2=seq(nrow(Y[[X]])))
  ) %>%
  lapply(gather,HOSP,n,-TYPE,-level,-dataset,-seq,-seq2) %>%
  do.call(rbind,.) %>%
  spread(HOSP,n,fill=0) %>%
  mutate(
    dataset=
      ifelse(
        !str_detect(dataset,'_idw')
        ,paste0(dataset,'_all')
        ,dataset
      )
  ) %>%
  separate(dataset,c('start','end','min_duration','cath_type'),sep='_') %>%
  mutate(
    min_duration=
      case_when(
        min_duration=='all'~'any duration (inc. missing value)'
        ,min_duration=='gt0'~'greater than 0 day (exc. missing value)'
        ,min_duration=='gt1'~'greater than 1 day'
        ,min_duration=='gt2'~'greater than 2 days'
      )
    ,cath_type=
      case_when(
        cath_type=='all'~'indwelling + intermittent'
        ,cath_type=='idw'~'indwelling'
      )
  ) %>%
  group_by(start,end,min_duration,cath_type) %>%
  mutate(
    s_epv_cp20_p10=round(max(ifelse(level=='prediction',s,NA),na.rm=T)*0.1/20,2)
    ,s_epv_cp28_p10=round(max(ifelse(level=='prediction',s,NA),na.rm=T)*0.1/28,2)
  ) %>%
  arrange(desc(min_duration),cath_type,end,desc(seq),seq2) %>%
  select(-seq,-seq2) %>%
  # write_csv('selection.csv')
  knitr::kable()
```

```{r Chosen selection scenarios, include=FALSE}
uri_cath_d3=
  list(
    prediction=
      uri_cath_d_pred_selector %>%
      filter(duration>2)
    ,order=
      uri_cath_d_order_selector %>%
      filter(duration>2)
    ,visit=
      uri_cath_d_visit_selector %>%
      filter(
        paste0(HOSP,CHR_NO,TYPE,FEE_NO)
        %in%pull(
          uri_cath_d_order_selector %>%
            filter(duration>2) %>%
            mutate(selector=paste0(HOSP,CHR_NO,TYPE,FEE_NO))
          ,selector
        )
      )
    ,patient=
      uri_cath_d_patient_selector %>%
      filter(
        paste0(HOSP,CHR_NO)
        %in%pull(
          uri_cath_d_order_selector %>%
            filter(duration>2) %>%
            mutate(selector=paste0(HOSP,CHR_NO))
          ,selector
        )
      )
  )

uri_cath_d=
  list(
    prediction=uri_cath_d_pred_selector
    ,order=uri_cath_d_order_selector
    ,visit=uri_cath_d_visit_selector
    ,patient=uri_cath_d_patient_selector
  )
```

```{r Sanity check the number of selected samples, eval=FALSE, include=FALSE}
uri_cath_d3 %>%
  lapply(group_by,HOSP) %>%
  lapply(summarize,n=n()) %>%
  lapply(X=names(.),Y=.,\(X,Y)mutate(Y[[X]],level=X)) %>%
  lapply(spread,HOSP,n) %>%
  do.call(rbind,.)

uri_cath_d %>%
  lapply(group_by,HOSP) %>%
  lapply(summarize,n=n()) %>%
  lapply(X=names(.),Y=.,\(X,Y)mutate(Y[[X]],level=X)) %>%
  lapply(spread,HOSP,n) %>%
  do.call(rbind,.)
```

```{r Only takes the latest cath. per visit, eval=FALSE, include=FALSE}
uri_cath_d3[c('prediction','order')] %>%
  lapply(group_by,HOSP,CHR_NO,TYPE,FEE_NO) %>%
  lapply(filter,START==max(START)) %>%
  lapply(group_by,HOSP) %>%
  lapply(summarize,n=n()) %>%
  lapply(X=names(.),Y=.,\(X,Y)mutate(Y[[X]],level=X)) %>%
  lapply(spread,HOSP,n) %>%
  do.call(rbind,.)

uri_cath_d[c('prediction','order')] %>%
  lapply(group_by,HOSP,CHR_NO,TYPE,FEE_NO) %>%
  lapply(filter,START==max(START)) %>%
  lapply(group_by,HOSP) %>%
  lapply(summarize,n=n()) %>%
  lapply(X=names(.),Y=.,\(X,Y)mutate(Y[[X]],level=X)) %>%
  lapply(spread,HOSP,n) %>%
  do.call(rbind,.)
```
```{r Show CHR_NO overlaps among hospitals, eval=FALSE, include=FALSE}
raw_data %>%
  .[str_detect(names(.),'^v_chr_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^CHR_NO')]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  group_by(CHR_NO) %>%
  summarize(HOSP=paste0(HOSP,collapse=',')) %>%
  group_by(HOSP) %>%
  summarize(n=n(),.groups='drop')
```

```{r Required table per variable, include=FALSE}
tab_req=read_csv('data/tab_req.csv')
```

```{r Table connection, include=FALSE}
tab_conn=
  read_csv('data/tab_conn.csv') %>%
  filter(
    str_detect(parent,paste0(paste0('^',tab_req$table,'$'),collapse='|'))
    | str_detect(child,paste0(paste0('^',tab_req$table,'$'),collapse='|'))
  )
```

```{r Check table availability, include=FALSE}
tab_avail=
  tab_req %>%
  group_by(table) %>%
  summarize(n=n()) %>%
  pull(table) %>%
  .[!is.na(.)] %>%
  lapply(X=1:2,Y=.,\(X,Y){
    if(X==1){
      Y
    }else{
      raw_data %>%
        names() %>%
        str_remove_all('^v_|_s$|_t$|_w$') %>%
        str_to_upper()
    }
  }) %>%
  sapply(X=1:3,Y=.,\(X,Y){
    if(X==1){
      Y[[1]] %>%
        setdiff(Y[[2]])
    }else if(X==2){
      Y[[1]] %>%
        intersect(Y[[2]])
    }else{
      Y[[2]] %>%
        setdiff(Y[[1]])
    }
  }) %>%
  `names<-`(c(
    'Unavailable required tables'
    ,'Available required tables'
    ,'Available unrequired tables'
  ))
```

```{r Variables requiring unavailable tables, eval=FALSE, include=FALSE}
tab_req %>%
  mutate(unavail=table%in%tab_avail$`Unavailable required tables`) %>%
  filter(
    variable
    %in%filter(.,unavail)$variable
  )
```

```{r Select subject and table of interests, include=FALSE}
if(all(c(1,2)%in%comp_req)){
  raw_data1a=
    raw_data %>%
    .[str_to_upper(str_remove_all(names(.),'^v_|_s$|_t$|_w$'))
      %in%tab_req$table] %>%
    lapply(X=names(.),Y=.,\(X,Y){
      if('CHR_NO'%in%colnames(Y[[X]])){
        Y[[X]] %>%
          filter(
            CHR_NO
            %in%pull(
              uri_cath_d3$patient %>%
                filter(HOSP==str_sub(X,str_count(X),str_count(X)))
              ,CHR_NO
            )
          )
      }else{
        Y[[X]]
      }
    }) %>%
    `names<-`(
      raw_data %>%
        .[str_to_upper(str_remove_all(names(.),'^v_|_s$|_t$|_w$'))
          %in%tab_req$table] %>%
        names()
    )
  
  saveRDS(raw_data1a,'data/raw_data1a.rds')
  
  raw_data1b=
    raw_data %>%
    .[str_to_upper(str_remove_all(names(.),'^v_|_s$|_t$|_w$'))
      %in%tab_req$table] %>%
    lapply(X=names(.),Y=.,\(X,Y){
      if('CHR_NO'%in%colnames(Y[[X]])){
        Y[[X]] %>%
          filter(
            CHR_NO
            %in%pull(
              uri_cath_d$patient %>%
                filter(HOSP==str_sub(X,str_count(X),str_count(X)))
              ,CHR_NO
            )
          )
      }else{
        Y[[X]]
      }
    }) %>%
    `names<-`(
      raw_data %>%
        .[str_to_upper(str_remove_all(names(.),'^v_|_s$|_t$|_w$'))
          %in%tab_req$table] %>%
        names()
    )
  
  saveRDS(raw_data1b,'data/raw_data1b.rds')
}else{
  raw_data1a=readRDS('data/raw_data1a.rds')
  raw_data1b=readRDS('data/raw_data1b.rds')
}
```

```{r Check row reduction, eval=FALSE, include=FALSE}
raw_data %>%
  sapply(dim) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var='table') %>%
  left_join(
    raw_data1a %>%
      sapply(dim) %>%
      t() %>%
      as.data.frame() %>%
      rownames_to_column(var='table')
    ,by='table'
  ) %>%
  mutate(
    row_reduction=V1.x-V1.y
    ,row_reduction_p=round(row_reduction/V1.x*100,3)
  ) %>%
  filter(!is.na(row_reduction) & row_reduction>0) %>%
  arrange(desc(row_reduction))

raw_data %>%
  sapply(dim) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var='table') %>%
  left_join(
    raw_data1b %>%
      sapply(dim) %>%
      t() %>%
      as.data.frame() %>%
      rownames_to_column(var='table')
    ,by='table'
  ) %>%
  mutate(
    row_reduction=V1.x-V1.y
    ,row_reduction_p=round(row_reduction/V1.x*100,3)
  ) %>%
  filter(!is.na(row_reduction) & row_reduction>0) %>%
  arrange(desc(row_reduction))
```

```{r Find unique identifiers in CHR_ICD, eval=FALSE, include=FALSE}
raw_data1a %>%
  .[str_detect(names(.),'^v_chr_icd')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^CHR_NO|^FEE_NO|^HOSPIN_DATE|^HIA_DATE')]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  group_by_all() %>%
  summarize(n=n(),.groups='drop') %>%
  arrange(desc(n))
```

```{r Extract tables of diagnosis updates, include=FALSE}
diag_upd=
  raw_data1b %>%
  .[str_detect(names(.),'^v_chr_icd')] %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  select_at(
    c('HOSP','CHR_NO','FEE_NO','HOSPIN_DATE','HIA_DATE'
      ,select_at(.,colnames(.) %>% .[str_detect(.,'CODE')]) %>%
        sapply(\(x)any(str_detect(x,'[:alpha:]') & str_detect(x,'\\.'))) %>%
        .[.] %>%
        names()
      )
  ) %>%
  left_join(
    raw_data1b %>%
      .[str_detect(names(.),'^v_chr_diag')] %>%
      lapply(
        X=names(.)
        ,Y=.
        ,\(X,Y)
        Y[[X]] %>%
          mutate(
            HOSP=
              str_sub(X,str_count(X),str_count(X))
          )
      ) %>%
      do.call(rbind,.) %>%
      select_at(
        c('HOSP','CHR_NO','HIA_DATE'
          ,colnames(.)[str_detect(
            colnames(.)
            ,colnames(.) %>%
              .[str_detect(.,'_ORD')] %>%
              str_remove_all('_ORD')
          )]
        )
      )
    ,by=c('HOSP','CHR_NO','HIA_DATE')
  ) %>%
  select(HOSP,CHR_NO,FEE_NO,HOSPIN_DATE,SDIAG_ORD,SDIAG_CODE) %>%
  arrange(HOSPIN_DATE,SDIAG_ORD) %>%
  mutate(HOSPIN_TIME='0000') %>%
  mutate(HOSPIN_DATE=as.numeric(HOSPIN_DATE)+(2023-112)*10000) %>%
  mutate(
    HOSPIN_DATE=
      paste0(
        str_sub(HOSPIN_DATE,1,4)
        ,'-'
        ,str_sub(HOSPIN_DATE,5,6)
        ,'-'
        ,str_sub(HOSPIN_DATE,7,8)
      )
  ) %>%
  mutate(
    HOSPIN_TIME=
      paste0(
        str_sub(HOSPIN_TIME,1,2)
        ,':'
        ,str_sub(HOSPIN_TIME,3,4)
      )
  ) %>%
  unite(HOSPIN,HOSPIN_DATE,HOSPIN_TIME,sep=' ') %>%
  mutate(
    HOSPIN=
      ifelse(
        str_count(HOSPIN)==16
        & str_count(HOSPIN,'-')==2
        & str_count(HOSPIN,' ')==1
        & str_count(HOSPIN,'\\:')==1
        ,HOSPIN
        ,NA
      )
  ) %>%
  mutate(HOSPIN=ymd_hm(HOSPIN))
```

```{r Extract tables of discharge diagnosis, include=FALSE}
diag_discharge=
  raw_data1b %>%
  .[str_detect(names(.),'^v_ipd_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^CHR_NO|^FEE_NO|^MDIAG|^SDIAG')
            | (str_detect(.,'^ICD') & str_detect(.,'OUT$'))
            ]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
        ,TYPE=
          str_sub(X,3,5)
      )
  ) %>%
  do.call(rbind,.) %>%
  select(HOSP,everything()) %>%
  mutate_all(as.character) %>%
  gather(KEY,CODE,-HOSP,-CHR_NO,-TYPE,-FEE_NO)
```

```{r Find an example in multiple diagnosis updates, include=FALSE}
seq_example2=
  raw_data1b %>%
  .[str_detect(names(.),'^v_chr_icd')] %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  filter(
    paste0(HOSP,'_',CHR_NO,'_',FEE_NO)
    %in%paste0(
      uri_cath_d$prediction$HOSP
      ,'_'
      ,uri_cath_d$prediction$CHR_NO
      ,'_'
      ,uri_cath_d$prediction$FEE_NO
    )
  ) %>%
  group_by(HOSP,CHR_NO,FEE_NO) %>%
  summarize(n=n(),.groups='drop') %>%
  arrange(desc(n)) %>%
  slice(1)

seq_example2=
  diag_upd %>%
  filter(
    paste0(HOSP,'_',CHR_NO,'_',FEE_NO)
    %in%paste0(
      seq_example2$HOSP
      ,'_'
      ,seq_example2$CHR_NO
      ,'_'
      ,seq_example2$FEE_NO
    )
  )

seq_example2=
  uri_cath_d$prediction %>%
  filter(
    paste0(HOSP,'_',CHR_NO,'_',FEE_NO)
    %in%paste0(
      seq_example2$HOSP
      ,'_'
      ,seq_example2$CHR_NO
      ,'_'
      ,seq_example2$FEE_NO
    )
  ) %>%
  lapply(X=seq(nrow(.)),Y=.,Z=seq_example2,\(X,Y,Z){
    K=Y %>%
      slice(X)
    
    K %>%
      left_join(
        Z %>%
          filter(HOSPIN>=K$START & HOSPIN<=K$pred_day)
        ,by=c('HOSP','CHR_NO','FEE_NO')
      )
  }) %>%
  do.call(rbind,.)
```

```{r An example of multiple diagnosis updates, eval=FALSE, include=FALSE}
seq_example2 %>%
  mutate(ID='1. Prediction interval') %>%
  ggplot(aes(ID,START+duration/2,color=paste0(START,DC))) +
  geom_linerange(aes(ymin=START,ymax=DC),size=0.5,alpha=0.75,show.legend=F) +
  geom_point(size=1.5,alpha=0.75,show.legend=F) +
  geom_point(
    data=
      seq_example2 %>%
      mutate(ID='2. Diagnoses')
    ,aes(ID,HOSPIN)
    ,show.legend=F
    ,na.rm=T
  ) +
  facet_wrap(~SDIAG_CODE) +
  coord_flip() +
  scale_x_discrete('') +
  scale_y_datetime(
    ''
    ,date_breaks='1 month'
    ,date_labels='%Y-%m'
    ,date_minor_breaks='1 day'
  ) +
  theme(
    axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)
  )
```

```{r Create diagnosis identifier, include=FALSE}
if(all(c(1,2,3)%in%comp_req)){
  diag_identifier=
    uri_cath_d$prediction %>%
    left_join(
      group_by(.,HOSP,CHR_NO,TYPE,FEE_NO) %>%
        mutate(latest_pred_day=max(pred_day)) %>%
        ungroup() %>%
        left_join(
          diag_upd
          ,by=c('HOSP','CHR_NO','FEE_NO')
        ) %>%
        filter(HOSPIN>pred_day & HOSPIN<=latest_pred_day)
      ,by=colnames(uri_cath_d$prediction)
    ) %>%
    left_join(
      diag_discharge
      ,by=c('HOSP','CHR_NO','TYPE','FEE_NO')
    ) %>%
    mutate(
      ALL_CODE=
        ifelse(
          is.na(SDIAG_CODE) | SDIAG_CODE==''
          ,ifelse(CODE=='',NA,CODE)
          ,SDIAG_CODE
        )
    )
  
  saveRDS(diag_identifier,'data/diag_identifier.rds')
}else{
  diag_identifier=readRDS('data/diag_identifier.rds')
}
```

```{r Create UTI identifier, include=FALSE}
if(all(c(1,2,3)%in%comp_req)){
  uti_identifier=
    diag_identifier %>%
    group_by_at(colnames(uri_cath_d$prediction)) %>%
    summarize(
      all_UTI_na=
        all(is.na(ALL_CODE))
      ,UTI=
        any(str_sub(ALL_CODE,1,3)%in%c('N39','599'))
      ,.groups='drop'
    ) %>%
    mutate(UTI=ifelse(all_UTI_na,NA,UTI)) %>%
    select(-all_UTI_na)
  
  saveRDS(uti_identifier,'data/uti_identifier.rds')
}else{
  uti_identifier=readRDS('data/uti_identifier.rds')
}
```

```{r UTI prev. selection 1 by discharge diagnosis, eval=FALSE, include=FALSE}
raw_data1a %>%
  .[str_detect(names(.),'^v_ipd_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^CHR_NO|^FEE_NO|^MDIAG|^SDIAG')
            | (str_detect(.,'^ICD') & str_detect(.,'OUT$'))
            ]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
        ,TYPE=
          str_sub(X,3,5)
      )
  ) %>%
  do.call(rbind,.) %>%
  gather(KEY,CODE,-HOSP,-CHR_NO,-FEE_NO) %>%
  group_by(HOSP,CHR_NO,FEE_NO) %>%
  summarize(UTI=any(str_sub(CODE,1,3)%in%c('N39','599')),.groups='drop') %>%
  right_join(
    uri_cath_d3$prediction %>%
      group_by(HOSP,CHR_NO,TYPE,FEE_NO) %>%
      filter(START==max(START)) %>%
      ungroup()
    ,by=c('HOSP','CHR_NO','FEE_NO')
  ) %>%
  filter(HOSP=='t') %>%
  group_by(HOSP,UTI) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()

raw_data1a %>%
  .[str_detect(names(.),'^v_ipd_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^CHR_NO|^FEE_NO|^MDIAG|^SDIAG')
            | (str_detect(.,'^ICD') & str_detect(.,'OUT$'))
            ]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
        ,TYPE=
          str_sub(X,3,5)
      )
  ) %>%
  do.call(rbind,.) %>%
  gather(KEY,CODE,-HOSP,-CHR_NO,-FEE_NO) %>%
  group_by(HOSP,CHR_NO,FEE_NO) %>%
  summarize(UTI=any(str_sub(CODE,1,3)%in%c('N39','599')),.groups='drop') %>%
  right_join(
    uri_cath_d3$prediction
    ,by=c('HOSP','CHR_NO','FEE_NO')
  ) %>%
  mutate(HOSP=ifelse(HOSP%in%c('s','w'),'sw',HOSP)) %>%
  filter(HOSP=='sw') %>%
  group_by(HOSP,UTI) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r UTI prev. selection 1 by dis. & upd. diagnosis, eval=FALSE, include=FALSE}
uti_identifier %>%
  filter(duration>2) %>%
  filter(HOSP=='t') %>%
  group_by(HOSP,UTI) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()

uti_identifier %>%
  filter(duration>2) %>%
  mutate(HOSP=ifelse(HOSP%in%c('s','w'),'sw',HOSP)) %>%
  filter(HOSP=='sw') %>%
  group_by(HOSP,UTI) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r UTI prev. selection 2 by discharge diagnosis, eval=FALSE, include=FALSE}
raw_data1b %>%
  .[str_detect(names(.),'^v_ipd_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^CHR_NO|^FEE_NO|^MDIAG|^SDIAG')
            | (str_detect(.,'^ICD') & str_detect(.,'OUT$'))
            ]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
        ,TYPE=
          str_sub(X,3,5)
      )
  ) %>%
  do.call(rbind,.) %>%
  gather(KEY,CODE,-HOSP,-CHR_NO,-FEE_NO) %>%
  group_by(HOSP,CHR_NO,FEE_NO) %>%
  summarize(UTI=any(str_sub(CODE,1,3)%in%c('N39','599')),.groups='drop') %>%
  right_join(
    uri_cath_d$prediction %>%
      group_by(HOSP,CHR_NO,TYPE,FEE_NO) %>%
      filter(START==max(START)) %>%
      ungroup()
    ,by=c('HOSP','CHR_NO','FEE_NO')
  ) %>%
  mutate(HOSP=ifelse(HOSP%in%c('s','t'),'st',HOSP)) %>%
  filter(HOSP=='st') %>%
  group_by(HOSP,UTI) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()

raw_data1b %>%
  .[str_detect(names(.),'^v_ipd_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^CHR_NO|^FEE_NO|^MDIAG|^SDIAG')
            | (str_detect(.,'^ICD') & str_detect(.,'OUT$'))
            ]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
        ,TYPE=
          str_sub(X,3,5)
      )
  ) %>%
  do.call(rbind,.) %>%
  gather(KEY,CODE,-HOSP,-CHR_NO,-FEE_NO) %>%
  group_by(HOSP,CHR_NO,FEE_NO) %>%
  summarize(UTI=any(str_sub(CODE,1,3)%in%c('N39','599')),.groups='drop') %>%
  right_join(
    uri_cath_d$prediction
    ,by=c('HOSP','CHR_NO','FEE_NO')
  ) %>%
  filter(HOSP=='w') %>%
  group_by(HOSP,UTI) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r UTI prev. selection 2 by dis. & upd. diagnosis, eval=FALSE, include=FALSE}
uti_identifier %>%
  mutate(HOSP=ifelse(HOSP%in%c('s','t'),'st',HOSP)) %>%
  filter(HOSP=='st') %>%
  group_by(HOSP,UTI) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()

uti_identifier %>%
  filter(HOSP=='w') %>%
  group_by(HOSP,UTI) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r TTE analysis of UTI by dis. & upd diagnosis, eval=FALSE, include=FALSE}
uti_identifier %>%
  filter(duration>2) %>%
  group_by_at(colnames(uri_cath_d3$prediction) %>% .[.!='pred_day']) %>%
  arrange_at(colnames(uri_cath_d3$prediction)) %>%
  mutate(pred_day=seq(n())+2) %>%
  ungroup() %>%
  mutate(UTI=ifelse(is.na(UTI),F,UTI)) %>%
  group_by(HOSP,pred_day) %>%
  summarize(
    `log(n)`=log(n())
    ,p=mean(UTI)
    ,.groups='drop'
  ) %>%
  gather(key,value,-HOSP,-pred_day) %>%
  ggplot(aes(pred_day,value)) +
  geom_col() +
  facet_grid(key~HOSP,scales='free',space='free_x') +
  scale_x_continuous(breaks=seq(1,100,1))

uti_identifier %>%
  group_by_at(colnames(uri_cath_d$prediction) %>% .[.!='pred_day']) %>%
  arrange_at(colnames(uri_cath_d$prediction)) %>%
  mutate(pred_day=seq(n())) %>%
  ungroup() %>%
  mutate(UTI=ifelse(is.na(UTI),F,UTI)) %>%
  group_by(HOSP,pred_day) %>%
  summarize(
    `log(n)`=log(n())
    ,p=mean(UTI)
    ,.groups='drop'
  ) %>%
  gather(key,value,-HOSP,-pred_day) %>%
  ggplot(aes(pred_day,value)) +
  geom_col() +
  facet_grid(key~HOSP,scales='free',space='free_x') +
  scale_x_continuous(breaks=seq(1,100,1))
```

```{r Check FEE_CODE for ordering urine culture, eval=FALSE, include=FALSE}
raw_data %>%
  .[str_detect(names(.),'^v_fee_basic')] %>%
  lapply(select,FEE_CODE,FEE_DESC) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  filter(FEE_CODE=='F13008B')
```

```{r Find table connection for urine culture order, eval=FALSE, include=FALSE}
raw_data1b$v_opd_exper_s %>%
  filter(
    FEE_NO
    %in%pull(
      raw_data1b$v_ipd_fee_s %>%
        filter(FEE_CODE=='F13008B')
      ,FEE_NO
    )
  ) %>%
  select(
    CHR_NO,FEE_NO
    ,SEQ_NO,OPD_DATE,CODE_NO,ITEM_NO,LAB_NO
  )

raw_data1b$v_opd_exper_t %>%
  filter(
    FEE_NO
    %in%pull(
      raw_data1b$v_ipd_fee_t %>%
        filter(FEE_CODE=='F13008B')
      ,FEE_NO
    )
  ) %>%
  select(
    CHR_NO,FEE_NO
    ,SEQ_NO,OPD_DATE,CODE_NO,ITEM_NO,LAB_NO
  )

raw_data$v_exper_order_w %>%
  filter(
    FEE_NO
    %in%pull(
      raw_data1b$v_ipd_fee_w %>%
        filter(FEE_CODE=='F13008B')
      ,FEE_NO
    )
  ) %>%
  select(
    CHR_NO,FEE_NO
    ,FEE_CODE,GROUP_CODE,ITEM_NO1,LAB_NO,SOUR_FLAG,EXPER_CLASS,EXPER_TYPE
  )
```


```{r Extract tables of diagnosis updates, include=FALSE}
uricult_upd=
  raw_data1b %>%
  .[str_detect(names(.),'^v_opd_exper|^v_exper_order')] %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y){
    Z=Y[[X]] %>%
      left_join(
        raw_data1b[[paste0(
            'v_ipd_fee_'
            ,str_sub(X,str_count(X),str_count(X))
          )]] %>%
          filter(FEE_CODE=='F13008B') %>%
          select(FEE_NO,FEE_CODE,START_DATE,START_TIME) %>%
          rename(URICULT=FEE_CODE)
        ,by='FEE_NO'
      ) %>%
      filter(!(is.na(START_DATE) & is.na(START_TIME)))
    
    if(str_detect(X,'_s$|_t$')){
      Z=Z %>%
        select(
          CHR_NO,FEE_NO
          ,URICULT,START_DATE,START_TIME
          # ,SEQ_NO,OPD_DATE,CODE_NO,ITEM_NO,LAB_NO
        )
    }else{
      Z=Z %>%
        select(
          CHR_NO,FEE_NO
          ,URICULT,START_DATE,START_TIME
          # ,FEE_CODE,GROUP_CODE,ITEM_NO1,LAB_NO,SOUR_FLAG,EXPER_CLASS,EXPER_TYPE
        )
    }
    
    Z %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  }) %>%
  do.call(rbind,.) %>%
  select(HOSP,everything()) %>%
  mutate(
    START_TIME=
      ifelse(
        !is.na(START_DATE) & is.na(START_TIME)
        ,'0000'
        ,START_TIME
      )
  ) %>%
  mutate(START_DATE=as.numeric(START_DATE)+(2023-112)*10000) %>%
  mutate(
    START_DATE=
      paste0(
        str_sub(START_DATE,1,4)
        ,'-'
        ,str_sub(START_DATE,5,6)
        ,'-'
        ,str_sub(START_DATE,7,8)
      )
  ) %>%
  mutate(
    START_TIME=
      paste0(
        str_sub(START_TIME,1,2)
        ,':'
        ,str_sub(START_TIME,3,4)
      )
  ) %>%
  unite(START,START_DATE,START_TIME,sep=' ') %>%
  mutate(
    START=
      ifelse(
        str_count(START)==16
        & str_count(START,'-')==2
        & str_count(START,' ')==1
        & str_count(START,'\\:')==1
        ,START
        ,NA
      )
  ) %>%
  mutate(START=ymd_hm(START))
```

```{r Create urine culture identifier, include=FALSE}
if(all(c(1,2,3)%in%comp_req)){
  uricult_identifier=
    uri_cath_d$prediction %>%
    left_join(
      group_by(.,HOSP,CHR_NO,TYPE,FEE_NO) %>%
        mutate(latest_pred_day=max(pred_day)) %>%
        ungroup() %>%
        left_join(
          uricult_upd %>%
            rename(START_URICULT=START)
          ,by=c('HOSP','CHR_NO','FEE_NO')
        ) %>%
        filter(START_URICULT>pred_day & START_URICULT<=latest_pred_day) %>%
        select(-START_URICULT)
      ,by=colnames(uri_cath_d$prediction)
    ) %>%
    mutate(URICULT=!is.na(URICULT)) %>%
    group_by_at(colnames(uri_cath_d$prediction)) %>%
    summarize(URICULT=any(URICULT),.groups='drop')
  
  saveRDS(uricult_identifier,'data/uricult_identifier.rds')
}else{
  uricult_identifier=readRDS('data/uricult_identifier.rds')
}
```

```{r UTI prev. selection 1 by diag. & urine culture, eval=FALSE, include=FALSE}
uti_identifier %>%
  filter(duration>2) %>%
  left_join(
    uricult_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(outcome=ifelse(UTI==T | URICULT==T,T,F)) %>%
  filter(HOSP=='t') %>%
  group_by(HOSP,outcome) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()

uti_identifier %>%
  filter(duration>2) %>%
  left_join(
    uricult_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(outcome=ifelse(UTI==T | URICULT==T,T,F)) %>%
  mutate(HOSP=ifelse(HOSP%in%c('s','w'),'sw',HOSP)) %>%
  filter(HOSP=='sw') %>%
  group_by(HOSP,outcome) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r UTI prev. selection 2 by diag. & urine culture, eval=FALSE, include=FALSE}
uti_identifier %>%
  left_join(
    uricult_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(outcome=ifelse(UTI==T | URICULT==T,T,F)) %>%
  mutate(HOSP=ifelse(HOSP%in%c('s','t'),'st',HOSP)) %>%
  filter(HOSP=='st') %>%
  group_by(HOSP,outcome) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()

uti_identifier %>%
  left_join(
    uricult_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(outcome=ifelse(UTI==T | URICULT==T,T,F)) %>%
  filter(HOSP=='w') %>%
  group_by(HOSP,outcome) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Create pneumonia identifier, include=FALSE}
if(all(c(1,2,3)%in%comp_req)){
  pneu_identifier=
    diag_identifier %>%
    group_by_at(colnames(uri_cath_d$prediction)) %>%
    summarize(
      all_PNEU_na=
        all(is.na(ALL_CODE))
      ,PNEU=
        any(str_sub(ALL_CODE,1,3)%in%c(paste0('J',12:18),440:448))
      ,.groups='drop'
    ) %>%
    mutate(PNEU=ifelse(all_PNEU_na,NA,PNEU)) %>%
    select(-all_PNEU_na)
  
  saveRDS(pneu_identifier,'data/pneu_identifier.rds')
}else{
  pneu_identifier=readRDS('data/pneu_identifier.rds')
}
```

```{r UTI prev. selection 1 by UTI-urine culture-PNEU, eval=FALSE, include=FALSE}
uti_identifier %>%
  filter(duration>2) %>%
  left_join(
    uricult_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    pneu_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(outcome=ifelse((UTI==T | URICULT==T) & PNEU==F,T,F)) %>%
  filter(HOSP=='t') %>%
  group_by(HOSP,outcome) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()

uti_identifier %>%
  filter(duration>2) %>%
  left_join(
    uricult_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    pneu_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(outcome=ifelse((UTI==T | URICULT==T) & PNEU==F,T,F)) %>%
  mutate(HOSP=ifelse(HOSP%in%c('s','w'),'sw',HOSP)) %>%
  filter(HOSP=='sw') %>%
  group_by(HOSP,outcome) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r UTI prev. selection 2 by UTI-urine culture-PNEU, eval=FALSE, include=FALSE}
uti_identifier %>%
  left_join(
    uricult_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    pneu_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(outcome=ifelse((UTI==T | URICULT==T) & PNEU==F,T,F)) %>%
  mutate(HOSP=ifelse(HOSP%in%c('s','t'),'st',HOSP)) %>%
  filter(HOSP=='st') %>%
  group_by(HOSP,outcome) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()

uti_identifier %>%
  left_join(
    uricult_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    pneu_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(outcome=ifelse((UTI==T | URICULT==T) & PNEU==F,T,F)) %>%
  filter(HOSP=='w') %>%
  group_by(HOSP,outcome) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Ensure UTI/urine culture/PNEU have + & -, eval=FALSE, include=FALSE}
uti_identifier %>%
  group_by(HOSP,UTI) %>%
  summarize(n=n(),.groups='drop')

uricult_identifier %>%
  group_by(HOSP,URICULT) %>%
  summarize(n=n(),.groups='drop')

pneu_identifier %>%
  group_by(HOSP,PNEU) %>%
  summarize(n=n(),.groups='drop')
```

```{r Create outcome identifier, include=FALSE}
outcome_identifier=
  uti_identifier %>%
  left_join(
    uricult_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    pneu_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(outcome=ifelse((UTI==T | URICULT==T) & PNEU==F,T,F))
```

```{r Extract tables of birthdate for computing age, include=FALSE}
age_birthdate=
  raw_data1b %>%
  .[str_detect(names(.),'^v_chr_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^CHR_NO|^BIRTH_DATE')]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  mutate(BIRTH_TIME='0000') %>%
  mutate(BIRTH_DATE=as.numeric(BIRTH_DATE)+(2023-112)*10000) %>%
  mutate(
    BIRTH_DATE=
      paste0(
        str_sub(BIRTH_DATE,1,4)
        ,'-'
        ,str_sub(BIRTH_DATE,5,6)
        ,'-'
        ,str_sub(BIRTH_DATE,7,8)
      )
  ) %>%
  mutate(
    BIRTH_TIME=
      paste0(
        str_sub(BIRTH_TIME,1,2)
        ,':'
        ,str_sub(BIRTH_TIME,3,4)
      )
  ) %>%
  unite(BIRTH,BIRTH_DATE,BIRTH_TIME,sep=' ') %>%
  mutate(
    BIRTH=
      ifelse(
        str_count(BIRTH)==16
        & str_count(BIRTH,'-')==2
        & str_count(BIRTH,' ')==1
        & str_count(BIRTH,'\\:')==1
        ,BIRTH
        ,NA
      )
  ) %>%
  mutate(BIRTH=ymd_hm(BIRTH))
```

```{r Create age identifier, include=FALSE}
age_identifier=
  uri_cath_d$prediction %>%
  left_join(
    age_birthdate
    ,by=c('HOSP','CHR_NO')
  ) %>%
  mutate(AGE=as.duration(pred_day-BIRTH)/dyears(1)) %>%
  mutate(pred_day2=as_datetime(ifelse(AGE>200,pred_day-years(200),pred_day))) %>%
  mutate(AGE=as.duration(pred_day2-BIRTH)/dyears(1)) %>%
  select(-BIRTH,-pred_day2)
```

```{r Check age missingness and outliers, eval=FALSE, include=FALSE}
age_identifier %>%
  group_by(HOSP) %>%
  mutate(
    min=min(AGE,na.rm=T)
    ,q1=quantile(AGE,0.25,na.rm=T)
    ,q2=quantile(AGE,0.5,na.rm=T)
    ,q3=quantile(AGE,0.75,na.rm=T)
    ,max=max(AGE,na.rm=T)
    ,n=n()
    ,missing=sum(is.na(AGE))
  ) %>%
  ungroup() %>%
  mutate(
    outlier=
      AGE<(q1-1.5*(q3-q1))
      | AGE>(q3+1.5*(q3-q1))
  ) %>%
  group_by(HOSP,min,q1,q2,q3,max,n,missing) %>%
  summarize(outliers=sum(outlier,na.rm=T),.groups='drop')
```

```{r Create age group identifier, include=FALSE}
age_group_identifier=
  age_identifier %>%
  mutate(
    AGE=
      case_when(
        AGE<=50~'<=50'
        ,AGE>50 & AGE<=65~'>50 to 65'
        ,AGE>65~'>65'
      ) %>%
      factor(c('<=50','>50 to 65','>65'))
  ) %>%
  rename(AGE_GROUP=AGE)
```

```{r Check age group distribution, eval=FALSE, include=FALSE}
age_group_identifier %>%
  group_by(HOSP,AGE_GROUP) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Check BED_KIND for ICU, eval=FALSE, include=FALSE}
raw_data1b %>%
  .[str_detect(names(.),'^v_bed_basic')] %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.)  %>%
  filter(
    paste0(HOSP,BED_KIND)
    %in%pull(
      filter(.,str_detect(str_to_lower(BED_DESC),'加護病')) %>%
        unite(HOSP_BED_KIND,HOSP,BED_KIND,sep='')
      ,HOSP_BED_KIND
    )
  ) %>%
  mutate(
    BED_DESC=
      BED_DESC %>%
      str_replace_all('[:digit:]+','[num]')
  ) %>%
  group_by(HOSP,BED_DESC,BED_KIND) %>%
  summarize(n=n(),.groups='drop') %>%
  spread(BED_KIND,n,fill=0)
```

```{r Extract tables of ICU stay updates, include=FALSE}
icu_upd=
  raw_data1b %>%
  .[str_detect(names(.),'^v_ipd_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(
            .
            ,c('^CHR_NO'
               ,'^FEE_NO'
               ,'^BED_NO'
               ,'^IPD_DATE$'
               ,'^IPD_TIME$'
               ,'^CPD_DATE$'
               ,'^CPD_TIME$'
               ) %>%
              paste0(collapse='|')
          )]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  left_join(
    raw_data1b %>%
      .[str_detect(names(.),'^v_bed_basic')] %>%
      lapply(\(x)
        x %>%
          select_at(
            colnames(.) %>%
              .[str_detect(.,'^BED_NO|^BED_KIND|^BED_DESC')]
          )
      ) %>%
      lapply(
        X=names(.)
        ,Y=.
        ,\(X,Y)
        Y[[X]] %>%
          mutate(
            HOSP=
              str_sub(X,str_count(X),str_count(X))
          )
      ) %>%
      do.call(rbind,.)  %>%
      filter(
        paste0(HOSP,BED_KIND)
        %in%pull(
          filter(.,str_detect(str_to_lower(BED_DESC),'加護病')) %>%
            unite(HOSP_BED_KIND,HOSP,BED_KIND,sep='')
          ,HOSP_BED_KIND
        )
      ) %>%
      mutate(BED_DESC='加護病') %>%
      select(HOSP,BED_NO,BED_DESC) %>%
      filter(!duplicated(.))
    ,by=c('HOSP','BED_NO')
  ) %>%
  filter(!is.na(BED_DESC)) %>%
  lapply(X=1,Y=.,\(X,Y){
    Z=raw_data1b %>%
      .[str_detect(names(.),'^v_ipd_trans')] %>%
      lapply(\(x)
        x %>%
          select_at(
            colnames(.) %>%
              .[str_detect(.,'^CHR_NO|^FEE_NO|BED_NO$|^TRANS_DATE|^TRANS_TIME')]
          )
      ) %>%
      lapply(
        X=names(.)
        ,Y=.
        ,\(X,Y)
        Y[[X]] %>%
          mutate(
            HOSP=
              str_sub(X,str_count(X),str_count(X))
          )
      ) %>%
      do.call(rbind,.)
    
    Y %>%
      left_join(
        Z %>%
          rename(BED_NO=NEW_BED_NO) %>%
          `colnames<-`(
            colnames(.) %>%
              str_replace_all('TRANS','BED_ADM')
          ) %>%
          select(-ORI_BED_NO)
        ,by=c('HOSP','CHR_NO','FEE_NO','BED_NO')
      ) %>%
      mutate(
        BED_ADM_DATE=
          ifelse(
            is.na(BED_ADM_DATE)
            ,IPD_DATE
            ,BED_ADM_DATE
          )
        ,BED_ADM_TIME=
          ifelse(
            is.na(BED_ADM_TIME)
            ,IPD_TIME
            ,BED_ADM_TIME
          )
      ) %>%
      left_join(
        Z %>%
          rename(BED_NO=ORI_BED_NO) %>%
          `colnames<-`(
            colnames(.) %>%
              str_replace_all('TRANS','BED_DIS')
          ) %>%
          select(-NEW_BED_NO)
        ,by=c('HOSP','CHR_NO','FEE_NO','BED_NO')
      ) %>%
      mutate(
        BED_DIS_DATE=
          ifelse(
            is.na(BED_DIS_DATE)
            ,CPD_DATE
            ,BED_DIS_DATE
          )
        ,BED_DIS_TIME=
          ifelse(
            is.na(BED_DIS_TIME)
            ,CPD_TIME
            ,BED_DIS_TIME
          )
      ) %>%
      filter(!duplicated(.))
  }) %>%
  .[[1]] %>%
  mutate(
    IPD_TIME=
      ifelse(
        !is.na(IPD_DATE) & is.na(IPD_TIME)
        ,'0000'
        ,IPD_TIME
      )
    ,BED_ADM_TIME=
      ifelse(
        !is.na(BED_ADM_DATE) & is.na(BED_ADM_TIME)
        ,'0000'
        ,BED_ADM_TIME
      )
    ,BED_DIS_TIME=
      ifelse(
        !is.na(BED_DIS_DATE) & is.na(BED_DIS_TIME)
        ,'0000'
        ,BED_DIS_TIME
      )
    ,CPD_TIME=
      ifelse(
        !is.na(CPD_DATE) & is.na(CPD_TIME)
        ,'0000'
        ,CPD_TIME
      )
  ) %>%
  mutate_at(
    c('IPD_DATE','BED_ADM_DATE','BED_DIS_DATE','CPD_DATE')
    ,\(x)
    as.numeric(x)+(2023-112)*10000
  ) %>%
  mutate_at(
    c('IPD_DATE','BED_ADM_DATE','BED_DIS_DATE','CPD_DATE')
    ,\(x)
    paste0(
      str_sub(x,1,4)
      ,'-'
      ,str_sub(x,5,6)
      ,'-'
      ,str_sub(x,7,8)
    )
  ) %>%
  mutate_at(
    c('IPD_TIME','BED_ADM_TIME','BED_DIS_TIME','CPD_TIME')
    ,\(x)
    paste0(
      str_sub(x,1,2)
      ,':'
      ,str_sub(x,3,4)
    )
  ) %>%
  unite(IPD,IPD_DATE,IPD_TIME,sep=' ') %>%
  unite(BED_ADM,BED_ADM_DATE,BED_ADM_TIME,sep=' ') %>%
  unite(BED_DIS,BED_DIS_DATE,BED_DIS_TIME,sep=' ') %>%
  unite(CPD,CPD_DATE,CPD_TIME,sep=' ') %>%
  mutate_at(
    c('IPD','BED_ADM','BED_DIS','CPD')
    ,\(x)
    ifelse(
      str_count(x)==16
      & str_count(x,'-')==2
      & str_count(x,' ')==1
      & str_count(x,'\\:')==1
      ,x
      ,NA
    )
  ) %>%
  mutate_at(c('IPD','BED_ADM','BED_DIS','CPD'),ymd_hm) %>%
  lapply(
    X=seq(nrow(.))
    ,Y=.
    ,\(X,Y){
      Z=Y %>%
        slice(X)
      if(!is.na(Z$BED_DIS) & Z$BED_DIS<Z$BED_ADM){
        K=Z %>%
          mutate(
            BED_ADM=BED_DIS
            ,BED_DIS=as_date(NA)
          ) %>%
          rbind(
            Z %>%
              mutate(
                BED_DIS=CPD
              )
          )
      }else{
        K=Z
      }
      K %>%
        filter(BED_ADM<=BED_DIS)
    }
  ) %>%
  do.call(rbind,.) %>%
  select(-IPD,-CPD) %>%
  mutate(merged=1)

icu_upd_nrow=
  icu_upd %>%
  nrow()

iter=0

while(iter<1){
  cat('iter',iter,'nrow',icu_upd_nrow,'\n')

  icu_upd=
    icu_upd %>%
    group_by(HOSP,CHR_NO,FEE_NO) %>%
    mutate(seq=seq(n())) %>%
    ungroup() %>%
    left_join(
      select(.,HOSP,CHR_NO,FEE_NO,seq,BED_DIS) %>%
        mutate(seq=seq+1) %>%
        rename(prev_BED_DIS=BED_DIS)
      ,by=c('HOSP','CHR_NO','FEE_NO','seq')
    ) %>%
    mutate(dist=as.duration(BED_ADM-prev_BED_DIS)/ddays(1)) %>%
    mutate(dist=ifelse(is.na(dist),0,dist)) %>%
    group_by(HOSP,CHR_NO,FEE_NO) %>%
    mutate(unmerged=dist>1) %>%
    mutate(seq2=cumsum(unmerged)+1) %>%
    ungroup() %>%
    select(-seq,-prev_BED_DIS,-dist,-unmerged) %>%
    rename(seq=seq2) %>%
    group_by(HOSP,CHR_NO,FEE_NO,seq) %>%
    mutate(
      BED_NO=paste0(sort(unique(BED_NO)),collapse=' & ')
      ,BED_ADM=min(BED_ADM)
      ,BED_DIS=max(BED_DIS)
      ,merged=sum(merged)
    ) %>%
    slice(1) %>%
    ungroup() %>%
    select(-seq)

  if(icu_upd_nrow>nrow(icu_upd)){
    iter=0
  }else{
    iter=iter+1
  }

  icu_upd_nrow=
    icu_upd %>%
    nrow()
}

rm(iter,icu_upd_nrow)
```

```{r Create ICU stay identifier, include=FALSE}
if(all(c(1,2,3)%in%comp_req)){
  icu_identifier=
    uri_cath_d$prediction %>%
    left_join(
      icu_upd %>%
        select(-merged)
      ,by=c('HOSP','CHR_NO','FEE_NO')
    ) %>%
    filter(BED_ADM<=pred_day) %>%
    mutate(
      ICU_STAY=
        ifelse(
          is.na(BED_DESC)
          ,0
          ,ifelse(
            BED_ADM>pred_day
            ,0
            ,ifelse(
              is.na(BED_DIS)
              ,NA
              ,ifelse(
                BED_DIS>=pred_day
                ,as.duration(pred_day-BED_ADM)/ddays(1)
                ,as.duration(BED_DIS-BED_ADM)/ddays(1)
              )
            )
          )
        )
    ) %>%
    group_by_at(colnames(uri_cath_d$prediction)) %>%
    summarize(
      ICU_STAY_D=sum(ICU_STAY,na.rm=T)
      ,ICU_STAY_N=sum(!is.na(BED_DESC))
      ,.groups='drop'
    )
  
  saveRDS(icu_identifier,'data/icu_identifier.rds')
}else{
  icu_identifier=readRDS('data/icu_identifier.rds')
}

icu_identifier=
  uri_cath_d$prediction %>%
  left_join(
    icu_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate_at(c('ICU_STAY_D','ICU_STAY_N'),\(x)ifelse(is.na(x),0,x))
```

```{r Check ICU stay missingness and outliers, eval=FALSE, include=FALSE}
icu_identifier %>%
  group_by(HOSP) %>%
  mutate(
    min=min(ICU_STAY_D,na.rm=T)
    ,q1=quantile(ICU_STAY_D,0.25,na.rm=T)
    ,q2=quantile(ICU_STAY_D,0.5,na.rm=T)
    ,q3=quantile(ICU_STAY_D,0.75,na.rm=T)
    ,max=max(ICU_STAY_D,na.rm=T)
    ,n=n()
    ,missing=sum(is.na(ICU_STAY_D))
  ) %>%
  ungroup() %>%
  mutate(
    outlier=
      ICU_STAY_D<(q1-1.5*(q3-q1))
      | ICU_STAY_D>(q3+1.5*(q3-q1))
  ) %>%
  group_by(HOSP,ICU_STAY_N,min,q1,q2,q3,max,n,missing) %>%
  summarize(outliers=sum(outlier,na.rm=T),.groups='drop')
```


```{r Create ICU-stay 10+ day identifier, include=FALSE}
icu_10d_identifier=
  icu_identifier %>%
  mutate(ICU_STAY_10D=ICU_STAY_D>=10) %>%
  select(-ICU_STAY_D,-ICU_STAY_N)
```

```{r Check ICU-stay 10+ day distribution, eval=FALSE, include=FALSE}
icu_10d_identifier %>%
  group_by(HOSP,ICU_STAY_10D) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Create catheter duration identifier, include=FALSE}
cath_d_identifier=
  uri_cath_d$prediction %>%
  mutate(
    CATH_D=as.duration(pred_day-START)/ddays(1)
    ,CATH_D=ifelse(CATH_D>=duration,duration,CATH_D)
  )
```

```{r Check catheter duration missingness and outliers, eval=FALSE, include=FALSE}
cath_d_identifier %>%
  group_by(HOSP) %>%
  mutate(
    min=min(CATH_D,na.rm=T)
    ,q1=quantile(CATH_D,0.25,na.rm=T)
    ,q2=quantile(CATH_D,0.5,na.rm=T)
    ,q3=quantile(CATH_D,0.75,na.rm=T)
    ,max=max(CATH_D,na.rm=T)
    ,n=n()
    ,missing=sum(is.na(CATH_D))
  ) %>%
  ungroup() %>%
  mutate(
    outlier=
      CATH_D<(q1-1.5*(q3-q1))
      | CATH_D>(q3+1.5*(q3-q1))
  ) %>%
  group_by(HOSP,min,q1,q2,q3,max,n,missing) %>%
  summarize(outliers=sum(outlier,na.rm=T),.groups='drop')
```

```{r Create catheter duration 6+ day identifier, include=FALSE}
cath_d_6d_identifier=
  cath_d_identifier %>%
  mutate(CATH_D=CATH_D>=6) %>%
  rename(CATH_D_6D=CATH_D)
```

```{r Check catheter duration 6+ day distribution, eval=FALSE, include=FALSE}
cath_d_6d_identifier %>%
  group_by(HOSP,CATH_D_6D) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Extract tables of hospital stay updates, include=FALSE}
los_upd=
  raw_data1b %>%
  .[str_detect(names(.),'^v_ipd_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(
            .
            ,c('^CHR_NO'
               ,'^FEE_NO'
               ,'^IPD_DATE$'
               ,'^IPD_TIME$'
               ,'^CPD_DATE$'
               ,'^CPD_TIME$'
               ) %>%
              paste0(collapse='|')
          )]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  mutate(
    IPD_TIME=
      ifelse(
        !is.na(IPD_DATE) & is.na(IPD_TIME)
        ,'0000'
        ,IPD_TIME
      )
    ,CPD_TIME=
      ifelse(
        !is.na(CPD_DATE) & is.na(CPD_TIME)
        ,'0000'
        ,IPD_TIME
      )
  ) %>%
  mutate_at(
    c('IPD_DATE','CPD_DATE')
    ,\(x)as.numeric(x)+(2023-112)*10000
  ) %>%
  mutate_at(
    c('IPD_DATE','CPD_DATE')
    ,\(x)
      paste0(
        str_sub(x,1,4)
        ,'-'
        ,str_sub(x,5,6)
        ,'-'
        ,str_sub(x,7,8)
      )
  ) %>%
  mutate_at(
    c('IPD_TIME','CPD_TIME')
    ,\(x)
      paste0(
        str_sub(x,1,2)
        ,':'
        ,str_sub(x,3,4)
      )
  ) %>%
  unite(IPD,IPD_DATE,IPD_TIME,sep=' ') %>%
  unite(CPD,CPD_DATE,CPD_TIME,sep=' ') %>%
  mutate_at(
    c('IPD','CPD')
    ,\(x)
      ifelse(
        str_count(x)==16
        & str_count(x,'-')==2
        & str_count(x,' ')==1
        & str_count(x,'\\:')==1
        ,x
        ,NA
      )
  ) %>%
  mutate_at(c('IPD','CPD'),ymd_hm) %>%
  select(HOSP,everything())
```

```{r Create hospital stay identifier, include=FALSE}
los_identifier=
  uri_cath_d$prediction %>%
  left_join(los_upd,by=c('HOSP','CHR_NO','FEE_NO')) %>%
  mutate(LOS=as.duration(pred_day-IPD)/ddays(1)) %>%
  mutate(
    IPD=as_datetime(ifelse(LOS>3500,IPD+years(200),IPD))
    ,IPD=as_datetime(ifelse(IPD>=START,START,IPD))
  ) %>%
  mutate(LOS=as.duration(pred_day-IPD)/ddays(1)) %>%
  select(-IPD,-CPD)
```

```{r Check ICU stay missingness and outliers, eval=FALSE, include=FALSE}
los_identifier %>%
  group_by(HOSP) %>%
  mutate(
    min=min(LOS,na.rm=T)
    ,q1=quantile(LOS,0.25,na.rm=T)
    ,q2=quantile(LOS,0.5,na.rm=T)
    ,q3=quantile(LOS,0.75,na.rm=T)
    ,max=max(LOS,na.rm=T)
    ,n=n()
    ,missing=sum(is.na(LOS))
  ) %>%
  ungroup() %>%
  mutate(
    outlier=
      LOS<(q1-1.5*(q3-q1))
      | LOS>(q3+1.5*(q3-q1))
  ) %>%
  group_by(HOSP,min,q1,q2,q3,max,n,missing) %>%
  summarize(outliers=sum(outlier,na.rm=T),.groups='drop')
```

```{r Create hospital stay 4+ day identifier, include=FALSE}
los_4d_identifier=
  los_identifier %>%
  mutate(LOS=LOS>=4) %>%
  rename(LOS_4D=LOS)
```

```{r Check hospital stay 4+ day distribution, eval=FALSE, include=FALSE}
los_4d_identifier %>%
  group_by(HOSP,LOS_4D) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Create prev. cath. identifier, include=FALSE}
if(all(c(1,2,3)%in%comp_req)){ # 25m 50s
  cl=detectCores()-2
  start=T; source('R/parallel_computing-codes.R')
  
  prev_cath_identifier=
    uri_cath_d$prediction %>%
    cbind(
      uri_cath_d$prediction %>%
        pbsapply(
          cl=cl
          ,X=seq(nrow(.))
          ,Y=.
          ,\(X,Y){
            Y %>%
              filter(HOSP==Y$HOSP[X] & CHR_NO==Y$CHR_NO[X] & DC<Y$START[X]) %>%
              nrow()
        }) %>%
        data.frame(CATH_PREV=.)
    )
  
  saveRDS(prev_cath_identifier,'data/prev_cath_identifier.rds')
  start=F; source('R/parallel_computing-codes.R')
}else{
  prev_cath_identifier=readRDS('data/prev_cath_identifier.rds')
}
```

```{r Check prev.cath. missingness and outliers, eval=FALSE, include=FALSE}
prev_cath_identifier %>%
  group_by(HOSP) %>%
  mutate(
    min=min(CATH_PREV,na.rm=T)
    ,q1=quantile(CATH_PREV,0.25,na.rm=T)
    ,q2=quantile(CATH_PREV,0.5,na.rm=T)
    ,q3=quantile(CATH_PREV,0.75,na.rm=T)
    ,max=max(CATH_PREV,na.rm=T)
    ,n=n()
    ,missing=sum(is.na(CATH_PREV))
  ) %>%
  ungroup() %>%
  mutate(
    outlier=
      CATH_PREV<(q1-1.5*(q3-q1))
      | CATH_PREV>(q3+1.5*(q3-q1))
  ) %>%
  group_by(HOSP,min,q1,q2,q3,max,n,missing) %>%
  summarize(outliers=sum(outlier,na.rm=T),.groups='drop')
```

```{r Create sex identifier, include=FALSE}
sex_identifier=
  uri_cath_d$prediction %>%
  left_join(
    raw_data1b %>%
      .[str_detect(names(.),'^v_chr_basic')] %>%
      lapply(\(x)
        x %>%
          select_at(
            colnames(.) %>%
              .[str_detect(.,'^CHR_NO|^SEX')]
          )
      ) %>%
      lapply(
        X=names(.)
        ,Y=.
        ,\(X,Y)
        Y[[X]] %>%
          mutate(
            HOSP=
              str_sub(X,str_count(X),str_count(X))
          )
      ) %>%
      do.call(rbind,.) %>%
      mutate(
        SEX_TYPE=
          ifelse(SEX_TYPE==1,'M','F') %>%
          factor(c('F','M'))
      )
    ,by=c('HOSP','CHR_NO')
  )
```

```{r Check sex distribution, eval=FALSE, include=FALSE}
sex_identifier %>%
  group_by(HOSP,SEX_TYPE) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Extract tables of ICD descriptors, include=FALSE}
icd_basic=
  raw_data %>%
  .[str_detect(names(.),'^v_icd')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^ICD[:digit:]|_SIMP_DESC$')]
      ) %>%
      mutate(
        ICD_TYPE=
          colnames(.) %>%
          .[str_detect(.,'^ICD[:digit:]')] %>%
          .[1] %>%
          str_remove_all('_CODE')
      ) %>%
      `colnames<-`(
        colnames(.) %>%
          str_remove_all('[:digit:]')
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  mutate_all(as.character) %>%
  mutate(n=1) %>%
  spread(HOSP,n,fill=0) %>%
  select(ICD_TYPE,ICD_CODE,ENG_SIMP_DESC,everything()) %>%
  arrange(ICD_TYPE,ICD_CODE)
```

```{r Extract tables of previous DM diagnosis updates, include=FALSE}
prev_DM_upd=
  uri_cath_d$prediction %>%
  left_join(
    diag_upd %>%
      select(-FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(HOSPIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(SDIAG_CODE))
    ,SDIAG_CODE=
      any(str_sub(SDIAG_CODE,1,3)%in%c('E11','250'))
    ,.groups='drop'
  ) %>%
  mutate(SDIAG_CODE=ifelse(all_na,NA,SDIAG_CODE)) %>%
  select(-all_na)
```

```{r Extract tables of previous discharged DM diagnosis, include=FALSE}
prev_DM_discharge=
  uri_cath_d$prediction %>%
  left_join(
     diag_discharge %>%
      left_join(
        los_upd
        ,by=c('HOSP','CHR_NO','FEE_NO')
      ) %>%
      select(-TYPE,-FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(CPD<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CODE))
    ,CODE=
      any(str_sub(CODE,1,3)%in%c('E11','250'))
    ,.groups='drop'
  ) %>%
  mutate(CODE=ifelse(all_na,NA,CODE)) %>%
  select(-all_na)
```

```{r Create previous DM diagnosis identifier, include=FALSE}
prev_DMdiag_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_DM_upd
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    prev_DM_discharge
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  gather(
    CRITERIA_TYPE,CRITERIA_VALUE
    ,-HOSP,-CHR_NO,-TYPE,-FEE_NO
    ,-FEE_DATE,-FEE_TIME,-FEE_CODE,-SEQ_NO,-SEQ_NO2
    ,-START,-DC,-duration,-merged,-pred_day
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CRITERIA_VALUE))
    ,prev_DMdiag=
      sum(CRITERIA_VALUE,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(prev_DMdiag=ifelse(all_na,NA,prev_DMdiag)) %>%
  select(-all_na)
```

```{r Check previous DM diagnosis distribution, eval=FALSE, include=FALSE}
prev_DMdiag_identifier %>%
  group_by(HOSP,prev_DMdiag) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Identify MED_CODE for anti-diabetic drugs, eval=FALSE, include=FALSE}
raw_data1b %>%
  .[str_detect(names(.),'^v_med_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^MED_|DESC')]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  mutate(
    ANTIDIAB=
      ALISE_DESC %>%
      str_to_lower() %>%
      str_replace_all('/',' ') %>%
      str_remove_all('[:digit:]|[:punct:]|庫|針頭')
  ) %>%
  select(HOSP,MED_CODE,MED_TYPE,ANTIDIAB,everything()) %>%
  lapply(X=1,Y=.,\(X,Y){
    Z=Y %>%
      filter(
        str_detect(
          str_to_lower(MED_CODE)
          ,filter(.,str_detect(str_to_lower(MED_TYPE),'^0908')) %>%
            pull(MED_CODE) %>%
            str_to_lower() %>%
            unique() %>%
            paste0(collapse='|')
        )
      )
    
    print(
      Z %>%
        filter(ANTIDIAB%in%c(''))
    )
    
    print(
      Z %>%
        group_by(HOSP,MED_TYPE,ANTIDIAB,MED_CODE) %>%
        summarize(n=n(),.groups='drop') %>%
        group_by(HOSP,MED_TYPE,ANTIDIAB) %>%
        summarize(
          MED_CODES=paste0(MED_CODE,collapse='|')
          ,n=sum(n)
          ,.groups='drop'
        ) %>%
        spread(HOSP,n,fill=0) %>%
        arrange(MED_TYPE,MED_CODES,w,t,s)
    )
    
    Y
  }) %>%
  .[[1]] %>%
  filter(str_detect(str_to_lower(MED_TYPE),'^0908')) %>%
  group_by(HOSP,MED_TYPE,ANTIDIAB,MED_CODE) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP,MED_TYPE,ANTIDIAB) %>%
  summarize(
    MED_CODES=paste0(MED_CODE,collapse='|')
    ,n=sum(n)
    ,.groups='drop'
  ) %>%
  spread(HOSP,n,fill=0) %>%
  arrange(MED_TYPE,MED_CODES,w,t,s)
```

```{r Extract tables of medication orders, include=FALSE}
med_order=
  raw_data1b %>%
  .[str_detect(names(.),'^v_ud_order')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^FEE_NO|^UD_SEQ|^MED_CODE|^BEGIN_')]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  left_join(
    raw_data1b %>%
      .[str_detect(names(.),'^v_med_basic')] %>%
      lapply(\(x)
        x %>%
          select_at(
            colnames(.) %>%
              .[str_detect(.,'^MED_CODE|^MED_TYPE|^UNIT_DESC')]
          )
      ) %>%
      lapply(
        X=names(.)
        ,Y=.
        ,\(X,Y)
        Y[[X]] %>%
          mutate(
            HOSP=
              str_sub(X,str_count(X),str_count(X))
          )
      ) %>%
      do.call(rbind,.)
    ,by=c('HOSP','MED_CODE')
  ) %>%
  select(HOSP,FEE_NO,everything()) %>%
  mutate(
    BEGIN_TIME=
      ifelse(
        !is.na(BEGIN_DATE) & is.na(BEGIN_TIME)
        ,'0000'
        ,BEGIN_TIME
      )
  ) %>%
  mutate(BEGIN_DATE=as.numeric(BEGIN_DATE)+(2023-112)*10000) %>%
  mutate(
    BEGIN_DATE=
      paste0(
        str_sub(BEGIN_DATE,1,4)
        ,'-'
        ,str_sub(BEGIN_DATE,5,6)
        ,'-'
        ,str_sub(BEGIN_DATE,7,8)
      )
  ) %>%
  mutate(
    BEGIN_TIME=
      paste0(
        str_sub(BEGIN_TIME,1,2)
        ,':'
        ,str_sub(BEGIN_TIME,3,4)
      )
  ) %>%
  unite(BEGIN,BEGIN_DATE,BEGIN_TIME,sep=' ') %>%
  mutate(
    BEGIN=
      ifelse(
        str_count(BEGIN)==16
        & str_count(BEGIN,'-')==2
        & str_count(BEGIN,' ')==1
        & str_count(BEGIN,'\\:')==1
        ,BEGIN
        ,NA
      )
  ) %>%
  mutate(BEGIN=ymd_hm(BEGIN))
```

```{r Extract tables of previous DM medication orders, include=FALSE}
prev_DM_med=
  uri_cath_d$prediction %>%
  left_join(
    med_order %>%
      select(-UD_SEQ,-UD_SEQ_OLD,-MED_CODE)
    ,by=c('HOSP','FEE_NO')
  ) %>%
  filter(BEGIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(MED_TYPE))
    ,MED_TYPE=
      any(str_detect(str_to_lower(MED_TYPE),'^0908'))
    ,.groups='drop'
  ) %>%
  mutate(MED_TYPE=ifelse(all_na,NA,MED_TYPE)) %>%
  select(-all_na)
```

```{r Create previous DM medication identifier, include=FALSE}
prev_DMmed_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_DM_med
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  gather(
    CRITERIA_TYPE,CRITERIA_VALUE
    ,-HOSP,-CHR_NO,-TYPE,-FEE_NO
    ,-FEE_DATE,-FEE_TIME,-FEE_CODE,-SEQ_NO,-SEQ_NO2
    ,-START,-DC,-duration,-merged,-pred_day
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CRITERIA_VALUE))
    ,prev_DMmed=
      sum(CRITERIA_VALUE,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(prev_DMmed=ifelse(all_na,NA,prev_DMmed)) %>%
  select(-all_na)
```

```{r Check previous DM medication distribution, eval=FALSE, include=FALSE}
prev_DMmed_identifier %>%
  group_by(HOSP,prev_DMmed) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Create previous DM diagnosis/medication identifier, include=FALSE}
prev_DM_identifier=
  prev_DMdiag_identifier %>%
  left_join(
    prev_DMmed_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(prev_DM=(prev_DMdiag+prev_DMmed)>0) %>%
  select(-prev_DMdiag,-prev_DMmed)
```

```{r Check previous DM diag./med. distribution, eval=FALSE, include=FALSE}
prev_DM_identifier %>%
  group_by(HOSP,prev_DM) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Determine FEE_CODE for immobilization, include=FALSE}
immob=
  raw_data %>%
  .[str_detect(names(.),'^v_fee_basic')] %>%
  lapply(select,FEE_CODE,FEE_DESC) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  filter(
    str_detect(
      str_to_lower(FEE_CODE)
      ,filter(.,str_detect(str_to_lower(FEE_DESC),'保護性約束')) %>%
        pull(FEE_CODE) %>%
        str_sub(1,str_count(.)-1) %>%
        str_to_lower() %>%
        unique() %>%
        paste0(collapse='|')
    )
  ) %>%
  mutate(exist='yes') %>%
  spread(HOSP,exist,fill='no') %>%
  arrange(FEE_CODE,w,t,s) %>%
  filter(str_detect(str_to_lower(FEE_CODE),'f47093b'))

immob %>%
  knitr::kable()
```

```{r Extract tables of immob. orders, include=FALSE}
immob_order=
  raw_data1b %>%
  .[str_detect(names(.),'^v_ipd_fee')] %>%
  lapply(filter,FEE_CODE%in%immob$FEE_CODE) %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(
            .
            ,paste0(
              c(
                '^CHR_NO'
                ,'^FEE_NO'
                ,'^FEE_DATE'
                ,'^FEE_TIME'
                ,'^FEE_CODE'
                ,'^SEQ_NO'
                ,'^START'
                ,'^DC'
              )
              ,collapse='|'
            )
          )]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
        ,TYPE=
          str_sub(X,3,5)
      )
  ) %>%
  do.call(rbind,.) %>%
  select_at(c(
    intersect(colnames(uri_cath_d$prediction),colnames(.))
    ,setdiff(colnames(.),colnames(uri_cath_d$prediction))
  )) %>%
  mutate(
    START_TIME=
      ifelse(
        !is.na(START_DATE) & is.na(START_TIME)
        ,'0000'
        ,START_TIME
      )
    ,DC_TIME=
      ifelse(
        !is.na(DC_DATE) & is.na(DC_TIME)
        ,'0000'
        ,DC_TIME
      )
  ) %>%
  mutate_at(
    c('START_DATE','DC_DATE')
    ,\(x)
    as.numeric(x)+(2023-112)*10000
  ) %>%
  mutate_at(
    c('START_DATE','DC_DATE')
    ,\(x)
    paste0(
      str_sub(x,1,4)
      ,'-'
      ,str_sub(x,5,6)
      ,'-'
      ,str_sub(x,7,8)
    )
  ) %>%
  mutate_at(
    c('START_TIME','DC_TIME')
    ,\(x)
    paste0(
      str_sub(x,1,2)
      ,':'
      ,str_sub(x,3,4)
    )
  ) %>%
  unite(START,START_DATE,START_TIME,sep=' ') %>%
  unite(DC,DC_DATE,DC_TIME,sep=' ') %>%
  mutate_at(
    c('START','DC')
    ,\(x)
    ifelse(
      str_count(x)==16
      & str_count(x,'-')==2
      & str_count(x,' ')==1
      & str_count(x,'\\:')==1
      ,x
      ,NA
    )
  ) %>%
  mutate_at(c('START','DC'),ymd_hm) %>%
  arrange(HOSP,CHR_NO,TYPE,FEE_NO,START,DC) %>%
  select(HOSP,CHR_NO,FEE_CODE,START,DC) %>%
  rename(
    IMMOB_FEE_CODE=FEE_CODE
    ,IMMOB_START=START
    ,IMMOB_DC=DC
  )
```

```{r Create immob. identifier, include=FALSE}
immob_identifier=
  uri_cath_d$prediction %>%
  left_join(
    left_join(
        .
        ,immob_order
        ,by=c('HOSP','CHR_NO')
      ) %>%
      filter(IMMOB_START<pred_day) %>%
      select(-IMMOB_START,-IMMOB_DC)
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(IMMOB_FEE_CODE=!is.na(IMMOB_FEE_CODE)) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    immob=
      any(IMMOB_FEE_CODE)
    ,.groups='drop'
  )
```

```{r Check immob. distribution, eval=FALSE, include=FALSE}
immob_identifier %>%
  group_by(HOSP,immob) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Extract tables of dept. descriptors, include=FALSE}
dept_basic=
  raw_data1b %>%
  .[str_detect(names(.),'^v_ipd_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(
            .
            ,paste0(
              c(
                '^CHR_NO'
                ,'^FEE_NO'
                ,'^GEN_DEPT_CODE'
              )
              ,collapse='|'
            )
          )]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
        ,TYPE=
          str_sub(X,3,5)
      )
  ) %>%
  do.call(rbind,.) %>%
  group_by(HOSP,GEN_DEPT_CODE) %>%
  summarize(n=n(),.groups='drop') %>%
  rename(DEPT_CODE=GEN_DEPT_CODE) %>%
  left_join(
    raw_data %>%
      .[str_detect(names(.),'^v_dept_basic')] %>%
      lapply(\(x)
        x %>%
          select_at(
            colnames(.) %>%
              .[str_detect(
                .
                ,paste0(
                  c(
                    '^DEPT_CODE'
                    ,'_DESC$'
                  )
                  ,collapse='|'
                )
              )]
          )
      ) %>%
      lapply(
        X=names(.)
        ,Y=.
        ,\(X,Y)
        Y[[X]] %>%
          mutate(
            HOSP=
              str_sub(X,str_count(X),str_count(X))
          )
      ) %>%
      do.call(rbind,.)
    ,by=c('HOSP','DEPT_CODE')
  ) %>%
  filter(!duplicated(.))
```

```{r Extract tables of op./surgery, include=FALSE}
indication_op=
  raw_data1b %>%
  .[str_detect(names(.),'^v_op_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(
            .
            ,paste0(
              c(
                '^CHR_NO'
                ,'^FEE_NO'
                ,'^IN_'
                ,'^OUT_'
              )
              ,collapse='|'
            )
          )]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  select(HOSP,CHR_NO,FEE_NO,everything()) %>%
  mutate_at(
    c('IN_DATE','OUT_DATE')
    ,\(x)
    ifelse(x=='',NA,x)
  ) %>%
  mutate(
    IN_TIME=
      ifelse(
        !is.na(IN_DATE) & is.na(IN_TIME)
        ,'0000'
        ,IN_TIME
      )
    ,OUT_TIME=
      ifelse(
        !is.na(OUT_DATE) & is.na(OUT_TIME)
        ,'0000'
        ,OUT_TIME
      )
  ) %>%
  mutate_at(
    c('IN_DATE','OUT_DATE')
    ,\(x)
    as.numeric(x)+(2023-112)*10000
  ) %>%
  mutate_at(
    c('IN_DATE','OUT_DATE')
    ,\(x)
    paste0(
      str_sub(x,1,4)
      ,'-'
      ,str_sub(x,5,6)
      ,'-'
      ,str_sub(x,7,8)
    )
  ) %>%
  mutate_at(
    c('IN_TIME','OUT_TIME')
    ,\(x)
    paste0(
      str_sub(x,1,2)
      ,':'
      ,str_sub(x,3,4)
    )
  ) %>%
  unite(IN,IN_DATE,IN_TIME,sep=' ') %>%
  unite(OUT,OUT_DATE,OUT_TIME,sep=' ') %>%
  mutate_at(
    c('IN','OUT')
    ,\(x)
    ifelse(
      str_count(x)==16
      & str_count(x,'-')==2
      & str_count(x,' ')==1
      & str_count(x,'\\:')==1
      ,x
      ,NA
    )
  ) %>%
  mutate_at(c('IN','OUT'),ymd_hm)
```

```{r Create indication identifier, include=FALSE}
indication_identifier=
  uri_cath_d$prediction %>%
  left_join(
    left_join(
        .
        ,indication_op
        ,by=c('HOSP','CHR_NO','FEE_NO')
      ) %>%
      filter(is.na(IN) | (IN>=START & IN<pred_day)) %>%
      mutate(
        op=1
        ,int_d=as.duration(IN-START)/ddays(1)
        ,missing=is.na(int_d)
      ) %>%
      select(-IN,-OUT)
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  arrange(int_d) %>%
  slice(1) %>%
  summarize(
    missing=
      sum(missing,na.rm=T)>0
    ,indication=
      sum(op,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(
    indication=ifelse(missing,NA,indication)
    ,indication=
      ifelse(indication,'Surgery','Medical') %>%
      factor(c('Surgery','Medical'))
  ) %>%
  select(-missing)
```

```{r Check indication distribution, eval=FALSE, include=FALSEs}
indication_identifier %>%
  group_by(HOSP,indication) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Extract tables of hypertension diagnosis updates, include=FALSE}
prev_HYP_upd=
  uri_cath_d$prediction %>%
  left_join(
    diag_upd %>%
      select(-FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(HOSPIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(SDIAG_CODE))
    ,SDIAG_CODE=
      any(str_sub(SDIAG_CODE,1,3)%in%paste0('I',10:15))
    ,.groups='drop'
  ) %>%
  mutate(SDIAG_CODE=ifelse(all_na,NA,SDIAG_CODE)) %>%
  select(-all_na)
```

```{r Extract tables of discharged hypertension diagnosis, include=FALSE}
prev_HYP_discharge=
  uri_cath_d$prediction %>%
  left_join(
     diag_discharge %>%
      left_join(
        los_upd
        ,by=c('HOSP','CHR_NO','FEE_NO')
      ) %>%
      select(-TYPE,-FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(CPD<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CODE))
    ,CODE=
      any(str_sub(CODE,1,3)%in%paste0('I',10:15))
    ,.groups='drop'
  ) %>%
  mutate(CODE=ifelse(all_na,NA,CODE)) %>%
  select(-all_na)
```

```{r Create hypertension identifier, include=FALSE}
prev_HYP_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_HYP_upd
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    prev_HYP_discharge
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  gather(
    CRITERIA_TYPE,CRITERIA_VALUE
    ,-HOSP,-CHR_NO,-TYPE,-FEE_NO
    ,-FEE_DATE,-FEE_TIME,-FEE_CODE,-SEQ_NO,-SEQ_NO2
    ,-START,-DC,-duration,-merged,-pred_day
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CRITERIA_VALUE))
    ,prev_HYP=
      sum(CRITERIA_VALUE,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(prev_HYP=ifelse(all_na,NA,prev_HYP)) %>%
  select(-all_na)
```

```{r Check hypertension distribution, eval=FALSE, include=FALSE}
prev_HYP_identifier %>%
  group_by(HOSP,prev_HYP) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Extract tables of previous DM insulin orders, include=FALSE}
prev_DM_insulin=
  uri_cath_d$prediction %>%
  left_join(
    med_order %>%
      select(-UD_SEQ,-UD_SEQ_OLD,-MED_CODE)
    ,by=c('HOSP','FEE_NO')
  ) %>%
  filter(BEGIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(MED_TYPE))
    ,MED_TYPE=
      any(str_detect(str_to_lower(MED_TYPE),'^090801'))
    ,.groups='drop'
  ) %>%
  mutate(MED_TYPE=ifelse(all_na,NA,MED_TYPE)) %>%
  select(-all_na)
```

```{r Create previous DM insulin identifier, include=FALSE}
prev_DMinsulin_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_DM_insulin
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  gather(
    CRITERIA_TYPE,CRITERIA_VALUE
    ,-HOSP,-CHR_NO,-TYPE,-FEE_NO
    ,-FEE_DATE,-FEE_TIME,-FEE_CODE,-SEQ_NO,-SEQ_NO2
    ,-START,-DC,-duration,-merged,-pred_day
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CRITERIA_VALUE))
    ,prev_DMinsulin=
      sum(CRITERIA_VALUE,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(prev_DMinsulin=ifelse(all_na,NA,prev_DMinsulin)) %>%
  select(-all_na)
```

```{r Check previous DM insulin distribution, eval=FALSE, include=FALSE}
prev_DMinsulin_identifier %>%
  group_by(HOSP,prev_DMinsulin) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Extract tables of BMI components from BIO_INF, include=FALSE}
bmi_bio_inf=
  raw_data %>%
  .[str_detect(names(.),'^v_bio_inf')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(
            .
            ,paste0(
              c(
                '^CHR_NO'
                ,'^FEE_NO'
                ,'EIGHT$'
                ,'_DATE$'
                ,'_TIME$'
              )
              ,collapse='|'
            )
          )]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  mutate(source='bio_inf') %>%
  mutate_at(c('HEIGHT','WEIGHT'),as.character) %>%
  gather(variable,value,-source,-HOSP,-CHR_NO,-FEE_NO,-UPD_DATE,-UPD_TIME) %>%
  mutate(
    UPD_TIME=
      ifelse(
        !is.na(UPD_DATE) & is.na(UPD_TIME)
        ,'0000'
        ,UPD_TIME
      )
  ) %>%
  mutate(UPD_DATE=as.numeric(UPD_DATE)+(2023-112)*10000) %>%
  mutate(
    UPD_DATE=
      paste0(
        str_sub(UPD_DATE,1,4)
        ,'-'
        ,str_sub(UPD_DATE,5,6)
        ,'-'
        ,str_sub(UPD_DATE,7,8)
      )
  ) %>%
  mutate(
    UPD_TIME=
      paste0(
        str_sub(UPD_TIME,1,2)
        ,':'
        ,str_sub(UPD_TIME,3,4)
      )
  ) %>%
  unite(UPD,UPD_DATE,UPD_TIME,sep=' ') %>%
  mutate(
    UPD=
      ifelse(
        str_count(UPD)==16
        & str_count(UPD,'-')==2
        & str_count(UPD,' ')==1
        & str_count(UPD,'\\:')==1
        ,UPD
        ,NA
      )
  ) %>%
  mutate(UPD=ymd_hm(UPD)) %>%
  rename(CREATE=UPD) %>%
  left_join(
    c('',''
      ,'-',''
      ,'.',''
      ,'..',''
      ,'//',''
      ,'155+','155'
      ,'160+','160'
      ,'164,0','164'
      ,'NA',''
      ,'np',''
      ,'VD',''
      ,'53.5.','53.5'
      ,'53.5.0','53.5'
      ,'55+','55'
      ,'60+','60'
      ,'72.0.','72'
      ,'不知',''
      ) %>%
      matrix(ncol=2,byrow=T,dimnames=list(NULL,c('value','value2'))) %>%
      as.data.frame()
    ,by='value'
  ) %>%
  mutate(value=ifelse(is.na(value2),value,value2)) %>%
  select(-value2) %>%
  mutate(value=ifelse(value=='',NA,value)) %>%
  mutate(value=as.numeric(value)) %>%
  filter(!is.na(value)) %>%
  filter(value>0) %>%
  select(HOSP,everything())
```

```{r Extract tables of BMI components from NIS_TPR, include=FALSE}
bmi_nis_tpr=
  raw_data %>%
  .[str_detect(names(.),'^v_nis_tpr')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(
            .
            ,paste0(
              c(
                '^FEE_NO'
                ,'^ITEM_NO'
                ,'^POSITION'
                ,'^RECORD'
                ,'^CREATE'
              )
              ,collapse='|'
            )
          )]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  filter(ITEM_NO%in%c('bh','bw')) %>%
  left_join(
    raw_data %>%
      .[str_detect(names(.),'^v_ipd_basic')] %>%
      lapply(\(x)
        x %>%
          select_at(
            colnames(.) %>%
              .[str_detect(
                .
                ,paste0(
                  c(
                    '^CHR_NO'
                    ,'^FEE_NO'
                  )
                  ,collapse='|'
                )
              )]
          )
      ) %>%
      lapply(
        X=names(.)
        ,Y=.
        ,\(X,Y)
        Y[[X]] %>%
          mutate(
            HOSP=
              str_sub(X,str_count(X),str_count(X))
          )
      ) %>%
      do.call(rbind,.)
    ,by=c('HOSP','FEE_NO')
  ) %>%
  mutate(source='nis_tpr') %>%
  mutate_at(c('CREATE_DATE','CREATE_TIME'),as.character) %>%
  mutate(
    CREATE_TIME=
      ifelse(
        !is.na(CREATE_DATE) & is.na(CREATE_TIME)
        ,'00:00:00'
        ,CREATE_TIME
      )
  ) %>%
  separate(CREATE_TIME,c('H','M','S'),sep='\\:') %>%
  select(-S) %>%
  unite(CREATE_TIME,H,M,sep=':') %>%
  unite(CREATE,CREATE_DATE,CREATE_TIME,sep=' ') %>%
  mutate(
    CREATE=
      ifelse(
        str_count(CREATE)==16
        & str_count(CREATE,'-')==2
        & str_count(CREATE,' ')==1
        & str_count(CREATE,'\\:')==1
        ,CREATE
        ,NA
      )
  ) %>%
  mutate(CREATE=ymd_hm(CREATE)) %>%
  select(-POSITION) %>%
  rename(variable=ITEM_NO,value=RECORD) %>%
  mutate(
    variable=
      case_when(
        variable=='bh'~'HEIGHT'
        ,variable=='bw'~'WEIGHT'
      )
  ) %>%
  mutate(
    value=
      ifelse(
        str_detect(value,'\\|')
        ,value
        ,paste0(value,'|')
      ) %>%
      str_remove_all('\\#+')
  ) %>%
  separate(value,c('value','unit'),sep='\\|') %>%
  mutate(
    unit=
      ifelse(
        unit=='請選擇'
        ,'Kg'
        ,unit
      )
    ,unit=
      ifelse(
        variable=='WEIGHT' & unit==''
        ,'Kg'
        ,unit
      )
  ) %>%
  left_join(
    c('',''
      ,'`',''
      ,'158`','158'
      ,'164.5`','164.5'
      ,'javascript:void(0);',''
      ,'病人躁動',''
      ,'-',''
      ,'48..7',''
      ,'59..6',''
      ,'６1',''
      ,'拒',''
      ,'病人拒量',''
      ,'病人躁動',''
      ) %>%
      matrix(ncol=2,byrow=T,dimnames=list(NULL,c('value','value2'))) %>%
      as.data.frame()
    ,by='value'
  ) %>%
  mutate(value=ifelse(is.na(value2),value,value2)) %>%
  select(-value2) %>%
  mutate(value=ifelse(value=='',NA,value)) %>%
  mutate(value=as.numeric(value)) %>%
  mutate(
    value=
      ifelse(
        variable=='WEIGHT' & unit=='g'
        ,value/1000
        ,value
      )
  ) %>%
  select(-unit) %>%
  filter(!is.na(value)) %>%
  filter(value>0) %>%
  select_at(colnames(bmi_bio_inf))
```

```{r Extract tables of BMI components from CHR_FIGURE, include=FALSE}
bmi_chr_figure=
  bmi_bio_inf %>%
  rbind(bmi_nis_tpr) %>%
  arrange(HOSP,CREATE)
```

```{r Create BMI identifier, include=FALSE}
bmi_identifier=
  uri_cath_d$prediction %>%
  left_join(
    left_join(
        .
        ,bmi_chr_figure %>%
          select(-FEE_NO)
        ,by=c('HOSP','CHR_NO')
      ) %>%
      filter(CREATE<pred_day) %>%
      mutate(int_d=as.duration(pred_day-CREATE)/ddays(1)) %>%
      group_by_at(c(colnames(uri_cath_d$prediction),'variable')) %>%
      arrange(int_d) %>%
      slice(1) %>%
      ungroup() %>%
      select(-source,-CREATE,-int_d) %>%
      spread(variable,value) %>%
      mutate(BMI=WEIGHT/((HEIGHT/100)^2))
    ,by=colnames(uri_cath_d$prediction)
  )
```

```{r Check BMI missingness and outliers, eval=FALSE, include=FALSE}
bmi_identifier %>%
  group_by(HOSP) %>%
  mutate(
    min=min(BMI,na.rm=T)
    ,q1=quantile(BMI,0.25,na.rm=T)
    ,q2=quantile(BMI,0.5,na.rm=T)
    ,q3=quantile(BMI,0.75,na.rm=T)
    ,max=max(BMI,na.rm=T)
    ,n=n()
    ,missing=sum(is.na(BMI))
  ) %>%
  ungroup() %>%
  mutate(
    outlier=
      BMI<(q1-1.5*(q3-q1))
      | BMI>(q3+1.5*(q3-q1))
  ) %>%
  group_by(HOSP,min,q1,q2,q3,max,n,missing) %>%
  summarize(outliers=sum(outlier,na.rm=T),.groups='drop')
```

```{r Create BMI >30 identifier, include=FALSE}
bmi_gt30_identifier=
  bmi_identifier %>%
  mutate(BMI=BMI>30) %>%
  rename(BMI_GT30=BMI) %>%
  select(-HEIGHT,-WEIGHT)
```

```{r Check BMI >30 distribution, eval=FALSE, include=FALSE}
bmi_gt30_identifier %>%
  group_by(HOSP,BMI_GT30) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Extract tables of previous DM nephropathy updates, include=FALSE}
prev_DMneph_upd=
  uri_cath_d$prediction %>%
  left_join(
    diag_upd %>%
      select(-FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(HOSPIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(SDIAG_CODE))
    ,SDIAG_CODE=
      any(SDIAG_CODE%in%c('E11.21'))
    ,.groups='drop'
  ) %>%
  mutate(SDIAG_CODE=ifelse(all_na,NA,SDIAG_CODE)) %>%
  select(-all_na)
```

```{r Extract tables of previous discharged DM diagnosis, include=FALSE}
prev_DMneph_discharge=
  uri_cath_d$prediction %>%
  left_join(
     diag_discharge %>%
      left_join(
        los_upd
        ,by=c('HOSP','CHR_NO','FEE_NO')
      ) %>%
      select(-TYPE,-FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(CPD<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CODE))
    ,CODE=
      any(CODE%in%c('E11.21'))
    ,.groups='drop'
  ) %>%
  mutate(CODE=ifelse(all_na,NA,CODE)) %>%
  select(-all_na)
```

```{r Create previous DM nephropathy identifier, include=FALSE}
prev_DMneph_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_DMneph_upd
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    prev_DMneph_discharge
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  gather(
    CRITERIA_TYPE,CRITERIA_VALUE
    ,-HOSP,-CHR_NO,-TYPE,-FEE_NO
    ,-FEE_DATE,-FEE_TIME,-FEE_CODE,-SEQ_NO,-SEQ_NO2
    ,-START,-DC,-duration,-merged,-pred_day
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CRITERIA_VALUE))
    ,prev_DMneph=
      sum(CRITERIA_VALUE,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(prev_DMneph=ifelse(all_na,NA,prev_DMneph)) %>%
  select(-all_na)
```

```{r Check previous DM nephropathy distribution, eval=FALSE, include=FALSE}
prev_DMneph_identifier %>%
  group_by(HOSP,prev_DMneph) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Create previous DM-related factors identifier, include=FALSE}
prev_DMrel_identifier=
  prev_DM_identifier %>%
  left_join(
    prev_HYP_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    prev_DMinsulin_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    bmi_gt30_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    prev_DMneph_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(
    prev_DMrel=
      prev_DM
      & (prev_HYP+prev_DMinsulin+BMI_GT30+prev_DMneph)>0
  ) %>%
  select(-prev_DM,-prev_HYP,-prev_DMinsulin,-BMI_GT30,-prev_DMneph)
```

```{r Check previous DM-related factors distribution, eval=FALSE, include=FALSE}
prev_DMrel_identifier %>%
  group_by(HOSP,prev_DMrel) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Determine FEE_CODE for albumin, include=FALSE}
albumin=
  raw_data %>%
  .[str_detect(names(.),'^v_fee_basic')] %>%
  lapply(select,FEE_CODE,FEE_DESC) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  filter(
    str_detect(
      str_to_lower(FEE_CODE)
      ,filter(.,str_detect(str_to_lower(FEE_DESC),'albumin')) %>%
        pull(FEE_CODE) %>%
        str_sub(1,str_count(.)-1) %>%
        str_to_lower() %>%
        unique() %>%
        paste0(collapse='|')
    )
  ) %>%
  mutate(exist='yes') %>%
  spread(HOSP,exist,fill='no') %>%
  arrange(FEE_CODE,w,t,s) %>%
  filter(str_detect(str_to_lower(FEE_CODE),'f090380|f09038c'))
```

```{r Extract tables of albumin orders and results, include=FALSE}
albumin_order=
  raw_data1b %>%
  .[str_detect(names(.),'^v_opd_exper|^v_exper_order')] %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y){
    Z=Y[[X]] %>%
      left_join(
        raw_data1b[[paste0(
            'v_ipd_fee_'
            ,str_sub(X,str_count(X),str_count(X))
          )]] %>%
          filter(FEE_CODE%in%albumin$FEE_CODE) %>%
          select(FEE_NO,FEE_CODE) %>%
          rename(ALBUMIN=FEE_CODE)
        ,by='FEE_NO'
      ) %>%
      filter(!is.na(ALBUMIN))
    
    if(str_detect(X,'_s$|_t$')){
      Z=Z %>%
        select(
          CHR_NO,FEE_NO
          ,ALBUMIN
          ,TUBE_NO,ITEM_NO
        ) %>%
        left_join(
          raw_data1b[[paste0(
              'v_labresult_'
              ,str_sub(X,str_count(X),str_count(X))
            )]] %>%
            select(
              FEE_NO,TUBE_NO,O_ITEM
              ,VALUE
              ,B_DATE,B_TIME
            ) %>%
            rename(ITEM_NO=O_ITEM) %>%
            filter(ITEM_NO%in%c('0103','11D1'))
          ,by=c('FEE_NO','TUBE_NO','ITEM_NO')
        ) %>%
        rename(TAKE_DATE=B_DATE,TAKE_TIME=B_TIME)
    }else{
      Z=Z %>%
        select(
          CHR_NO,FEE_NO
          ,ALBUMIN
          ,TUBE_NUMBER,GROUP_CODE
        ) %>%
        left_join(
          raw_data1b[[paste0(
              'v_exper_sign_'
              ,str_sub(X,str_count(X),str_count(X))
            )]] %>%
            select(
              FEE_NO,TUBE_NUMBER,GROUP_CODE
              ,EXPER_DATA2
              ,TAKE_DATE,TAKE_TIME
            ) %>%
            filter(GROUP_CODE%in%albumin$FEE_CODE)
          ,by=c('FEE_NO','TUBE_NUMBER','GROUP_CODE')
        ) %>%
        rename(TUBE_NO=TUBE_NUMBER,ITEM_NO=GROUP_CODE,VALUE=EXPER_DATA2)
    }
    
    Z %>%
      mutate(
        VALUE=
          ifelse(
            str_detect(VALUE,'\\s+')
            ,VALUE
            ,paste0(VALUE,' ')
          )
      ) %>%
      separate(VALUE,c('VALUE','UNIT'),sep='\\s+') %>%
      select(-UNIT) %>%
      mutate(
        VALUE=ifelse(str_detect(VALUE,'\\<|\\>'),NA,VALUE)
        ,VALUE=as.numeric(VALUE)
      ) %>%
      filter(!is.na(VALUE) & VALUE!='') %>%
      filter(!duplicated(.)) %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  }) %>%
  do.call(rbind,.) %>%
  mutate(
    TAKE_TIME=
      ifelse(
        !is.na(TAKE_DATE) & is.na(TAKE_TIME)
        ,'0000'
        ,TAKE_TIME
      )
  ) %>%
  mutate(TAKE_DATE=as.numeric(TAKE_DATE)+(2023-112)*10000) %>%
  mutate(
    TAKE_DATE=
      paste0(
        str_sub(TAKE_DATE,1,4)
        ,'-'
        ,str_sub(TAKE_DATE,5,6)
        ,'-'
        ,str_sub(TAKE_DATE,7,8)
      )
  ) %>%
  mutate(
    TAKE_TIME=
      paste0(
        str_sub(TAKE_TIME,1,2)
        ,':'
        ,str_sub(TAKE_TIME,3,4)
      )
  ) %>%
  unite(TAKE,TAKE_DATE,TAKE_TIME,sep=' ') %>%
  mutate(
    TAKE=
      ifelse(
        str_count(TAKE)==16
        & str_count(TAKE,'-')==2
        & str_count(TAKE,' ')==1
        & str_count(TAKE,'\\:')==1
        ,TAKE
        ,NA
      )
  ) %>%
  mutate(TAKE=ymd_hm(TAKE))
```

```{r Create albumin identifier, include=FALSE}
albumin_identifier=
  uri_cath_d$prediction %>%
  left_join(
    left_join(
        .
        ,albumin_order %>%
          select(-FEE_NO)
        ,by=c('HOSP','CHR_NO')
      ) %>%
      filter(TAKE<pred_day) %>%
      mutate(int_d=as.duration(pred_day-TAKE)/ddays(1)) %>%
      group_by_at(colnames(uri_cath_d$prediction)) %>%
      arrange(int_d) %>%
      slice(1) %>%
      ungroup() %>%
      select(-ALBUMIN,-TUBE_NO,-ITEM_NO,-TAKE,-int_d) %>%
      rename(ALBUMIN=VALUE)
    ,by=colnames(uri_cath_d$prediction)
  )
```

```{r Check albumin missingness and outliers, eval=FALSE, include=FALSE}
albumin_identifier %>%
  group_by(HOSP) %>%
  mutate(
    min=min(ALBUMIN,na.rm=T)
    ,q1=quantile(ALBUMIN,0.25,na.rm=T)
    ,q2=quantile(ALBUMIN,0.5,na.rm=T)
    ,q3=quantile(ALBUMIN,0.75,na.rm=T)
    ,max=max(ALBUMIN,na.rm=T)
    ,n=n()
    ,missing=sum(is.na(ALBUMIN))
  ) %>%
  ungroup() %>%
  mutate(
    outlier=
      ALBUMIN<(q1-1.5*(q3-q1))
      | ALBUMIN>(q3+1.5*(q3-q1))
  ) %>%
  group_by(HOSP,min,q1,q2,q3,max,n,missing) %>%
  summarize(outliers=sum(outlier,na.rm=T),.groups='drop')
```

```{r Create albumin <3.5 identifier, include=FALSE}
albumin_lt3.5_identifier=
  albumin_identifier %>%
  mutate(ALBUMIN=ALBUMIN<3.5) %>%
  rename(ALBUMIN_LT3.5=ALBUMIN)
```

```{r Check albumin <3.5 distribution, eval=FALSE, include=FALSE}
albumin_lt3.5_identifier %>%
  group_by(HOSP,ALBUMIN_LT3.5) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Determine FEE_CODE for creatinine, include=FALSE}
creatinine=
  raw_data %>%
  .[str_detect(names(.),'^v_fee_basic')] %>%
  lapply(select,FEE_CODE,FEE_DESC) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  filter(
    str_detect(
      str_to_lower(FEE_CODE)
      ,filter(.,str_detect(str_to_lower(FEE_DESC),'creatinine')) %>%
        pull(FEE_CODE) %>%
        str_sub(1,str_count(.)-1) %>%
        str_to_lower() %>%
        unique() %>%
        paste0(collapse='|')
    )
  ) %>%
  mutate(exist='yes') %>%
  spread(HOSP,exist,fill='no') %>%
  arrange(FEE_CODE,w,t,s) %>%
  filter(str_detect(str_to_lower(FEE_CODE),'f090150|f090159|f09015b|f09015c$'))
```

```{r Extract tables of albumin orders and results, include=FALSE}
creatinine_order=
  raw_data1b %>%
  .[str_detect(names(.),'^v_opd_exper|^v_exper_order')] %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y){
    Z=Y[[X]] %>%
      left_join(
        raw_data1b[[paste0(
            'v_ipd_fee_'
            ,str_sub(X,str_count(X),str_count(X))
          )]] %>%
          filter(FEE_CODE%in%creatinine$FEE_CODE) %>%
          select(FEE_NO,FEE_CODE) %>%
          rename(CREATININE_EGFR=FEE_CODE)
        ,by='FEE_NO'
      ) %>%
      filter(!is.na(CREATININE_EGFR))
    
    if(str_detect(X,'_s$|_t$')){
      Z=Z %>%
        select(
          CHR_NO,FEE_NO
          ,CREATININE_EGFR
          ,TUBE_NO,ITEM_NO
        ) %>%
        left_join(
          raw_data1b[[paste0(
              'v_labresult_'
              ,str_sub(X,str_count(X),str_count(X))
            )]] %>%
            select(
              FEE_NO,TUBE_NO,O_ITEM
              ,VALUE
              ,B_DATE,B_TIME
              ,R_ITEM
            ) %>%
            rename(ITEM_NO=O_ITEM) %>%
            filter(ITEM_NO%in%c('0108','11A2')) %>%
            filter(R_ITEM%in%c('010801','11A201','010802','11A202'))
          ,by=c('FEE_NO','TUBE_NO','ITEM_NO')
        ) %>%
        rename(TAKE_DATE=B_DATE,TAKE_TIME=B_TIME)
    }else{
      Z=Z %>%
        select(
          CHR_NO,FEE_NO
          ,CREATININE_EGFR
          ,TUBE_NUMBER,GROUP_CODE
        ) %>%
        left_join(
          raw_data1b[[paste0(
              'v_exper_sign_'
              ,str_sub(X,str_count(X),str_count(X))
            )]] %>%
            select(
              FEE_NO,TUBE_NUMBER,GROUP_CODE
              ,EXPER_DATA2
              ,TAKE_DATE,TAKE_TIME
              ,EXPER_CLASS,EXPER_TYPE,EXPER_CODE
            ) %>%
            unite(R_ITEM,EXPER_CLASS,EXPER_TYPE,EXPER_CODE,sep='|') %>%
            filter(GROUP_CODE%in%creatinine$FEE_CODE) %>%
            filter(R_ITEM%in%c('01|A|CREB','01|A|EGFR'))
          ,by=c('FEE_NO','TUBE_NUMBER','GROUP_CODE')
        ) %>%
        rename(TUBE_NO=TUBE_NUMBER,ITEM_NO=GROUP_CODE,VALUE=EXPER_DATA2)
    }
    
    Z %>%
      mutate(
        VALUE=
          ifelse(
            str_detect(VALUE,'\\s+')
            ,VALUE
            ,paste0(VALUE,' ')
          )
      ) %>%
      mutate(VALUE=str_replace_all(VALUE,'1.73 m\\^2','1.73M2')) %>%
      separate(VALUE,c('VALUE','UNIT'),sep='\\s+') %>%
      select(-UNIT) %>%
      mutate(
        VALUE=ifelse(str_detect(VALUE,'\\<|\\>|\\*|無法計算'),NA,VALUE)
        ,VALUE=as.numeric(VALUE)
      ) %>%
      filter(!is.na(VALUE) & VALUE!='') %>%
      filter(!duplicated(.)) %>%
      mutate(
        R_ITEM=
          ifelse(
            R_ITEM%in%c('010801','11A201','01|A|CREB')
            ,'CREATININE'
            ,'EGFR'
          )
      ) %>%
      spread(R_ITEM,VALUE) %>%
      filter(!is.na(CREATININE)) %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  }) %>%
  do.call(rbind,.) %>%
  mutate(
    TAKE_TIME=
      ifelse(
        !is.na(TAKE_DATE) & is.na(TAKE_TIME)
        ,'0000'
        ,TAKE_TIME
      )
  ) %>%
  mutate(TAKE_DATE=as.numeric(TAKE_DATE)+(2023-112)*10000) %>%
  mutate(
    TAKE_DATE=
      paste0(
        str_sub(TAKE_DATE,1,4)
        ,'-'
        ,str_sub(TAKE_DATE,5,6)
        ,'-'
        ,str_sub(TAKE_DATE,7,8)
      )
  ) %>%
  mutate(
    TAKE_TIME=
      paste0(
        str_sub(TAKE_TIME,1,2)
        ,':'
        ,str_sub(TAKE_TIME,3,4)
      )
  ) %>%
  unite(TAKE,TAKE_DATE,TAKE_TIME,sep=' ') %>%
  mutate(
    TAKE=
      ifelse(
        str_count(TAKE)==16
        & str_count(TAKE,'-')==2
        & str_count(TAKE,' ')==1
        & str_count(TAKE,'\\:')==1
        ,TAKE
        ,NA
      )
  ) %>%
  mutate(TAKE=ymd_hm(TAKE))
```

```{r Create creatinine identifier, include=FALSE}
creatinine_identifier=
  uri_cath_d$prediction %>%
  left_join(
    left_join(
        .
        ,creatinine_order %>%
          select(-FEE_NO)
        ,by=c('HOSP','CHR_NO')
      ) %>%
      filter(TAKE<pred_day) %>%
      mutate(int_d=as.duration(pred_day-TAKE)/ddays(1)) %>%
      group_by_at(colnames(uri_cath_d$prediction)) %>%
      arrange(int_d) %>%
      slice(1) %>%
      ungroup() %>%
      select(-CREATININE_EGFR,-TUBE_NO,-ITEM_NO,-TAKE,-int_d)
    ,by=colnames(uri_cath_d$prediction)
  )
```

```{r Check creatinine missingness and outliers, eval=FALSE, include=FALSE}
creatinine_identifier %>%
  group_by(HOSP) %>%
  mutate(
    min=min(CREATININE,na.rm=T)
    ,q1=quantile(CREATININE,0.25,na.rm=T)
    ,q2=quantile(CREATININE,0.5,na.rm=T)
    ,q3=quantile(CREATININE,0.75,na.rm=T)
    ,max=max(CREATININE,na.rm=T)
    ,n=n()
    ,missing=sum(is.na(CREATININE))
  ) %>%
  ungroup() %>%
  mutate(
    outlier=
      CREATININE<(q1-1.5*(q3-q1))
      | CREATININE>(q3+1.5*(q3-q1))
  ) %>%
  group_by(HOSP,min,q1,q2,q3,max,n,missing) %>%
  summarize(outliers=sum(outlier,na.rm=T),.groups='drop')

creatinine_identifier %>%
  group_by(HOSP) %>%
  mutate(
    min=min(EGFR,na.rm=T)
    ,q1=quantile(EGFR,0.25,na.rm=T)
    ,q2=quantile(EGFR,0.5,na.rm=T)
    ,q3=quantile(EGFR,0.75,na.rm=T)
    ,max=max(EGFR,na.rm=T)
    ,n=n()
    ,missing=sum(is.na(EGFR))
  ) %>%
  ungroup() %>%
  mutate(
    outlier=
      EGFR<(q1-1.5*(q3-q1))
      | EGFR>(q3+1.5*(q3-q1))
  ) %>%
  group_by(HOSP,min,q1,q2,q3,max,n,missing) %>%
  summarize(outliers=sum(outlier,na.rm=T),.groups='drop')
```

```{r Create creatinine <0.5 identifier, include=FALSE}
creatinine_lt0.5_identifier=
  creatinine_identifier %>%
  mutate(CREATININE=CREATININE<0.5 & EGFR>=105) %>%
  rename(CREATININE_LT0.5=CREATININE) %>%
  select(-EGFR)
```

```{r Check creatinine <0.5 distribution, eval=FALSE, include=FALSE}
creatinine_lt0.5_identifier %>%
  group_by(HOSP,CREATININE_LT0.5) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Create poor nutrition identifier, include=FALSE}
poor_nutr_identifier=
  albumin_lt3.5_identifier %>%
  left_join(
    creatinine_lt0.5_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(poor_nutr=(ALBUMIN_LT3.5+CREATININE_LT0.5)>0) %>%
  select(-ALBUMIN_LT3.5,-CREATININE_LT0.5)
```

```{r Check poor nutrition distribution, eval=FALSE, include=FALSE}
poor_nutr_identifier %>%
  group_by(HOSP,poor_nutr) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Identify MED_CODE for FI-AD drugs, eval=FALSE, include=FALSE}
raw_data1b %>%
  .[str_detect(names(.),'^v_med_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^MED_|DESC')]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  mutate(
    ANTIDIAR=
      ALISE_DESC %>%
      str_to_lower() %>%
      str_replace_all('/',' ') %>%
      str_remove_all('[:digit:]|[:punct:]|庫|針頭')
  ) %>%
  select(HOSP,MED_CODE,MED_TYPE,ANTIDIAR,everything()) %>%
  lapply(X=1,Y=.,\(X,Y){
    Z=Y %>%
      filter(
        str_detect(
          str_to_lower(MED_CODE)
          ,filter(.,str_detect(str_to_lower(MED_TYPE),'^0708')) %>%
            pull(MED_CODE) %>%
            str_to_lower() %>%
            unique() %>%
            paste0(collapse='|')
        )
      )
    
    print(
      Z %>%
        filter(ANTIDIAR%in%c(''))
    )
    
    print(
      Z %>%
        group_by(HOSP,MED_TYPE,ANTIDIAR,MED_CODE) %>%
        summarize(n=n(),.groups='drop') %>%
        group_by(HOSP,MED_TYPE,ANTIDIAR) %>%
        summarize(
          MED_CODES=paste0(MED_CODE,collapse='|')
          ,n=sum(n)
          ,.groups='drop'
        ) %>%
        spread(HOSP,n,fill=0) %>%
        arrange(MED_TYPE,MED_CODES,w,t,s)
    )
    
    Y
  }) %>%
  .[[1]] %>%
  filter(str_detect(str_to_lower(MED_TYPE),'^0708')) %>%
  group_by(HOSP,MED_TYPE,ANTIDIAR,MED_CODE) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP,MED_TYPE,ANTIDIAR) %>%
  summarize(
    MED_CODES=paste0(MED_CODE,collapse='|')
    ,n=sum(n)
    ,.groups='drop'
  ) %>%
  spread(HOSP,n,fill=0) %>%
  arrange(MED_TYPE,MED_CODES,w,t,s)
```

```{r Extract tables of FI-AD medication orders, include=FALSE}
prev_FIAD_med=
  uri_cath_d$prediction %>%
  left_join(
    med_order %>%
      select(-UD_SEQ,-UD_SEQ_OLD,-MED_CODE)
    ,by=c('HOSP','FEE_NO')
  ) %>%
  filter(BEGIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(MED_TYPE))
    ,MED_TYPE=
      any(str_detect(str_to_lower(MED_TYPE),'^0708'))
    ,.groups='drop'
  ) %>%
  mutate(MED_TYPE=ifelse(all_na,NA,MED_TYPE)) %>%
  select(-all_na)
```

```{r Create FI-AD identifier, include=FALSE}
prev_FIAD_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_FIAD_med
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(MED_TYPE))
    ,prev_FIAD=
      sum(MED_TYPE,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(prev_FIAD=ifelse(all_na,NA,prev_FIAD)) %>%
  select(-all_na)
```

```{r Check FI-AD distribution, eval=FALSE, include=FALSE}
prev_FIAD_identifier %>%
  group_by(HOSP,prev_FIAD) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Identify MED_CODE for FI-LX laxative drugs, eval=FALSE, include=FALSE}
raw_data1b %>%
  .[str_detect(names(.),'^v_med_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^MED_|DESC')]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  mutate(
    LAXATIVE=
      ALISE_DESC %>%
      str_to_lower() %>%
      str_replace_all('/',' ') %>%
      str_remove_all('[:digit:]|[:punct:]|庫|針頭')
  ) %>%
  select(HOSP,MED_CODE,MED_TYPE,LAXATIVE,everything()) %>%
  lapply(X=1,Y=.,\(X,Y){
    Z=Y %>%
      filter(
        str_detect(
          str_to_lower(MED_CODE)
          ,filter(.,str_detect(str_to_lower(MED_TYPE),'^0709')) %>%
            pull(MED_CODE) %>%
            str_to_lower() %>%
            unique() %>%
            paste0(collapse='|')
        )
      )
    
    print(
      Z %>%
        filter(LAXATIVE%in%c(''))
    )
    
    print(
      Z %>%
        group_by(HOSP,MED_TYPE,LAXATIVE,MED_CODE) %>%
        summarize(n=n(),.groups='drop') %>%
        group_by(HOSP,MED_TYPE,LAXATIVE) %>%
        summarize(
          MED_CODES=paste0(MED_CODE,collapse='|')
          ,n=sum(n)
          ,.groups='drop'
        ) %>%
        spread(HOSP,n,fill=0) %>%
        arrange(MED_TYPE,MED_CODES,w,t,s)
    )
    
    Y
  }) %>%
  .[[1]] %>%
  filter(str_detect(str_to_lower(MED_TYPE),'^0709')) %>%
  group_by(HOSP,MED_TYPE,LAXATIVE,MED_CODE) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP,MED_TYPE,LAXATIVE) %>%
  summarize(
    MED_CODES=paste0(MED_CODE,collapse='|')
    ,n=sum(n)
    ,.groups='drop'
  ) %>%
  spread(HOSP,n,fill=0) %>%
  arrange(MED_TYPE,MED_CODES,w,t,s)
```

```{r Extract tables of FI-LX medication orders, include=FALSE}
prev_FILX_med=
  uri_cath_d$prediction %>%
  left_join(
    med_order %>%
      select(-UD_SEQ,-UD_SEQ_OLD,-MED_CODE)
    ,by=c('HOSP','FEE_NO')
  ) %>%
  filter(BEGIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(MED_TYPE))
    ,MED_TYPE=
      any(str_detect(str_to_lower(MED_TYPE),'^0709'))
    ,.groups='drop'
  ) %>%
  mutate(MED_TYPE=ifelse(all_na,NA,MED_TYPE)) %>%
  select(-all_na)
```

```{r Create FI-LX identifier, include=FALSE}
prev_FILX_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_FILX_med
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(MED_TYPE))
    ,prev_FILX=
      sum(MED_TYPE,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(prev_FILX=ifelse(all_na,NA,prev_FILX)) %>%
  select(-all_na)
```

```{r Check FI-LX distribution, eval=FALSE, include=FALSE}
prev_FILX_identifier %>%
  group_by(HOSP,prev_FILX) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Create previous FI identifier, include=FALSE}
prev_FI_identifier=
  prev_FIAD_identifier %>%
  left_join(
    prev_FILX_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(prev_FI=(prev_FIAD+prev_FILX)>0) %>%
  select(-prev_FIAD,-prev_FILX)
```

```{r Check previous FI distribution, eval=FALSE, include=FALSE}
prev_FI_identifier %>%
  group_by(HOSP,prev_FI) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Identify MED_CODE for IC-CS drugs, eval=FALSE, include=FALSE}
raw_data1b %>%
  .[str_detect(names(.),'^v_med_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^MED_|DESC')]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  mutate(
    CORTICOSTEROID=
      ALISE_DESC %>%
      str_to_lower() %>%
      str_replace_all('/',' ') %>%
      str_remove_all('[:digit:]|[:punct:]|庫|針頭')
  ) %>%
  select(HOSP,MED_CODE,MED_TYPE,CORTICOSTEROID,everything()) %>%
  lapply(X=1,Y=.,\(X,Y){
    Z=Y %>%
      filter(
        str_detect(
          str_to_lower(MED_CODE)
          ,filter(.,str_detect(str_to_lower(MED_TYPE),'^0906')) %>%
            pull(MED_CODE) %>%
            str_to_lower() %>%
            unique() %>%
            paste0(collapse='|')
        )
      )
    
    print(
      Z %>%
        filter(CORTICOSTEROID%in%c(''))
    )
    
    print(
      Z %>%
        group_by(HOSP,MED_TYPE,CORTICOSTEROID,MED_CODE) %>%
        summarize(n=n(),.groups='drop') %>%
        group_by(HOSP,MED_TYPE,CORTICOSTEROID) %>%
        summarize(
          MED_CODES=paste0(MED_CODE,collapse='|')
          ,n=sum(n)
          ,.groups='drop'
        ) %>%
        spread(HOSP,n,fill=0) %>%
        arrange(MED_TYPE,MED_CODES,w,t,s)
    )
    
    Y
  }) %>%
  .[[1]] %>%
  filter(
    str_detect(str_to_lower(MED_TYPE),'^0906')
    & str_to_lower(UNIT_DESC)%in%c('amp','cap','ml','tab','vial')
  ) %>%
  group_by(HOSP,MED_TYPE,CORTICOSTEROID,MED_CODE) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP,MED_TYPE,CORTICOSTEROID) %>%
  summarize(
    MED_CODES=paste0(MED_CODE,collapse='|')
    ,n=sum(n)
    ,.groups='drop'
  ) %>%
  spread(HOSP,n,fill=0) %>%
  arrange(MED_TYPE,MED_CODES,w,t,s)
```

```{r Extract tables of IC-CS medication orders, include=FALSE}
prev_ICCS_med=
  uri_cath_d$prediction %>%
  left_join(
    med_order %>%
      select(-UD_SEQ,-UD_SEQ_OLD,-MED_CODE)
    ,by=c('HOSP','FEE_NO')
  ) %>%
  filter(BEGIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(MED_TYPE))
    ,MED_TYPE=
      any(
        str_detect(str_to_lower(MED_TYPE),'^0709')
        & str_to_lower(UNIT_DESC)%in%c('amp','cap','ml','tab','vial')
      )
    ,.groups='drop'
  ) %>%
  mutate(MED_TYPE=ifelse(all_na,NA,MED_TYPE)) %>%
  select(-all_na)
```

```{r Create IC-CS identifier, include=FALSE}
prev_ICCS_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_ICCS_med
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(MED_TYPE))
    ,prev_ICCS=
      sum(MED_TYPE,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(prev_ICCS=ifelse(all_na,NA,prev_ICCS)) %>%
  select(-all_na)
```

```{r Check IC-CS distribution, eval=FALSE, include=FALSE}
prev_ICCS_identifier %>%
  group_by(HOSP,prev_ICCS) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Extract tables of IC-HIV diagnosis updates, include=FALSE}
prev_ICHIV_upd=
  uri_cath_d$prediction %>%
  left_join(
    diag_upd %>%
      select(-FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(HOSPIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(SDIAG_CODE))
    ,SDIAG_CODE=
      any(str_sub(SDIAG_CODE,1,3)%in%paste0('B',20:24))
    ,.groups='drop'
  ) %>%
  mutate(SDIAG_CODE=ifelse(all_na,NA,SDIAG_CODE)) %>%
  select(-all_na)
```

```{r Extract tables of discharged IC-HIV diagnosis, include=FALSE}
prev_ICHIV_discharge=
  uri_cath_d$prediction %>%
  left_join(
     diag_discharge %>%
      left_join(
        los_upd
        ,by=c('HOSP','CHR_NO','FEE_NO')
      ) %>%
      select(-TYPE,-FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(CPD<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CODE))
    ,CODE=
      any(str_sub(CODE,1,3)%in%paste0('B',20:24))
    ,.groups='drop'
  ) %>%
  mutate(CODE=ifelse(all_na,NA,CODE)) %>%
  select(-all_na)
```

```{r Create IC-HIV identifier, include=FALSE}
prev_ICHIV_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_ICHIV_upd
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    prev_ICHIV_discharge
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  gather(
    CRITERIA_TYPE,CRITERIA_VALUE
    ,-HOSP,-CHR_NO,-TYPE,-FEE_NO
    ,-FEE_DATE,-FEE_TIME,-FEE_CODE,-SEQ_NO,-SEQ_NO2
    ,-START,-DC,-duration,-merged,-pred_day
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CRITERIA_VALUE))
    ,prev_ICHIV=
      sum(CRITERIA_VALUE,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(prev_ICHIV=ifelse(all_na,NA,prev_ICHIV)) %>%
  select(-all_na)
```

```{r Check IC-HIV distribution, eval=FALSE, include=FALSE}
prev_ICHIV_identifier %>%
  group_by(HOSP,prev_ICHIV) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Extract tables of IC-NEO diagnosis updates, include=FALSE}
prev_ICNEO_upd=
  uri_cath_d$prediction %>%
  left_join(
    diag_upd %>%
      select(-FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(HOSPIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(SDIAG_CODE))
    ,SDIAG_CODE=
      any(str_sub(SDIAG_CODE,1,3)%in%paste0('C',str_pad(0:97,2,'left','0')))
    ,.groups='drop'
  ) %>%
  mutate(SDIAG_CODE=ifelse(all_na,NA,SDIAG_CODE)) %>%
  select(-all_na)
```

```{r Extract tables of discharged IC-NEO diagnosis, include=FALSE}
prev_ICNEO_discharge=
  uri_cath_d$prediction %>%
  left_join(
     diag_discharge %>%
      left_join(
        los_upd
        ,by=c('HOSP','CHR_NO','FEE_NO')
      ) %>%
      select(-TYPE,-FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(CPD<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CODE))
    ,CODE=
      any(str_sub(CODE,1,3)%in%paste0('C',str_pad(0:97,2,'left','0')))
    ,.groups='drop'
  ) %>%
  mutate(CODE=ifelse(all_na,NA,CODE)) %>%
  select(-all_na)
```

```{r Create IC-NEO identifier, include=FALSE}
prev_ICNEO_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_ICNEO_upd
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    prev_ICNEO_discharge
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  gather(
    CRITERIA_TYPE,CRITERIA_VALUE
    ,-HOSP,-CHR_NO,-TYPE,-FEE_NO
    ,-FEE_DATE,-FEE_TIME,-FEE_CODE,-SEQ_NO,-SEQ_NO2
    ,-START,-DC,-duration,-merged,-pred_day
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CRITERIA_VALUE))
    ,prev_ICNEO=
      sum(CRITERIA_VALUE,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(prev_ICNEO=ifelse(all_na,NA,prev_ICNEO)) %>%
  select(-all_na)
```

```{r Check IC-NEO distribution, eval=FALSE, include=FALSE}
prev_ICNEO_identifier %>%
  group_by(HOSP,prev_ICNEO) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Create previous IC identifier, include=FALSE}
prev_IC_identifier=
  prev_ICCS_identifier %>%
  left_join(
    prev_ICHIV_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    prev_ICNEO_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(prev_IC=(prev_ICCS+prev_ICHIV+prev_ICNEO)>0) %>%
  select(-prev_ICCS,-prev_ICHIV,-prev_ICNEO)
```

```{r Check previous IC distribution, eval=FALSE, include=FALSE}
prev_IC_identifier %>%
  group_by(HOSP,prev_IC) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Create creatinine >2 identifier, include=FALSE}
creatinine_gt2_identifier=
  creatinine_identifier %>%
  mutate(CREATININE=CREATININE>2) %>%
  rename(CREATININE_GT2=CREATININE) %>%
  select(-EGFR)
```

```{r Check creatinine >2 distribution, eval=FALSE, include=FALSE}
creatinine_gt2_identifier %>%
  group_by(HOSP,CREATININE_GT2) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Identify MED_CODE for SGLT-2 drugs, eval=FALSE, include=FALSE}
raw_data1b %>%
  .[str_detect(names(.),'^v_med_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^MED_|DESC')]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  mutate(
    SGLT2=
      ALISE_DESC %>%
      str_to_lower() %>%
      str_replace_all('/',' ') %>%
      str_remove_all('[:digit:]|[:punct:]|庫|針頭')
  ) %>%
  select(HOSP,MED_CODE,MED_TYPE,SGLT2,everything()) %>%
  lapply(X=1,Y=.,\(X,Y){
    Z=Y %>%
      filter(
        str_detect(
          str_to_lower(MED_CODE)
          ,filter(.,str_detect(str_to_lower(MED_TYPE),'^090808')) %>%
            pull(MED_CODE) %>%
            str_to_lower() %>%
            unique() %>%
            paste0(collapse='|')
        )
      )
    
    print(
      Z %>%
        filter(SGLT2%in%c(''))
    )
    
    print(
      Z %>%
        group_by(HOSP,MED_TYPE,SGLT2,MED_CODE) %>%
        summarize(n=n(),.groups='drop') %>%
        group_by(HOSP,MED_TYPE,SGLT2) %>%
        summarize(
          MED_CODES=paste0(MED_CODE,collapse='|')
          ,n=sum(n)
          ,.groups='drop'
        ) %>%
        spread(HOSP,n,fill=0) %>%
        arrange(MED_TYPE,MED_CODES,w,t,s)
    )
    
    Y
  }) %>%
  .[[1]] %>%
  filter(str_detect(str_to_lower(MED_TYPE),'^090808')) %>%
  group_by(HOSP,MED_TYPE,SGLT2,MED_CODE) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP,MED_TYPE,SGLT2) %>%
  summarize(
    MED_CODES=paste0(MED_CODE,collapse='|')
    ,n=sum(n)
    ,.groups='drop'
  ) %>%
  spread(HOSP,n,fill=0) %>%
  arrange(MED_TYPE,MED_CODES,s)
```

```{r Extract tables of SGLT-2 medication orders, include=FALSE}
prev_SGLT2_med=
  uri_cath_d$prediction %>%
  left_join(
    med_order %>%
      select(-UD_SEQ,-UD_SEQ_OLD,-MED_CODE)
    ,by=c('HOSP','FEE_NO')
  ) %>%
  filter(BEGIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(MED_TYPE))
    ,MED_TYPE=
      any(str_detect(str_to_lower(MED_TYPE),'^090808'))
    ,.groups='drop'
  ) %>%
  mutate(MED_TYPE=ifelse(all_na,NA,MED_TYPE)) %>%
  select(-all_na)
```

```{r Create SGLT-2 identifier, include=FALSE}
prev_SGLT2_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_SGLT2_med
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(MED_TYPE))
    ,prev_SGLT2=
      sum(MED_TYPE,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(prev_SGLT2=ifelse(all_na,NA,prev_SGLT2)) %>%
  select(-all_na)
```

```{r Check SGLT-2 distribution, eval=FALSE, include=FALSE}
prev_SGLT2_identifier %>%
  group_by(HOSP,prev_SGLT2) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Determine FEE_CODE for double-J, include=FALSE}
doublej=
  raw_data %>%
  .[str_detect(names(.),'^v_fee_basic')] %>%
  lapply(select,FEE_CODE,FEE_DESC) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  filter(
    str_detect(
      str_to_lower(FEE_CODE)
      ,filter(
          .
          ,str_detect(
            str_to_lower(FEE_DESC)
            ,'雙丁輸尿管導管置入術|經膀胱鏡逆行尿管導管'
          )
        ) %>%
        pull(FEE_CODE) %>%
        str_sub(1,str_count(.)-1) %>%
        str_to_lower() %>%
        unique() %>%
        paste0(collapse='|')
    )
  ) %>%
  mutate(exist='yes') %>%
  spread(HOSP,exist,fill='no') %>%
  arrange(FEE_CODE,w,t,s) %>%
  filter(str_detect(str_to_lower(FEE_CODE),'f50019c|f50010c'))

doublej %>%
  knitr::kable()
```

```{r Extract tables of double-J orders, include=FALSE}
doublej_order=
  raw_data1b %>%
  .[str_detect(names(.),'^v_ipd_fee')] %>%
  lapply(filter,FEE_CODE%in%doublej$FEE_CODE) %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(
            .
            ,paste0(
              c(
                '^CHR_NO'
                ,'^FEE_NO'
                ,'^FEE_DATE'
                ,'^FEE_TIME'
                ,'^FEE_CODE'
                ,'^SEQ_NO'
                ,'^START'
                ,'^DC'
              )
              ,collapse='|'
            )
          )]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
        ,TYPE=
          str_sub(X,3,5)
      )
  ) %>%
  do.call(rbind,.) %>%
  select_at(c(
    intersect(colnames(uri_cath_d$prediction),colnames(.))
    ,setdiff(colnames(.),colnames(uri_cath_d$prediction))
  )) %>%
  mutate(
    START_TIME=
      ifelse(
        !is.na(START_DATE) & is.na(START_TIME)
        ,'0000'
        ,START_TIME
      )
    ,DC_TIME=
      ifelse(
        !is.na(DC_DATE) & is.na(DC_TIME)
        ,'0000'
        ,DC_TIME
      )
  ) %>%
  mutate_at(
    c('START_DATE','DC_DATE')
    ,\(x)
    as.numeric(x)+(2023-112)*10000
  ) %>%
  mutate_at(
    c('START_DATE','DC_DATE')
    ,\(x)
    paste0(
      str_sub(x,1,4)
      ,'-'
      ,str_sub(x,5,6)
      ,'-'
      ,str_sub(x,7,8)
    )
  ) %>%
  mutate_at(
    c('START_TIME','DC_TIME')
    ,\(x)
    paste0(
      str_sub(x,1,2)
      ,':'
      ,str_sub(x,3,4)
    )
  ) %>%
  unite(START,START_DATE,START_TIME,sep=' ') %>%
  unite(DC,DC_DATE,DC_TIME,sep=' ') %>%
  mutate_at(
    c('START','DC')
    ,\(x)
    ifelse(
      str_count(x)==16
      & str_count(x,'-')==2
      & str_count(x,' ')==1
      & str_count(x,'\\:')==1
      ,x
      ,NA
    )
  ) %>%
  mutate_at(c('START','DC'),ymd_hm) %>%
  arrange(HOSP,CHR_NO,TYPE,FEE_NO,START,DC) %>%
  select(HOSP,CHR_NO,FEE_CODE,START,DC) %>%
  rename(
    DOUBLEJ_FEE_CODE=FEE_CODE
    ,DOUBLEJ_START=START
    ,DOUBLEJ_DC=DC
  )
```

```{r Create double-J identifier, include=FALSE}
doublej_identifier=
  uri_cath_d$prediction %>%
  left_join(
    left_join(
        .
        ,doublej_order
        ,by=c('HOSP','CHR_NO')
      ) %>%
      filter(DOUBLEJ_START<pred_day) %>%
      select(-DOUBLEJ_START,-DOUBLEJ_DC)
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(DOUBLEJ_FEE_CODE=!is.na(DOUBLEJ_FEE_CODE)) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    doublej=
      any(DOUBLEJ_FEE_CODE)
    ,.groups='drop'
  )
```

```{r Check double-J distribution, eval=FALSE, include=FALSE}
doublej_identifier %>%
  group_by(HOSP,doublej) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Extract tables of urological diagnosis updates, include=FALSE}
prev_urodiag_upd=
  uri_cath_d$prediction %>%
  left_join(
    diag_upd %>%
      select(-FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(HOSPIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(SDIAG_CODE))
    ,SDIAG_CODE=
      any(str_sub(SDIAG_CODE,1,3)%in%c(paste0('N',c(20:23,40,13,32)),'R31'))
    ,.groups='drop'
  ) %>%
  mutate(SDIAG_CODE=ifelse(all_na,NA,SDIAG_CODE)) %>%
  select(-all_na)
```

```{r Extract tables of discharged urological diagnosis, include=FALSE}
prev_urodiag_discharge=
  uri_cath_d$prediction %>%
  left_join(
     diag_discharge %>%
      left_join(
        los_upd
        ,by=c('HOSP','CHR_NO','FEE_NO')
      ) %>%
      select(-TYPE,-FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(CPD<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CODE))
    ,CODE=
      any(str_sub(CODE,1,3)%in%c(paste0('N',c(20:23,40,13,32)),'R31'))
    ,.groups='drop'
  ) %>%
  mutate(CODE=ifelse(all_na,NA,CODE)) %>%
  select(-all_na)
```

```{r Create urological diagnosis identifier, include=FALSE}
prev_urodiag_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_urodiag_upd
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    prev_urodiag_discharge
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  gather(
    CRITERIA_TYPE,CRITERIA_VALUE
    ,-HOSP,-CHR_NO,-TYPE,-FEE_NO
    ,-FEE_DATE,-FEE_TIME,-FEE_CODE,-SEQ_NO,-SEQ_NO2
    ,-START,-DC,-duration,-merged,-pred_day
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CRITERIA_VALUE))
    ,prev_urodiag=
      sum(CRITERIA_VALUE,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(prev_urodiag=ifelse(all_na,NA,prev_urodiag)) %>%
  select(-all_na)
```

```{r Check urological diagnosis distribution, eval=FALSE, include=FALSE}
prev_urodiag_identifier %>%
  group_by(HOSP,prev_urodiag) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Determine FEE_CODE for urodynamic exam, include=FALSE}
urodyn=
  raw_data %>%
  .[str_detect(names(.),'^v_fee_basic')] %>%
  lapply(select,FEE_CODE,FEE_DESC) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  filter(
    str_detect(
      str_to_lower(FEE_CODE)
      ,filter(
          .
          ,str_detect(
            str_to_lower(FEE_DESC)
            ,paste0(
              c('壓力尿流速圖'
                ,'外括約肌肌電圖'
                ,'尿道壓力測量'
                ,'尿流量圖'
                ,'膀胱超音波尿量測量'
                ,'應力尿道壓力測試'
                ,'錄影尿動力學')
              ,collapse='|'
            )
          )
        ) %>%
        pull(FEE_CODE) %>%
        str_sub(1,str_count(.)-1) %>%
        str_to_lower() %>%
        unique() %>%
        paste0(collapse='|')
    )
  ) %>%
  mutate(exist='yes') %>%
  spread(HOSP,exist,fill='no') %>%
  arrange(FEE_CODE,w,t,s) %>%
  filter(
    str_detect(
      str_to_lower(FEE_CODE)
      ,'21010c|21011c|21012c|21003c|21004c|21005c|21006a|21006b'
    )
  )

urodyn %>%
  knitr::kable()
```

```{r Extract tables of urodynamic exam orders, include=FALSE}
urodyn_order=
  raw_data1b %>%
  .[str_detect(names(.),'^v_ipd_fee')] %>%
  lapply(filter,FEE_CODE%in%urodyn$FEE_CODE) %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(
            .
            ,paste0(
              c(
                '^CHR_NO'
                ,'^FEE_NO'
                ,'^FEE_DATE'
                ,'^FEE_TIME'
                ,'^FEE_CODE'
                ,'^SEQ_NO'
                ,'^START'
                ,'^DC'
              )
              ,collapse='|'
            )
          )]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
        ,TYPE=
          str_sub(X,3,5)
      )
  ) %>%
  do.call(rbind,.) %>%
  select_at(c(
    intersect(colnames(uri_cath_d$prediction),colnames(.))
    ,setdiff(colnames(.),colnames(uri_cath_d$prediction))
  )) %>%
  mutate(
    START_TIME=
      ifelse(
        !is.na(START_DATE) & is.na(START_TIME)
        ,'0000'
        ,START_TIME
      )
    ,DC_TIME=
      ifelse(
        !is.na(DC_DATE) & is.na(DC_TIME)
        ,'0000'
        ,DC_TIME
      )
  ) %>%
  mutate_at(
    c('START_DATE','DC_DATE')
    ,\(x)
    as.numeric(x)+(2023-112)*10000
  ) %>%
  mutate_at(
    c('START_DATE','DC_DATE')
    ,\(x)
    paste0(
      str_sub(x,1,4)
      ,'-'
      ,str_sub(x,5,6)
      ,'-'
      ,str_sub(x,7,8)
    )
  ) %>%
  mutate_at(
    c('START_TIME','DC_TIME')
    ,\(x)
    paste0(
      str_sub(x,1,2)
      ,':'
      ,str_sub(x,3,4)
    )
  ) %>%
  unite(START,START_DATE,START_TIME,sep=' ') %>%
  unite(DC,DC_DATE,DC_TIME,sep=' ') %>%
  mutate_at(
    c('START','DC')
    ,\(x)
    ifelse(
      str_count(x)==16
      & str_count(x,'-')==2
      & str_count(x,' ')==1
      & str_count(x,'\\:')==1
      ,x
      ,NA
    )
  ) %>%
  mutate_at(c('START','DC'),ymd_hm) %>%
  arrange(HOSP,CHR_NO,TYPE,FEE_NO,START,DC) %>%
  select(HOSP,CHR_NO,FEE_CODE,START,DC) %>%
  rename(
    URODYN_FEE_CODE=FEE_CODE
    ,URODYN_START=START
    ,URODYN_DC=DC
  )
```

```{r Create urodynamic exam identifier, include=FALSE}
urodyn_identifier=
  uri_cath_d$prediction %>%
  left_join(
    left_join(
        .
        ,urodyn_order
        ,by=c('HOSP','CHR_NO')
      ) %>%
      filter(URODYN_START<pred_day) %>%
      select(-URODYN_START,-URODYN_DC)
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(URODYN_FEE_CODE=!is.na(URODYN_FEE_CODE)) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    urodyn=
      any(URODYN_FEE_CODE)
    ,.groups='drop'
  )
```

```{r Check urodynamic exam distribution, eval=FALSE, include=FALSE}
urodyn_identifier %>%
  group_by(HOSP,urodyn) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Create urological issue identifier, include=FALSE}
prev_uro_identifier=
  doublej_identifier %>%
  left_join(
    prev_urodiag_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    urodyn_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(prev_uro=(doublej+prev_urodiag+urodyn)>0) %>%
  select(-doublej,-prev_urodiag,-urodyn)
```

```{r Check urological issue distribution, eval=FALSE, include=FALSE}
prev_uro_identifier %>%
  group_by(HOSP,prev_uro) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Extract tables of previous 6-mo UTI diagnosis updates, include=FALSE}
prev_utidiag6m_upd=
  uri_cath_d$prediction %>%
  left_join(
    diag_upd %>%
      rename(prev_FEE_NO=FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(HOSPIN>=(pred_day-months(6)) & HOSPIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(SDIAG_CODE))
    ,SDIAG_CODE=
      setdiff(
        ifelse(str_sub(SDIAG_CODE,1,3)%in%c('N39','599'),prev_FEE_NO,NA)
        ,FEE_NO
      ) %>%
      unique() %>%
      .[!is.na(.)] %>%
      paste0(collapse='|')
    ,.groups='drop'
  ) %>%
  mutate(SDIAG_CODE=ifelse(all_na,NA,SDIAG_CODE)) %>%
  select(-all_na)
```

```{r Extract tables of discharged previous 6-mo UTI diagnosis, include=FALSE}
prev_utidiag6m_discharge=
  uri_cath_d$prediction %>%
  left_join(
    diag_discharge %>%
      left_join(
        los_upd
        ,by=c('HOSP','CHR_NO','FEE_NO')
      ) %>%
      select(-TYPE) %>%
      rename(prev_FEE_NO=FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(CPD>=(pred_day-months(6)) & CPD<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CODE))
    ,CODE=
      setdiff(
        ifelse(str_sub(CODE,1,3)%in%c('N39','599'),prev_FEE_NO,NA)
        ,FEE_NO
      ) %>%
      unique() %>%
      .[!is.na(.)] %>%
      paste0(collapse='|')
    ,.groups='drop'
  ) %>%
  mutate(CODE=ifelse(all_na,NA,CODE)) %>%
  select(-all_na)
```

```{r Create previous 6-mo UTI identifier, include=FALSE}
prev_utidiag6m_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_utidiag6m_upd
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    prev_utidiag6m_discharge
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  gather(
    CRITERIA_TYPE,CRITERIA_VALUE
    ,-HOSP,-CHR_NO,-TYPE,-FEE_NO
    ,-FEE_DATE,-FEE_TIME,-FEE_CODE,-SEQ_NO,-SEQ_NO2
    ,-START,-DC,-duration,-merged,-pred_day
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CRITERIA_VALUE))
    ,prev_utidiag6m=
      CRITERIA_VALUE %>%
      paste0(collapse='|') %>%
      str_split('\\|') %>%
      .[[1]] %>%
      unique() %>%
      .[!is.na(.) & .!=''] %>%
      length()
    ,.groups='drop'
  ) %>%
  mutate(prev_utidiag6m=ifelse(all_na,NA,prev_utidiag6m)) %>%
  select(-all_na)
```

```{r Check prev. 6-mo UTI missingness and outliers, eval=FALSE, include=FALSE}
prev_utidiag6m_identifier %>%
  group_by(HOSP) %>%
  mutate(
    min=min(prev_utidiag6m,na.rm=T)
    ,q1=quantile(prev_utidiag6m,0.25,na.rm=T)
    ,q2=quantile(prev_utidiag6m,0.5,na.rm=T)
    ,q3=quantile(prev_utidiag6m,0.75,na.rm=T)
    ,max=max(prev_utidiag6m,na.rm=T)
    ,n=n()
    ,missing=sum(is.na(prev_utidiag6m))
  ) %>%
  ungroup() %>%
  mutate(
    outlier=
      prev_utidiag6m<(q1-1.5*(q3-q1))
      | prev_utidiag6m>(q3+1.5*(q3-q1))
  ) %>%
  group_by(HOSP,min,q1,q2,q3,max,n,missing) %>%
  summarize(outliers=sum(outlier,na.rm=T),.groups='drop')
```

```{r Create prev. 6-m UTI >2 identifier, include=FALSE}
prev_utidiag_6mgt2_identifier=
  prev_utidiag6m_identifier %>%
  mutate(prev_utidiag_6mgt2=prev_utidiag6m>2) %>%
  select(-prev_utidiag6m)
```

```{r Check prev. 6-m UTI >2 distribution, eval=FALSE, include=FALSE}
prev_utidiag_6mgt2_identifier %>%
  group_by(HOSP,prev_utidiag_6mgt2) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Extract tables of previous 1-y UTI diagnosis updates, include=FALSE}
prev_utidiag1y_upd=
  uri_cath_d$prediction %>%
  left_join(
    diag_upd %>%
      rename(prev_FEE_NO=FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(HOSPIN>=(pred_day-years(1)) & HOSPIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(SDIAG_CODE))
    ,SDIAG_CODE=
      setdiff(
        ifelse(str_sub(SDIAG_CODE,1,3)%in%c('N39','599'),prev_FEE_NO,NA)
        ,FEE_NO
      ) %>%
      unique() %>%
      .[!is.na(.)] %>%
      paste0(collapse='|')
    ,.groups='drop'
  ) %>%
  mutate(SDIAG_CODE=ifelse(all_na,NA,SDIAG_CODE)) %>%
  select(-all_na)
```

```{r Extract tables of discharged previous 1-y UTI diagnosis, include=FALSE}
prev_utidiag1y_discharge=
  uri_cath_d$prediction %>%
  left_join(
    diag_discharge %>%
      left_join(
        los_upd
        ,by=c('HOSP','CHR_NO','FEE_NO')
      ) %>%
      select(-TYPE) %>%
      rename(prev_FEE_NO=FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(CPD>=(pred_day-years(1)) & CPD<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CODE))
    ,CODE=
      setdiff(
        ifelse(str_sub(CODE,1,3)%in%c('N39','599'),prev_FEE_NO,NA)
        ,FEE_NO
      ) %>%
      unique() %>%
      .[!is.na(.)] %>%
      paste0(collapse='|')
    ,.groups='drop'
  ) %>%
  mutate(CODE=ifelse(all_na,NA,CODE)) %>%
  select(-all_na)
```

```{r Create previous 1-y UTI identifier, include=FALSE}
prev_utidiag1y_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_utidiag1y_upd
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    prev_utidiag1y_discharge
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  gather(
    CRITERIA_TYPE,CRITERIA_VALUE
    ,-HOSP,-CHR_NO,-TYPE,-FEE_NO
    ,-FEE_DATE,-FEE_TIME,-FEE_CODE,-SEQ_NO,-SEQ_NO2
    ,-START,-DC,-duration,-merged,-pred_day
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CRITERIA_VALUE))
    ,prev_utidiag1y=
      CRITERIA_VALUE %>%
      paste0(collapse='|') %>%
      str_split('\\|') %>%
      .[[1]] %>%
      unique() %>%
      .[!is.na(.) & .!=''] %>%
      length()
    ,.groups='drop'
  ) %>%
  mutate(prev_utidiag1y=ifelse(all_na,NA,prev_utidiag1y)) %>%
  select(-all_na)
```

```{r Check prev. 1-y UTI missingness and outliers, eval=FALSE, include=FALSE}
prev_utidiag1y_identifier %>%
  group_by(HOSP) %>%
  mutate(
    min=min(prev_utidiag1y,na.rm=T)
    ,q1=quantile(prev_utidiag1y,0.25,na.rm=T)
    ,q2=quantile(prev_utidiag1y,0.5,na.rm=T)
    ,q3=quantile(prev_utidiag1y,0.75,na.rm=T)
    ,max=max(prev_utidiag1y,na.rm=T)
    ,n=n()
    ,missing=sum(is.na(prev_utidiag1y))
  ) %>%
  ungroup() %>%
  mutate(
    outlier=
      prev_utidiag1y<(q1-1.5*(q3-q1))
      | prev_utidiag1y>(q3+1.5*(q3-q1))
  ) %>%
  group_by(HOSP,min,q1,q2,q3,max,n,missing) %>%
  summarize(outliers=sum(outlier,na.rm=T),.groups='drop')
```

```{r Create prev. 1-y UTI >3 identifier, include=FALSE}
prev_utidiag_1ygt3_identifier=
  prev_utidiag1y_identifier %>%
  mutate(prev_utidiag_1ygt3=prev_utidiag1y>3) %>%
  select(-prev_utidiag1y)
```

```{r Check prev. 1-y UTI >3 distribution, eval=FALSE, include=FALSE}
prev_utidiag_1ygt3_identifier %>%
  group_by(HOSP,prev_utidiag_1ygt3) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Create prev. 6-m/1-y UTI identifier, include=FALSE}
prev_utidiag_6mgt2_1ygt3_identifier=
  prev_utidiag_6mgt2_identifier %>%
  left_join(
    prev_utidiag_1ygt3_identifier
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  mutate(prev_utidiag_6mgt2_1ygt3=(prev_utidiag_6mgt2+prev_utidiag_1ygt3)>0) %>%
  select(-prev_utidiag_6mgt2,-prev_utidiag_1ygt3)
```

```{r Check prev. 6-m/1-y UTI distribution, eval=FALSE, include=FALSE}
prev_utidiag_6mgt2_1ygt3_identifier %>%
  group_by(HOSP,prev_utidiag_6mgt2_1ygt3) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Extract tables of neurological diagnosis updates, include=FALSE}
prev_neurodiag_upd=
  uri_cath_d$prediction %>%
  left_join(
    diag_upd %>%
      select(-FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(HOSPIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(SDIAG_CODE))
    ,SDIAG_CODE=
      any(
        str_sub(SDIAG_CODE,1,3)
        %in%c('N31','G95','G83','I67','I69','I61','G35')
      )
    ,.groups='drop'
  ) %>%
  mutate(SDIAG_CODE=ifelse(all_na,NA,SDIAG_CODE)) %>%
  select(-all_na)
```

```{r Extract tables of discharged neurological diagnosis, include=FALSE}
prev_neurodiag_discharge=
  uri_cath_d$prediction %>%
  left_join(
     diag_discharge %>%
      left_join(
        los_upd
        ,by=c('HOSP','CHR_NO','FEE_NO')
      ) %>%
      select(-TYPE,-FEE_NO)
    ,by=c('HOSP','CHR_NO')
  ) %>%
  filter(CPD<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CODE))
    ,CODE=
      any(
        str_sub(CODE,1,3)
        %in%c('N31','G95','G83','I67','I69','I61','G35')
      )
    ,.groups='drop'
  ) %>%
  mutate(CODE=ifelse(all_na,NA,CODE)) %>%
  select(-all_na)
```

```{r Create neurological issue identifier, include=FALSE}
prev_neuro_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_neurodiag_upd
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  left_join(
    prev_neurodiag_discharge
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  gather(
    CRITERIA_TYPE,CRITERIA_VALUE
    ,-HOSP,-CHR_NO,-TYPE,-FEE_NO
    ,-FEE_DATE,-FEE_TIME,-FEE_CODE,-SEQ_NO,-SEQ_NO2
    ,-START,-DC,-duration,-merged,-pred_day
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(CRITERIA_VALUE))
    ,prev_neuro=
      sum(CRITERIA_VALUE,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(prev_neuro=ifelse(all_na,NA,prev_neuro)) %>%
  select(-all_na)
```

```{r Check neurological issue distribution, eval=FALSE, include=FALSE}
prev_neuro_identifier %>%
  group_by(HOSP,prev_neuro) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Identify MED_CODE for sys. antibiotic drugs, eval=FALSE, include=FALSE}
raw_data1b %>%
  .[str_detect(names(.),'^v_med_basic')] %>%
  lapply(\(x)
    x %>%
      select_at(
        colnames(.) %>%
          .[str_detect(.,'^MED_|DESC')]
      )
  ) %>%
  lapply(
    X=names(.)
    ,Y=.
    ,\(X,Y)
    Y[[X]] %>%
      mutate(
        HOSP=
          str_sub(X,str_count(X),str_count(X))
      )
  ) %>%
  do.call(rbind,.) %>%
  mutate(
    AB=
      ALISE_DESC %>%
      str_to_lower() %>%
      str_replace_all('/',' ') %>%
      str_remove_all('[:digit:]|[:punct:]|庫|針頭')
  ) %>%
  select(HOSP,MED_CODE,MED_TYPE,AB,everything()) %>%
  lapply(X=1,Y=.,\(X,Y){
    Z=Y %>%
      filter(
        str_detect(
          str_to_lower(MED_CODE)
          ,filter(.,str_detect(str_to_lower(MED_TYPE),'^1001')) %>%
            pull(MED_CODE) %>%
            str_to_lower() %>%
            unique() %>%
            paste0(collapse='|')
        )
      )
    
    print(
      Z %>%
        filter(AB%in%c(''))
    )
    
    print(
      Z %>%
        group_by(HOSP,MED_TYPE,AB,MED_CODE) %>%
        summarize(n=n(),.groups='drop') %>%
        group_by(HOSP,MED_TYPE,AB) %>%
        summarize(
          MED_CODES=paste0(MED_CODE,collapse='|')
          ,n=sum(n)
          ,.groups='drop'
        ) %>%
        spread(HOSP,n,fill=0) %>%
        arrange(MED_TYPE,MED_CODES,w,t,s)
    )
    
    Y
  }) %>%
  .[[1]] %>%
  filter(
    str_detect(str_to_lower(MED_TYPE),'^1001')
    & str_to_lower(UNIT_DESC)%in%c('amp','cap','ml','tab','vial')
  ) %>%
  group_by(HOSP,MED_TYPE,AB,MED_CODE) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP,MED_TYPE,AB) %>%
  summarize(
    MED_CODES=paste0(MED_CODE,collapse='|')
    ,n=sum(n)
    ,.groups='drop'
  ) %>%
  spread(HOSP,n,fill=0) %>%
  arrange(MED_TYPE,MED_CODES,s)
```

```{r Extract tables of sys. antibiotic medication orders, include=FALSE}
prev_AB_med=
  uri_cath_d$prediction %>%
  left_join(
    med_order %>%
      select(-UD_SEQ,-UD_SEQ_OLD,-MED_CODE)
    ,by=c('HOSP','FEE_NO')
  ) %>%
  filter(BEGIN>=START-days(7) & BEGIN<pred_day) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(MED_TYPE))
    ,MED_TYPE=
      any(
        str_detect(str_to_lower(MED_TYPE),'^1001')
        & str_to_lower(UNIT_DESC)%in%c('amp','cap','ml','tab','vial')
      )
    ,.groups='drop'
  ) %>%
  mutate(MED_TYPE=ifelse(all_na,NA,MED_TYPE)) %>%
  select(-all_na)
```

```{r Create sys. antibiotic identifier, include=FALSE}
prev_AB_identifier=
  uri_cath_d$prediction %>%
  left_join(
    prev_AB_med
    ,by=colnames(uri_cath_d$prediction)
  ) %>%
  group_by_at(colnames(uri_cath_d$prediction)) %>%
  summarize(
    all_na=
      all(is.na(MED_TYPE))
    ,prev_AB=
      sum(MED_TYPE,na.rm=T)>0
    ,.groups='drop'
  ) %>%
  mutate(prev_AB=ifelse(all_na,NA,prev_AB)) %>%
  select(-all_na)
```

```{r Check sys. antibiotic distribution, eval=FALSE, include=FALSE}
prev_AB_identifier %>%
  group_by(HOSP,prev_AB) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(HOSP) %>%
  mutate(
    total=sum(n)
    ,p=round(n/total*100,2)
  ) %>%
  ungroup()
```

```{r Join all identifiers, include=FALSE}
identifiers=
  uri_cath_d$prediction %>%
  
  left_join(outcome_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(age_group_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(age_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(icu_10d_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(icu_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(cath_d_6d_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(cath_d_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(los_4d_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(los_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(prev_cath_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(sex_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(prev_DM_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_DMdiag_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_DMmed_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(immob_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(indication_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(prev_DMrel_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_HYP_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_DMinsulin_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(bmi_gt30_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(bmi_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_DMneph_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(poor_nutr_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(albumin_lt3.5_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(albumin_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(creatinine_lt0.5_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(creatinine_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(prev_FI_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_FIAD_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_FILX_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(prev_IC_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_ICCS_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_ICHIV_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_ICNEO_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(creatinine_gt2_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(prev_SGLT2_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(prev_uro_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(doublej_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_urodiag_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(urodyn_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(prev_utidiag_6mgt2_1ygt3_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_utidiag_6mgt2_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_utidiag6m_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_utidiag_1ygt3_identifier,by=colnames(uri_cath_d$prediction)) %>%
  left_join(prev_utidiag1y_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(prev_neuro_identifier,by=colnames(uri_cath_d$prediction)) %>%
  
  left_join(prev_AB_identifier,by=colnames(uri_cath_d$prediction))
```

```{r Incorporate identifiers to each selection scenario, include=FALSE}
whole_data_d3=
  list(
    prediction=
      identifiers %>%
      filter(duration>2)
    ,order=
      identifiers %>%
      filter(duration>2) %>%
      group_by_at(colnames(uri_cath_d3$order)) %>%
      filter(pred_day==max(pred_day)) %>%
      ungroup()
    ,visit=
      identifiers %>%
      filter(duration>2) %>%
      group_by_at(colnames(uri_cath_d3$visit)) %>%
      filter(pred_day==max(pred_day)) %>%
      ungroup()
    ,patient=
      identifiers %>%
      filter(duration>2) %>%
      group_by_at(colnames(uri_cath_d3$patient)) %>%
      filter(pred_day==max(pred_day)) %>%
      ungroup()
  )

whole_data_d=
  list(
    prediction=
      identifiers
    ,order=
      identifiers %>%
      group_by_at(colnames(uri_cath_d$order)) %>%
      filter(pred_day==max(pred_day)) %>%
      ungroup()
    ,visit=
      identifiers %>%
      group_by_at(colnames(uri_cath_d$visit)) %>%
      filter(pred_day==max(pred_day)) %>%
      ungroup()
    ,patient=
      identifiers %>%
      group_by_at(colnames(uri_cath_d$patient)) %>%
      filter(pred_day==max(pred_day)) %>%
      ungroup()
  )
```

```{r eval=FALSE, include=FALSE}
# unified_id=
#   raw_data %>%
#   .[str_detect(names(.),'^v_chr_basic')] %>%
#   lapply(\(x)
#     x %>%
#       select_at(
#         colnames(.) %>%
#           .[str_detect(
#             .
#             ,paste0(
#               c(
#                 '^ID_NO'
#                 ,'^CHR_NO'
#               )
#               ,collapse='|'
#             )
#           )]
#       )
#   ) %>%
#   lapply(
#     X=names(.)
#     ,Y=.
#     ,\(X,Y)
#     Y[[X]] %>%
#       mutate(
#         HOSP=
#           str_sub(X,str_count(X),str_count(X))
#       )
#   ) %>%
#   do.call(rbind,.) %>%
#   group_by(ID_NO) %>%
#   mutate(
#     EV_HOSP=
#       HOSP %>%
#       unique() %>%
#       length()
#     ,WHICH_HOSP=
#       HOSP %>%
#       unique() %>%
#       sort() %>%
#       paste0(collapse='')
#   ) %>%
#   ungroup() %>%
#   select(HOSP,EV_HOSP,WHICH_HOSP,everything())
```

```{r eval=FALSE, include=FALSE}
# unified_id %>%
#   group_by(HOSP,ID_NO) %>%
#   summarize(n=n(),.groups='drop') %>%
#   spread(HOSP,n,fill=0) %>%
#   mutate(EVER_VISIT_HOSPs=s+t+w) %>%
#   arrange(desc(EVER_VISIT_HOSPs),desc(s),desc(t),desc(w)) %>%
#   group_by(EVER_VISIT_HOSPs) %>%
#   summarize(ID_NOs=n())
```

```{r eval=FALSE, include=FALSE}
# whole_data_d3$prediction %>%
#   left_join(
#     unified_id
#     ,by=c('HOSP','CHR_NO')
#   ) %>%
#   group_by(EV_HOSP) %>%
#   summarize(n=n())
# 
# whole_data_d$prediction %>%
#   left_join(
#     unified_id
#     ,by=c('HOSP','CHR_NO')
#   ) %>%
#   group_by(EV_HOSP) %>%
#   summarize(n=n())
```

```{r eval=FALSE, include=FALSE}
# partition_d3=list()
# 
# set.seed(seed); partition_d3$training=
#   which(
#     whole_data_d3$prediction$HOSP%in%c('t')
#     & left_join(
#         whole_data_d3$prediction
#         ,unified_id
#         ,by=c('HOSP','CHR_NO')
#       )$EV_HOSP%in%c(1)
#   ) %>%
#   sample(
#     0.8*sum(whole_data_d3$prediction$HOSP%in%c('t'))-sum(
#       left_join(
#         whole_data_d3$prediction
#         ,unified_id
#         ,by=c('HOSP','CHR_NO')
#       )$EV_HOSP%in%c(2,3)
#     )
#     ,F
#   ) %>%
#   c(which(
#     left_join(
#       whole_data_d3$prediction
#       ,unified_id
#       ,by=c('HOSP','CHR_NO')
#     )$EV_HOSP%in%c(2,3)
#   )) %>%
#   sort()
# 
# partition_d3$validation=
#   which(whole_data_d3$prediction$HOSP%in%c('t')) %>%
#   setdiff(partition_d3$training)
# 
# partition_d3$test=
#   which(whole_data_d3$prediction$HOSP%in%c('s','w'))
# 
# partition_d=list()
# 
# set.seed(seed); partition_d$training=
#   which(
#     whole_data_d$prediction$HOSP%in%c('s','t')
#     & left_join(
#         whole_data_d$prediction
#         ,unified_id
#         ,by=c('HOSP','CHR_NO')
#       )$EV_HOSP%in%c(1)
#   ) %>%
#   sample(
#     0.8*sum(whole_data_d$prediction$HOSP%in%c('s','t'))-sum(
#       left_join(
#         whole_data_d$prediction
#         ,unified_id
#         ,by=c('HOSP','CHR_NO')
#       )$EV_HOSP%in%c(2,3)
#     )
#     ,F
#   ) %>%
#   c(which(
#     left_join(
#       whole_data_d$prediction
#       ,unified_id
#       ,by=c('HOSP','CHR_NO')
#     )$EV_HOSP%in%c(2,3)
#   )) %>%
#   sort()
# 
# partition_d$validation=
#   which(whole_data_d$prediction$HOSP%in%c('s','t')) %>%
#   setdiff(partition_d$training)
# 
# partition_d$test=
#   which(whole_data_d$prediction$HOSP%in%c('w'))
```

```{r eval=FALSE, include=FALSE}
# whole_data_d3$prediction %>%
#   mutate(
#     set=
#       case_when(
#         seq(nrow(.))%in%partition_d3$training~'Training'
#         ,seq(nrow(.))%in%partition_d3$validation~'Validation'
#         ,seq(nrow(.))%in%partition_d3$test~'Test'
#       )
#   ) %>%
#   left_join(
#     unified_id
#     ,by=c('HOSP','CHR_NO')
#   ) %>%
#   group_by(set,EV_HOSP,WHICH_HOSP,outcome) %>%
#   summarize(n=n(),.groups='drop') %>%
#   spread(outcome,n,fill=0) %>%
#   lapply(X=1:2,Y=.,\(X,Y){
#     if(X==1){
#       filter(Y,set!='Test')
#     }else{
#       filter(Y,set=='Test')
#     }
#   }) %>%
#   lapply(
#     mutate
#     ,subtotal=
#       `FALSE`+`TRUE`#+`<NA>`
#     ,total=
#       sum(subtotal)
#     ,p=
#       subtotal/total
#   ) %>%
#   do.call(rbind,.) %>%
#   group_by(set) %>%
#   mutate(
#     FALSE_set=sum(`FALSE`)
#     ,TRUE_set=sum(`TRUE`)
#     # ,`<NA>_set`=sum(`<NA>`)
#     ,subtotal_set=sum(subtotal)
#     ,p_set=sum(p)
#   ) %>%
#   ungroup() %>%
#   mutate_at(c('p','p_set'),\(x)round(x*100,2))
# 
# whole_data_d$prediction %>%
#   mutate(
#     set=
#       case_when(
#         seq(nrow(.))%in%partition_d$training~'Training'
#         ,seq(nrow(.))%in%partition_d$validation~'Validation'
#         ,seq(nrow(.))%in%partition_d$test~'Test'
#       )
#   ) %>%
#   left_join(
#     unified_id
#     ,by=c('HOSP','CHR_NO')
#   ) %>%
#   group_by(set,EV_HOSP,WHICH_HOSP,outcome) %>%
#   summarize(n=n(),.groups='drop') %>%
#   spread(outcome,n,fill=0) %>%
#   lapply(X=1:2,Y=.,\(X,Y){
#     if(X==1){
#       filter(Y,set!='Test')
#     }else{
#       filter(Y,set=='Test')
#     }
#   }) %>%
#   lapply(
#     mutate
#     ,subtotal=
#       `FALSE`+`TRUE`+`<NA>`
#     ,total=
#       sum(subtotal)
#     ,p=
#       subtotal/total
#   ) %>%
#   do.call(rbind,.) %>%
#   group_by(set) %>%
#   mutate(
#     FALSE_set=sum(`FALSE`)
#     ,TRUE_set=sum(`TRUE`)
#     ,`<NA>_set`=sum(`<NA>`)
#     ,subtotal_set=sum(subtotal)
#     ,p_set=sum(p)
#   ) %>%
#   ungroup() %>%
#   mutate_at(c('p','p_set'),\(x)round(x*100,2))
```

```{r Description of variables, include=FALSE}
variable_description=
  c('UTI','UTI diagnosis'
    ,'URICULT','Urine culture order'
    ,'PNEU','Pneumonia diagnosis'
    ,'AGE_GROUP','Age group'
    ,'AGE','Age (years)'
    ,'ICU_STAY_10D','ICU stay >=10 days'
    ,'ICU_STAY_D','ICU stay (days)'
    ,'CATH_D_6D','Duration of catheterization >=6 days'
    ,'CATH_D','Duration of catheterization (days)'
    ,'LOS_4D','Hospital stay >=4 days'
    ,'LOS','Hospital stay (days)'
    ,'CATH_PREV','Previous catheterization (n)'
    ,'SEX_TYPE','Sex (F/M)'
    ,'prev_DM','T2DM diagnosis/DM medication'
    ,'prev_DMdiag','T2DM diagnosis'
    ,'prev_DMmed','DM medication'
    ,'immob','Immobilization (protective restraint)'
    ,'indication','Indication of cathetherization'
    ,'prev_DMrel','DM-related factors'
    ,'prev_HYP','Hypertension diagnosis'
    ,'prev_DMinsulin','Exogenous insulin'
    ,'BMI_GT30','BMI >30 kg/m^2'
    ,'BMI','BMI (kg/m^2)'
    ,'prev_DMneph','DM with nephropathy'
    ,'poor_nutr','Poor nutrition (serum albumin/creatinine)'
    ,'ALBUMIN_LT3.5','Serum albumin <3.5 g/dL'
    ,'ALBUMIN','Serum albumin (g/dL)'
    ,'CREATININE_LT0.5'
          ,'Serum creatinine <0.5 mg/dL & eGFR >=105 mL/min/1.73 m^2'
    ,'CREATININE','Serum creatinine (mg/dL)'
    ,'EGFR','eGFR (mL/min/1.73 m^2)'
    ,'prev_FI','FI medication (antidiarrheal/laxative)'
    ,'prev_FIAD','Antidiarrheal drugs'
    ,'prev_FILX','Laxative drugs'
    ,'prev_IC','Impaired immune function'
    ,'prev_ICCS','Corticosteroid drugs'
    ,'prev_ICHIV','HIV'
    ,'prev_ICNEO','Malignant neoplasms'
    ,'CREATININE_GT2','Serum creatinine >2 mg/dL'
    ,'prev_SGLT2','Sodium-glucose co-transporter (SGLT)-2 inhibitors'
    ,'prev_uro','Urological issues (double-J/diagnosis/urodynamics)'
    ,'doublej','Double-J ureteral stent insertion'
    ,'prev_urodiag','Urological diagnosis'
    ,'urodyn','Urodynamic examination'
    ,'prev_utidiag_6mgt2_1ygt3'
            ,'Previous UTI diagnosis >2x/6 mo or >3/1 y'
    ,'prev_utidiag_6mgt2','Previous UTI diagnosis >2x/6 mo'
    ,'prev_utidiag6m','Previous UTI diagnosis last 6 mo (n)'
    ,'prev_utidiag_1ygt3','Previous UTI diagnosis >3/1 y'
    ,'prev_utidiag1y','Previous UTI diagnosis last 1 y (n)'
    ,'prev_neuro','Neurological issues (diagnosis)'
    ,'prev_AB','Antibiotic drugs last 7 d'
  ) %>%
  matrix(
    ncol=2
    ,byrow=T
    ,dimnames=list(NULL,c('variable','description'))
  ) %>%
  as.data.frame()
```

```{r Function for descriptive analysis, include=FALSE}
descriptive_analysis=
  \(whole_data_d_prediction){
    whole_data_d_prediction %>%
      colnames() %>%
      .[!.%in%c(
        colnames(uri_cath_d$prediction)
        ,'outcome'
        ,'ICU_STAY_N'
        ,'HEIGHT'
        ,'WEIGHT'
      )] %>%
      lapply(\(x){
        y=whole_data_d_prediction %>%
          select_at(c('HOSP','outcome',x)) %>%
          rename_at(x,\(x)'variable')
        if(class(y$variable)%in%c('logical','factor')){
          z=y %>%
            group_by(HOSP,outcome,variable) %>%
            summarize(n=n(),.groups='drop') %>%
            group_by(HOSP,outcome) %>%
            mutate(
              total=sum(n)
              ,p=round(n/total*100,2)
            ) %>%
            ungroup() %>%
            mutate_at(
              c('n','total')
              ,\(x)ifelse(str_count(x)>4,format(x,big.mark=','),x)
            )
          
          if(class(y$variable)=='logical'){
            z=z %>%
              mutate_at(
                c('outcome','variable')
                ,\(x){
                  x=ifelse(x,'2-Yes','1-No')
                  x=ifelse(is.na(x),'3-Missing',x)
              })
          }else{
            z=z %>%
              mutate_at(
                c('outcome')
                ,\(x){
                  x=ifelse(x,'2-Yes','1-No')
                  x=ifelse(is.na(x),'3-Missing',x)
              }) %>%
              mutate(
                variable=
                  ifelse(
                    is.na(variable)
                    ,paste0(
                      length(levels(variable))+1
                      ,'-Missing'
                    )
                    ,paste0(
                      as.numeric(variable)
                      ,'-'
                      ,as.character(variable)
                    )
                  )
              )
          }
          
          z %>%
            mutate(
              n=paste0('(',n,')')
              ,total=paste0('(n=',total,')')
            ) %>%
            unite(HOSP,HOSP,outcome,total,sep=' ') %>%
            unite(p,p,n,sep=' ') %>%
            spread(HOSP,p,fill='0.00 (0)') %>%
            rename(unit=variable) %>%
            mutate(unit=paste0(unit,', % (n)')) %>%
            mutate(variable=x) %>%
            select(variable,everything())
        }else{
          z=suppressWarnings(
            y  %>%
              group_by(HOSP) %>%
              mutate(
                min=min(variable,na.rm=T)
                ,q1=quantile(variable,0.25,na.rm=T)
                ,q2=quantile(variable,0.5,na.rm=T)
                ,q3=quantile(variable,0.75,na.rm=T)
                ,max=max(variable,na.rm=T)
              ) %>%
              ungroup() %>%
              group_by(HOSP,outcome) %>%
              mutate(
                n=n()
                ,missing=sum(is.na(variable))
              ) %>%
              ungroup()
          )
          
          z %>%
            mutate(
              outlier=
                variable<(q1-1.5*(q3-q1))
                | variable>(q3+1.5*(q3-q1))
            ) %>%
            group_by(HOSP,outcome,n,missing) %>%
            summarize(
              outliers=sum(outlier,na.rm=T)
              ,avg=round(mean(ifelse(outlier,NA,variable),na.rm=T),2)
              ,std=round(sd(ifelse(outlier,NA,variable),na.rm=T),2)
              ,.groups='drop'
            ) %>%
            mutate_at(c('avg','std'),\(x)ifelse(is.nan(x),NA,x)) %>%
            rename(total=n) %>%
            mutate(
              avg_std=total-(missing+outliers)
            ) %>%
            gather(unit,value,-HOSP,-outcome,-avg,-std,-total) %>%
            mutate(p=round(value/total*100,2)) %>%
            mutate_at(
              c('value','total','avg','std')
              ,\(x)ifelse(str_count(x)>4,format(x,big.mark=','),x)
            ) %>%
            mutate_at(
              c('outcome')
              ,\(x){
                x=ifelse(x,'2-Yes','1-No')
                x=ifelse(is.na(x),'3-Missing',x)
            }) %>%
            mutate(
              value=paste0('(',value,')')
              ,total=paste0('(n=',total,')')
            ) %>%
            unite(HOSP,HOSP,outcome,total,sep=' ') %>%
            mutate(std=paste0('(',std,')')) %>%
            unite(avg_std,avg,std,sep=' ') %>%
            mutate(avg_std=ifelse(str_detect(avg_std,'NA'),'-',avg_std)) %>%
            unite(p,p,value,sep=' ') %>%
            lapply(X=1,Y=.,\(X,Y){
              Y %>%
                filter(unit=='avg_std') %>%
                select(-p) %>%
                mutate(
                  unit='1-Neither missing/outliers, avg. (SD)'
                ) %>%
                spread(HOSP,avg_std,fill='-') %>%
                rbind(
                  Y %>%
                    mutate(
                      unit=
                        case_when(
                          unit=='avg_std'~'1-Neither missing/outliers, % (n)'
                          ,unit=='outliers'~'2-Outliers, % (n)'
                          ,unit=='missing'~'3-Missing, % (n)'
                        )
                    ) %>%
                    select(-avg_std) %>%
                    spread(HOSP,p,fill='0.00 (0)')
                ) %>%
                mutate(variable=x) %>%
                select(variable,everything())
            }) %>%
            .[[1]]
        }
      }) %>%
      do.call(rbind,.) %>%
      left_join(
        variable_description
        ,by='variable'
      ) %>%
      mutate(description=ifelse(duplicated(variable),'',description)) %>%
      mutate(variable=description) %>%
      select(-description) %>%
      mutate(unit=str_sub(unit,3,str_count(unit)))
  }
```

```{r Conduct descriptive analyses, eval=FALSE, include=FALSE}
whole_data_d3$prediction %>%
  mutate(
    HOSP=
      ifelse(
        HOSP%in%c('s','w')
        ,'ws'
        ,HOSP
      )
  ) %>%
  descriptive_analysis() %>%
  write_csv('data/desc_whole_data_d3_prediction.csv')

whole_data_d$prediction %>%
  mutate(
    HOSP=
      ifelse(
        HOSP%in%c('s','t')
        ,'st'
        ,HOSP
      )
  ) %>%
  descriptive_analysis() %>%
  write_csv('data/desc_whole_data_d_prediction.csv')
```

```{r Function for missing analysis, include=FALSE}
missing_analysis=function(whole_data_d_prediction){
  whole_data_d_prediction %>%
    colnames(.) %>%
    .[!.%in%c(
      colnames(uri_cath_d$prediction)
      ,'outcome'
      ,'UTI'
      ,'URICULT'
      ,'PNEU'
      ,'ICU_STAY_N'
      ,'HEIGHT'
      ,'WEIGHT'
    )] %>%
    lapply(c,'outcome') %>%
    lapply(rev) %>%
    lapply(paste0,collapse='~') %>%
    lapply(as.formula) %>%
    lapply(
      \(x){
        y=whole_data_d_prediction %>%
          select_at(
            colnames(.) %>%
              .[!.%in%c(
                colnames(uri_cath_d$prediction)
                ,'outcome'
                ,'UTI'
                ,'URICULT'
                ,'PNEU'
                ,'ICU_STAY_N'
                ,'HEIGHT'
                ,'WEIGHT'
              )]
          ) %>%
          lapply(\(x)ifelse(is.na(x),'1-missing','0-non-missing')) %>%
          lapply(factor) %>%
          as.data.frame()
        
        whole_data_d_prediction %>%
          mutate_at(
            c('outcome')
            ,\(x){
              x=ifelse(x,'2-Yes','1-No')
              x=ifelse(is.na(x),'3-Missing',x)
          }) %>%
          pull(outcome) %>%
          unique() %>%
          lapply(\(z){
            k=whole_data_d_prediction %>%
              select(outcome) %>%
              mutate_at(
                c('outcome')
                ,\(x){
                  x=ifelse(x,'2-Yes','1-No')
                  x=ifelse(is.na(x),'3-Missing',x)
              }) %>%
              mutate(
                outcome=
                  ifelse(
                    outcome==z
                    ,paste0('1-outcome==',z)
                    ,paste0('0-outcome!=',z)
                  ) %>%
                  factor()
              ) %>%
              cbind(y)
            
            l=k %>%
              group_by_at(as.character(x)[2:3]) %>%
              summarize(n=n(),.groups='drop')
            
            if(nrow(l)>=4){
              x %>%
                glm(family=binomial(),data=k) %>%
                broom::tidy() %>%
                mutate(
                  outcome=z
                  ,variable=
                    x %>%
                    as.character() %>%
                    .[3]
                ) %>%
                select(outcome,variable,everything()) %>%
                filter(term!='(Intercept)')
            }else{
              data.frame(
                outcome=z
                ,variable=
                  x %>%
                  as.character() %>%
                  .[3]
                ,term='1-missing'
                ,estimate=NA
                ,std.error=NA
                ,statistic=NA
                ,p.value=NA
              )
            }
          }) %>%
          do.call(rbind,.)
    }) %>%
    do.call(rbind,.) %>%
    mutate(
      term=str_remove_all(term,variable)
      ,OR=round(exp(estimate),2)
      ,LB=round(exp(estimate-std.error),2)
      ,UB=round(exp(estimate+std.error),2)
      ,FDR=p.adjust(p.value,method='BH')
      ,FDR=
        ifelse(
          FDR<0.001
          ,'p<0.001'
          ,ifelse(
            FDR<=0.05
            ,paste0('p=',round(FDR,3))
            ,'p>0.05'
          )
        )
      ,
    ) %>%
    select(outcome,variable,OR,LB,UB,FDR) %>%
    unite(CI,LB,UB,sep=' to ') %>%
    unite(CI_FDR,CI,FDR,sep='; ') %>%
    mutate(CI_FDR=paste0('(',CI_FDR,')')) %>%
    unite(OR_CI_FDR,OR,CI_FDR,sep=' ') %>%
    mutate(OR_CI_FDR=ifelse(OR_CI_FDR=='NA (NA to NA; NA)','-',OR_CI_FDR)) %>%
    mutate(variable=factor(variable,unique(variable))) %>%
    spread(outcome,OR_CI_FDR,fill='-') %>%
    left_join(
      variable_description
      ,by='variable'
    ) %>%
    mutate(variable=description) %>%
    select(-description)
}
```

```{r Conduct missing analyses, eval=FALSE, include=FALSEE}
whole_data_d3$prediction %>%
  filter(HOSP%in%c('t')) %>%
  missing_analysis() %>%
  write_csv('data/missing_whole_data_d3_prediction.csv')

whole_data_d$prediction %>%
  filter(HOSP%in%c('s','t')) %>%
  missing_analysis() %>%
  write_csv('data/missing_whole_data_d_prediction.csv')
```

```{r Function for outlier analysis, include=FALSE}
outlier_analysis=function(whole_data_d_prediction){
  whole_data_d_prediction %>%
    .[,sapply(.,is.numeric)] %>%
    colnames(.) %>%
    .[!.%in%c(
      colnames(uri_cath_d$prediction)
      ,'outcome'
      ,'UTI'
      ,'URICULT'
      ,'PNEU'
      ,'ICU_STAY_N'
      ,'HEIGHT'
      ,'WEIGHT'
    )] %>%
    lapply(c,'outcome') %>%
    lapply(rev) %>%
    lapply(paste0,collapse='~') %>%
    lapply(as.formula) %>%
    lapply(
      \(x){
        y=whole_data_d_prediction %>%
          .[,sapply(.,is.numeric)] %>%
          select_at(
            colnames(.) %>%
              .[!.%in%c(
                colnames(uri_cath_d$prediction)
                ,'outcome'
                ,'UTI'
                ,'URICULT'
                ,'PNEU'
                ,'ICU_STAY_N'
                ,'HEIGHT'
                ,'WEIGHT'
              )]
          ) %>%
          lapply(\(x){
            y=suppressWarnings(
              data.frame(variable=x) %>%
                summarize(
                  q1=quantile(variable,0.25,na.rm=T)
                  ,q3=quantile(variable,0.75,na.rm=T)
                ) %>%
                mutate(
                  lb=q1-1.5*(q3-q1)
                  ,ub=q3+1.5*(q3-q1)
                )
            )
            ifelse(x<y$lb | x>y$ub | is.na(x),'1-outlier','0-non-outlier')
          }) %>%
          lapply(factor) %>%
          as.data.frame()
        
        whole_data_d_prediction %>%
          mutate_at(
            c('outcome')
            ,\(x){
              x=ifelse(x,'2-Yes','1-No')
              x=ifelse(is.na(x),'3-Missing',x)
          }) %>%
          pull(outcome) %>%
          unique() %>%
          lapply(\(z){
            k=whole_data_d_prediction %>%
              select(outcome) %>%
              mutate_at(
                c('outcome')
                ,\(x){
                  x=ifelse(x,'2-Yes','1-No')
                  x=ifelse(is.na(x),'3-Missing',x)
              }) %>%
              mutate(
                outcome=
                  ifelse(
                    outcome==z
                    ,paste0('1-outcome==',z)
                    ,paste0('0-outcome!=',z)
                  ) %>%
                  factor()
              ) %>%
              cbind(y)
            
            l=k %>%
              group_by_at(as.character(x)[2:3]) %>%
              summarize(n=n(),.groups='drop')
            
            if(nrow(l)>=4){
              x %>%
                glm(family=binomial(),data=k) %>%
                broom::tidy() %>%
                mutate(
                  outcome=z
                  ,variable=
                    x %>%
                    as.character() %>%
                    .[3]
                ) %>%
                select(outcome,variable,everything()) %>%
                filter(term!='(Intercept)')
            }else{
              data.frame(
                outcome=z
                ,variable=
                  x %>%
                  as.character() %>%
                  .[3]
                ,term='1-outlier'
                ,estimate=NA
                ,std.error=NA
                ,statistic=NA
                ,p.value=NA
              )
            }
          }) %>%
          do.call(rbind,.)
    }) %>%
    do.call(rbind,.) %>%
    mutate(
      term=str_remove_all(term,variable)
      ,OR=round(exp(estimate),2)
      ,LB=round(exp(estimate-std.error),2)
      ,UB=round(exp(estimate+std.error),2)
      ,FDR=p.adjust(p.value,method='BH')
      ,FDR=
        ifelse(
          FDR<0.001
          ,'p<0.001'
          ,ifelse(
            FDR<=0.05
            ,paste0('p=',round(FDR,3))
            ,'p>0.05'
          )
        )
      ,
    ) %>%
    select(outcome,variable,OR,LB,UB,FDR) %>%
    unite(CI,LB,UB,sep=' to ') %>%
    unite(CI_FDR,CI,FDR,sep='; ') %>%
    mutate(CI_FDR=paste0('(',CI_FDR,')')) %>%
    unite(OR_CI_FDR,OR,CI_FDR,sep=' ') %>%
    mutate(OR_CI_FDR=ifelse(OR_CI_FDR=='NA (NA to NA; NA)','-',OR_CI_FDR)) %>%
    mutate(variable=factor(variable,unique(variable))) %>%
    spread(outcome,OR_CI_FDR,fill='-') %>%
    left_join(
      variable_description
      ,by='variable'
    ) %>%
    mutate(variable=description) %>%
    select(-description)
}
```

```{r Conduct outlier analyses, eval=FALSE, include=FALSEE}
whole_data_d3$prediction %>%
  filter(HOSP%in%c('t')) %>%
  outlier_analysis() %>%
  write_csv('data/outlier_whole_data_d3_prediction.csv')

whole_data_d$prediction %>%
  filter(HOSP%in%c('s','t')) %>%
  outlier_analysis() %>%
  write_csv('data/outlier_whole_data_d_prediction.csv')
```

```{r Create data partition identifier}
partition_d3=list()

set.seed(seed); partition_d3$training=
  which(whole_data_d3$prediction$HOSP%in%c('t')) %>%
  sample(0.8*length(.),F) %>%
  sort()

partition_d3$validation=
  which(whole_data_d3$prediction$HOSP%in%c('t')) %>%
  setdiff(partition_d3$training)

partition_d3$test=
  which(whole_data_d3$prediction$HOSP%in%c('s','w'))

partition_d=list()

set.seed(seed); partition_d$training=
  which(whole_data_d$prediction$HOSP%in%c('s','t')) %>%
  sample(0.8*length(.),F) %>%
  sort()

partition_d$validation=
  which(whole_data_d$prediction$HOSP%in%c('s','t')) %>%
  setdiff(partition_d$training)

partition_d$test=
  which(whole_data_d$prediction$HOSP%in%c('w'))
```

```{r Show the sample size in each data partition}
whole_data_d3$prediction %>%
  mutate(
    set=
      case_when(
        seq(nrow(.))%in%partition_d3$training~'Training'
        ,seq(nrow(.))%in%partition_d3$validation~'Validation'
        ,seq(nrow(.))%in%partition_d3$test~'Test'
      ) %>%
      factor(c('Training','Validation','Test'))
  ) %>%
  group_by(set,outcome) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(set) %>%
  mutate(subtotal=sum(n)) %>%
  ungroup() %>%
  mutate(
    outcome=
      ifelse(
        is.na(outcome)
        ,'3-Missing'
        ,ifelse(
          outcome==T
          ,'2-Yes'
          ,'1-No'
        )
      )
  ) %>%
  spread(outcome,n,fill=0) %>%
  left_join(
    rbind(
        filter(.,set%in%c('Training','Validation')) %>%
          mutate(
            total=sum(subtotal)
            ,proportion=round(subtotal/total*100,2)
          )
        ,filter(.,set%in%c('Test')) %>%
          mutate(
            total=sum(subtotal)
            ,proportion=round(subtotal/total*100,2)
          )
      ) %>%
      select(set,total,proportion)
    ,by='set'
  ) %>%
  select(set,total,subtotal,proportion,everything()) %>%
  mutate(prevalence=round(`2-Yes`/subtotal*100,2))

whole_data_d$prediction %>%
  mutate(
    set=
      case_when(
        seq(nrow(.))%in%partition_d$training~'Training'
        ,seq(nrow(.))%in%partition_d$validation~'Validation'
        ,seq(nrow(.))%in%partition_d$test~'Test'
      ) %>%
      factor(c('Training','Validation','Test'))
  ) %>%
  group_by(set,outcome) %>%
  summarize(n=n(),.groups='drop') %>%
  group_by(set) %>%
  mutate(subtotal=sum(n)) %>%
  ungroup() %>%
  mutate(
    outcome=
      ifelse(
        is.na(outcome)
        ,'3-Missing'
        ,ifelse(
          outcome==T
          ,'2-Yes'
          ,'1-No'
        )
      )
  ) %>%
  spread(outcome,n,fill=0) %>%
  left_join(
    rbind(
        filter(.,set%in%c('Training','Validation')) %>%
          mutate(
            total=sum(subtotal)
            ,proportion=round(subtotal/total*100,2)
          )
        ,filter(.,set%in%c('Test')) %>%
          mutate(
            total=sum(subtotal)
            ,proportion=round(subtotal/total*100,2)
          )
      ) %>%
      select(set,total,proportion)
    ,by='set'
  ) %>%
  select(set,total,subtotal,proportion,everything()) %>%
  mutate(prevalence=round(`2-Yes`/subtotal*100,2))
```

```{r Lists of columns of interests and their connections, include=FALSE}
source('R/cols_int-variable.R')
source('R/cols_int_conn-variable.R')
```

```{r Select columns of interests, include=FALSE}
if(all(c(1)%in%comp_req)){
  raw_data2=
    raw_data %>%
    names() %>%
    `names<-`(.,.) %>%
    lapply(\(x){
      y=x %>%
        str_remove_all('^v_|_s$|_t$|_w$') %>%
        str_to_upper()
      
      if(y%in%cols_int$dataset){
        z=cols_int  %>%
          filter(dataset%in%y) %>%
          pull(select) %>%
          str_split('\\|') %>%
          .[[1]]
        
        raw_data[[x]] %>%
          select_at(
            colnames(.) %>%
              .[.%in%z]
          )
      }else{
        NULL
      }
    }) %>%
    .[!sapply(.,is.null)]
  
  saveRDS(raw_data2,'data/raw_data2.rds')
}else{
  raw_data2=readRDS('data/raw_data2.rds')
}
```

```{r Create a table to convert _NO to integer identifier}
id_no=
  raw_data2 %>%
  .[sapply(.,\(x)colnames(x) %>% str_detect('_NO$') %>% any())] %>%
  lapply(\(x)x %>% select_at(colnames(.) %>% .[str_detect(.,'_NO$')])) %>%
  lapply(mutate_all,as.character) %>%
  lapply(gather) %>%
  lapply(\(x)filter(x,!duplicated(x))) %>%
  do.call(rbind,.) %>%
  `rownames<-`(NULL) %>%
  filter(!duplicated(.)) %>%
  arrange(key,value) %>%
  group_by(key) %>%
  mutate(id_subject=seq(n()))
```

```{r}
raw_data2$v_chr_basic_s
raw_data2$v_opd_basic_s
raw_data2$v_ipd_basic_s
raw_data2$v_opd_med_s
raw_data2$v_bio_inf_s
raw_data2$v_opd_exper_s
raw_data2$v_labresult_s
raw_data2$v_chr_icd_s
raw_data2$v_ud_order_s
```

```{r An empty list for outpatient and inpatient datasets, include=FALSE}
raw_data3=list()
```

```{r Join outpatient datasets for each s/t/w, include=FALSE}
raw_data3$OPD=list()

for(x in c('_s$','_t$','_w$')){
  cat(x)
  y=raw_data2 %>%
    .[str_detect(names(.),x)] %>%
    `names<-`(str_remove_all(names(.),'^v_|_s$|_t$|_w$')) %>%
    `names<-`(str_to_upper(names(.)))
  
  z=cols_int_conn[c(3:6,13:14),] %>%
    filter(left%in%names(y) & right%in%names(y))
  
  for(i in rev(unique(z$level))){
    k=z %>%
      filter(level==i)
    
    for(j in seq(nrow(k))){
      cat(k$left[j],'-',k$right[j])
      
      y[[k$left[j]]]=
        y[[k$left[j]]] %>%
          left_join(
            y[[k$right[j]]]
            ,by=k$by[j]
          )
      
      cat('|')
    }
    
    y=y %>%
      .[!names(.)%in%k$right]
  }
  
  l=z %>%
    slice(1) %>%
    pull(left)
  
  cat('\n')
  raw_data3$OPD[[str_remove_all(x,'_|\\$')]]=
    y[[l]]
}

rm(x,y,z,k,l,i,j)
```

```{r Join inpatient datasets for each s/t/w, include=FALSE}
raw_data3$IPD=list()

for(x in c('_s$','_t$','_w$')){
  cat(x)
  y=raw_data2 %>%
    .[str_detect(names(.),x)] %>%
    `names<-`(str_remove_all(names(.),'^v_|_s$|_t$|_w$')) %>%
    `names<-`(str_to_upper(names(.)))
  
  z=cols_int_conn[c(7:12,13:14),] %>%
    filter(left%in%names(y) & right%in%names(y))
  
  for(i in rev(unique(z$level))){
    k=z %>%
      filter(level==i)
    
    for(j in seq(nrow(k))){
      cat(k$left[j],'-',k$right[j])
      
      Y=seq(
          1
          ,nrow(y[[k$left[j]]])
          ,length=ifelse(k$right[j]!='UD_ORDER',1,200)
        ) %>%
        floor()
      
      M=list()
      for(X in seq(length(Y))){
        cat('.')
        Z=c(Y[X],ifelse(X==length(Y),nrow(y[[k$left[j]]]),Y[X+1]-1))
        
        K=y[[k$left[j]]] %>%
          .[Z[1]:Z[2],]
        
        L=y[[k$right[j]]] %>%
          .[.[,k$by[j]]%in%K[[k$by[j]]],]
        
        M[[X]]=
          K %>%
          left_join(L,by=k$by[j])
      }
      
      y[[k$left[j]]]=
        M %>%
        do.call(rbind,.)
      
      rm(X,Y,Z,K,L,M)
      
      cat('|')
    }
    
    y=y %>%
      .[!names(.)%in%k$right]
  }
  
  l=z %>%
    slice(1) %>%
    pull(left)
  
  cat('\n')
  raw_data3$IPD[[str_remove_all(x,'_|\\$')]]=
    y[[l]]
}

rm(x,y,z,k,l,i,j)
```



































